import { createClient } from '@/lib/supabase/server'
import { requireRole } from '@/lib/utils/auth'
import { NextRequest, NextResponse } from 'next/server'
import { z } from 'zod'

// Validation schema for creating/updating marketing draft
const marketingDraftSchema = z.object({
  social_caption: z.string().optional(),
  social_hashtags: z.string().optional(),
  suggested_platforms: z.array(z.string()).optional(),
  newsletter_mention: z.string().optional(),
  approved: z.boolean().optional(),
  published: z.boolean().optional(),
})

/**
 * GET /api/events/[id]/marketing-draft
 * Get marketing draft for an event
 */
export async function GET(
  _request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const authResult = await requireRole(['admin', 'manager'])

  if ('error' in authResult) {
    return NextResponse.json(
      { error: authResult.error },
      { status: authResult.status }
    )
  }

  const { id } = await params
  const supabase = await createClient()

  // Verify event exists
  const { data: event } = await supabase
    .from('events')
    .select('id, title')
    .eq('id', id)
    .single()

  if (!event) {
    return NextResponse.json({ error: 'Event not found' }, { status: 404 })
  }

  // Get marketing draft
  const { data: draft, error } = await supabase
    .from('event_marketing_drafts')
    .select('*')
    .eq('event_id', id)
    .order('created_at', { ascending: false })
    .limit(1)
    .single()

  // If no draft exists, return null (not an error)
  if (error && error.code === 'PGRST116') {
    return NextResponse.json(null)
  }

  if (error) {
    return NextResponse.json({ error: error.message }, { status: 500 })
  }

  return NextResponse.json(draft)
}

/**
 * POST /api/events/[id]/marketing-draft
 * Create a marketing draft for an event (auto-generated by AI or manual)
 */
export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const authResult = await requireRole(['admin', 'manager'])

  if ('error' in authResult) {
    return NextResponse.json(
      { error: authResult.error },
      { status: authResult.status }
    )
  }

  const { id } = await params

  let body
  try {
    body = await request.json()
  } catch {
    return NextResponse.json({ error: 'Invalid JSON body' }, { status: 400 })
  }

  // Validate request body
  const validation = marketingDraftSchema.safeParse(body)
  if (!validation.success) {
    return NextResponse.json(
      {
        error: 'Validation failed',
        details: validation.error.errors,
      },
      { status: 400 }
    )
  }

  const supabase = await createClient()

  // Verify event exists
  const { data: event } = await supabase
    .from('events')
    .select('id')
    .eq('id', id)
    .single()

  if (!event) {
    return NextResponse.json({ error: 'Event not found' }, { status: 404 })
  }

  // Check if draft already exists
  const { data: existingDraft } = await supabase
    .from('event_marketing_drafts')
    .select('id')
    .eq('event_id', id)
    .single()

  if (existingDraft) {
    return NextResponse.json(
      { error: 'Marketing draft already exists for this event. Use PATCH to update.' },
      { status: 400 }
    )
  }

  // Create marketing draft
  const { data: newDraft, error } = await supabase
    .from('event_marketing_drafts')
    .insert({
      event_id: id,
      ...validation.data,
    })
    .select()
    .single()

  if (error) {
    return NextResponse.json({ error: error.message }, { status: 500 })
  }

  return NextResponse.json(newDraft, { status: 201 })
}

/**
 * PATCH /api/events/[id]/marketing-draft
 * Update marketing draft for an event
 */
export async function PATCH(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const authResult = await requireRole(['admin', 'manager'])

  if ('error' in authResult) {
    return NextResponse.json(
      { error: authResult.error },
      { status: authResult.status }
    )
  }

  const { id } = await params

  let body
  try {
    body = await request.json()
  } catch {
    return NextResponse.json({ error: 'Invalid JSON body' }, { status: 400 })
  }

  // Validate request body
  const validation = marketingDraftSchema.safeParse(body)
  if (!validation.success) {
    return NextResponse.json(
      {
        error: 'Validation failed',
        details: validation.error.errors,
      },
      { status: 400 }
    )
  }

  const supabase = await createClient()

  // Find existing draft
  const { data: existingDraft } = await supabase
    .from('event_marketing_drafts')
    .select('id')
    .eq('event_id', id)
    .single()

  if (!existingDraft) {
    return NextResponse.json(
      { error: 'Marketing draft not found for this event' },
      { status: 404 }
    )
  }

  // Update draft
  const { data: updatedDraft, error } = await supabase
    .from('event_marketing_drafts')
    .update(validation.data)
    .eq('event_id', id)
    .select()
    .single()

  if (error) {
    return NextResponse.json({ error: error.message }, { status: 500 })
  }

  return NextResponse.json(updatedDraft)
}

/**
 * DELETE /api/events/[id]/marketing-draft
 * Delete marketing draft for an event
 */
export async function DELETE(
  _request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const authResult = await requireRole(['admin', 'manager'])

  if ('error' in authResult) {
    return NextResponse.json(
      { error: authResult.error },
      { status: authResult.status }
    )
  }

  const { id } = await params
  const supabase = await createClient()

  const { error } = await supabase
    .from('event_marketing_drafts')
    .delete()
    .eq('event_id', id)

  if (error) {
    return NextResponse.json({ error: error.message }, { status: 500 })
  }

  return NextResponse.json({ message: 'Marketing draft deleted successfully' })
}
