-- Migration: Test questions for Food Safety guides G-FS-012 through G-FS-022
-- Generated: 2026-02-08
-- 11 guides × 8 questions × 4 languages = 352 rows

-- G-FS-012: Cross-Contamination Prevention (English)
INSERT INTO training_test_questions (guide_code, language, question, options, explanation, sort_order) VALUES
('G-FS-012', 'en', 'What is the primary purpose of using color-coded cutting boards?', '[{"text":"To make the kitchen look organized","correct":false},{"text":"To prevent cross-contamination between different food types","correct":true},{"text":"To identify which chef uses which board","correct":false},{"text":"To comply with aesthetic standards","correct":false}]', 'Color-coded cutting boards prevent cross-contamination by ensuring raw and ready-to-eat foods are prepared on separate surfaces.', 1),
('G-FS-012', 'en', 'When should you wash your hands during food preparation?', '[{"text":"Only at the start of your shift","correct":false},{"text":"Only when visibly dirty","correct":false},{"text":"Between handling different food types, especially raw and cooked","correct":true},{"text":"Once per hour","correct":false}]', 'Hands must be washed between handling different food types to prevent transferring harmful bacteria from raw to ready-to-eat foods.', 2),
('G-FS-012', 'en', 'Where should raw meat be stored in relation to ready-to-eat food in the refrigerator?', '[{"text":"On the shelf above ready-to-eat food","correct":false},{"text":"On the same shelf as ready-to-eat food","correct":false},{"text":"Below ready-to-eat food to prevent dripping","correct":true},{"text":"It doesn''t matter as long as both are covered","correct":false}]', 'Raw products must always be stored below cooked/ready-to-eat foods to prevent drips and contamination.', 3),
('G-FS-012', 'en', 'What should you do when switching from preparing raw chicken to preparing salad?', '[{"text":"Just wipe your hands on your apron","correct":false},{"text":"Wash hands, change cutting board, sanitize work surface","correct":true},{"text":"Only change the cutting board","correct":false},{"text":"Continue using the same board if you flip it over","correct":false}]', 'Complete hygiene protocol is required: wash hands, use a different color-coded board, and sanitize the work surface between raw and ready-to-eat foods.', 4),
('G-FS-012', 'en', 'Why is it dangerous to use the same knife for raw and cooked foods without washing?', '[{"text":"The knife will become dull faster","correct":false},{"text":"It can transfer harmful bacteria from raw to cooked food","correct":true},{"text":"It affects the taste of the cooked food","correct":false},{"text":"It violates kitchen organization rules","correct":false}]', 'Using the same unwashed knife transfers bacteria from raw foods to ready-to-eat items, causing cross-contamination that can lead to foodborne illness.', 5),
('G-FS-012', 'en', 'What is the correct procedure for sanitizing a work surface after preparing raw fish?', '[{"text":"Wipe with a dry cloth","correct":false},{"text":"Rinse with water only","correct":false},{"text":"Clean with detergent, rinse, then apply sanitizer with appropriate contact time","correct":true},{"text":"Spray with sanitizer only","correct":false}]', 'Proper sanitization requires a three-step process: clean with detergent to remove debris, rinse, then apply food-safe sanitizer for the required contact time.', 6),
('G-FS-012', 'en', 'Which practice presents the highest cross-contamination risk in a kitchen?', '[{"text":"Using separate tongs for each food item","correct":false},{"text":"Storing cleaning chemicals away from food","correct":false},{"text":"Using the same cloth to wipe multiple surfaces without sanitizing between uses","correct":true},{"text":"Washing hands before starting food prep","correct":false}]', 'Using the same cloth on multiple surfaces without sanitizing spreads bacteria across the kitchen, creating widespread contamination risk.', 7),
('G-FS-012', 'en', 'What is the purpose of having dedicated equipment for allergen-free food preparation?', '[{"text":"To speed up service","correct":false},{"text":"To prevent cross-contact with allergens that could cause severe reactions","correct":true},{"text":"To organize the kitchen better","correct":false},{"text":"To reduce cleaning time","correct":false}]', 'Dedicated equipment for allergen-free preparation prevents cross-contact with allergens, protecting customers with severe allergies from potentially life-threatening reactions.', 8);

-- G-FS-012: Cross-Contamination Prevention (Spanish)
INSERT INTO training_test_questions (guide_code, language, question, options, explanation, sort_order) VALUES
('G-FS-012', 'es', '¿Cuál es el propósito principal de usar tablas de cortar codificadas por colores?', '[{"text":"Para que la cocina se vea organizada","correct":false},{"text":"Para prevenir la contaminación cruzada entre diferentes tipos de alimentos","correct":true},{"text":"Para identificar qué chef usa qué tabla","correct":false},{"text":"Para cumplir con estándares estéticos","correct":false}]', 'Las tablas de cortar codificadas por colores previenen la contaminación cruzada al asegurar que los alimentos crudos y listos para consumir se preparen en superficies separadas.', 1),
('G-FS-012', 'es', '¿Cuándo debe lavarse las manos durante la preparación de alimentos?', '[{"text":"Solo al inicio del turno","correct":false},{"text":"Solo cuando estén visiblemente sucias","correct":false},{"text":"Entre el manejo de diferentes tipos de alimentos, especialmente crudos y cocidos","correct":true},{"text":"Una vez por hora","correct":false}]', 'Las manos deben lavarse entre el manejo de diferentes tipos de alimentos para prevenir la transferencia de bacterias dañinas de alimentos crudos a los listos para consumir.', 2),
('G-FS-012', 'es', '¿Dónde debe almacenarse la carne cruda en relación con los alimentos listos para consumir en el refrigerador?', '[{"text":"En el estante superior sobre los alimentos listos para consumir","correct":false},{"text":"En el mismo estante que los alimentos listos para consumir","correct":false},{"text":"Debajo de los alimentos listos para consumir para prevenir goteos","correct":true},{"text":"No importa siempre que ambos estén cubiertos","correct":false}]', 'Los productos crudos siempre deben almacenarse debajo de los alimentos cocidos/listos para consumir para prevenir goteos y contaminación.', 3),
('G-FS-012', 'es', '¿Qué debe hacer al cambiar de preparar pollo crudo a preparar ensalada?', '[{"text":"Solo limpiar las manos en el delantal","correct":false},{"text":"Lavar manos, cambiar tabla de cortar, desinfectar superficie de trabajo","correct":true},{"text":"Solo cambiar la tabla de cortar","correct":false},{"text":"Continuar usando la misma tabla si la voltea","correct":false}]', 'Se requiere un protocolo de higiene completo: lavar manos, usar una tabla de diferente color y desinfectar la superficie de trabajo entre alimentos crudos y listos para consumir.', 4),
('G-FS-012', 'es', '¿Por qué es peligroso usar el mismo cuchillo para alimentos crudos y cocidos sin lavar?', '[{"text":"El cuchillo se desafilará más rápido","correct":false},{"text":"Puede transferir bacterias dañinas de alimentos crudos a cocidos","correct":true},{"text":"Afecta el sabor del alimento cocido","correct":false},{"text":"Viola las reglas de organización de cocina","correct":false}]', 'Usar el mismo cuchillo sin lavar transfiere bacterias de alimentos crudos a los listos para consumir, causando contaminación cruzada que puede llevar a enfermedades alimentarias.', 5),
('G-FS-012', 'es', '¿Cuál es el procedimiento correcto para desinfectar una superficie de trabajo después de preparar pescado crudo?', '[{"text":"Limpiar con un paño seco","correct":false},{"text":"Enjuagar solo con agua","correct":false},{"text":"Limpiar con detergente, enjuagar, luego aplicar desinfectante con tiempo de contacto apropiado","correct":true},{"text":"Rociar solo con desinfectante","correct":false}]', 'La desinfección adecuada requiere un proceso de tres pasos: limpiar con detergente para eliminar residuos, enjuagar, luego aplicar desinfectante apto para alimentos durante el tiempo de contacto requerido.', 6),
('G-FS-012', 'es', '¿Qué práctica presenta el mayor riesgo de contaminación cruzada en una cocina?', '[{"text":"Usar pinzas separadas para cada alimento","correct":false},{"text":"Almacenar productos químicos de limpieza lejos de los alimentos","correct":false},{"text":"Usar el mismo paño para limpiar múltiples superficies sin desinfectar entre usos","correct":true},{"text":"Lavarse las manos antes de comenzar la preparación","correct":false}]', 'Usar el mismo paño en múltiples superficies sin desinfectar propaga bacterias por toda la cocina, creando un riesgo de contaminación generalizado.', 7),
('G-FS-012', 'es', '¿Cuál es el propósito de tener equipo dedicado para preparación de alimentos sin alérgenos?', '[{"text":"Para acelerar el servicio","correct":false},{"text":"Para prevenir el contacto cruzado con alérgenos que podrían causar reacciones graves","correct":true},{"text":"Para organizar mejor la cocina","correct":false},{"text":"Para reducir el tiempo de limpieza","correct":false}]', 'El equipo dedicado para preparación sin alérgenos previene el contacto cruzado con alérgenos, protegiendo a clientes con alergias graves de reacciones potencialmente mortales.', 8);

-- G-FS-012: Cross-Contamination Prevention (Dutch)
INSERT INTO training_test_questions (guide_code, language, question, options, explanation, sort_order) VALUES
('G-FS-012', 'nl', 'Wat is het primaire doel van het gebruik van kleurgecodeerde snijplanken?', '[{"text":"Om de keuken georganiseerd te laten lijken","correct":false},{"text":"Om kruisbesmetting tussen verschillende voedselsoorten te voorkomen","correct":true},{"text":"Om te identificeren welke chef welke plank gebruikt","correct":false},{"text":"Om te voldoen aan esthetische normen","correct":false}]', 'Kleurgecodeerde snijplanken voorkomen kruisbesmetting door ervoor te zorgen dat rauwe en kant-en-klare voedingsmiddelen op afzonderlijke oppervlakken worden bereid.', 1),
('G-FS-012', 'nl', 'Wanneer moet u uw handen wassen tijdens voedselbereiding?', '[{"text":"Alleen aan het begin van uw dienst","correct":false},{"text":"Alleen wanneer ze zichtbaar vuil zijn","correct":false},{"text":"Tussen het hanteren van verschillende voedselsoorten, vooral rauw en gekookt","correct":true},{"text":"Eenmaal per uur","correct":false}]', 'Handen moeten worden gewassen tussen het hanteren van verschillende voedselsoorten om overdracht van schadelijke bacteriën van rauw naar kant-en-klaar voedsel te voorkomen.', 2),
('G-FS-012', 'nl', 'Waar moet rauw vlees worden bewaard ten opzichte van kant-en-klaar voedsel in de koelkast?', '[{"text":"Op de plank boven kant-en-klaar voedsel","correct":false},{"text":"Op dezelfde plank als kant-en-klaar voedsel","correct":false},{"text":"Onder kant-en-klaar voedsel om druppelen te voorkomen","correct":true},{"text":"Het maakt niet uit zolang beide bedekt zijn","correct":false}]', 'Rauwe producten moeten altijd onder gekookte/kant-en-klare voedingsmiddelen worden bewaard om druppels en besmetting te voorkomen.', 3),
('G-FS-012', 'nl', 'Wat moet u doen bij het overschakelen van het bereiden van rauwe kip naar het bereiden van salade?', '[{"text":"Gewoon uw handen aan uw schort afvegen","correct":false},{"text":"Handen wassen, snijplank verwisselen, werkoppervlak desinfecteren","correct":true},{"text":"Alleen de snijplank verwisselen","correct":false},{"text":"Dezelfde plank blijven gebruiken als u hem omdraait","correct":false}]', 'Volledig hygiëneprotocol is vereist: handen wassen, een andere kleurgecodeerde plank gebruiken en het werkoppervlak desinfecteren tussen rauw en kant-en-klaar voedsel.', 4),
('G-FS-012', 'nl', 'Waarom is het gevaarlijk om hetzelfde mes te gebruiken voor rauw en gekookt voedsel zonder wassen?', '[{"text":"Het mes wordt sneller bot","correct":false},{"text":"Het kan schadelijke bacteriën overdragen van rauw naar gekookt voedsel","correct":true},{"text":"Het beïnvloedt de smaak van het gekookte voedsel","correct":false},{"text":"Het schendt de regels voor keukenorganisatie","correct":false}]', 'Het gebruik van hetzelfde ongewassen mes draagt bacteriën over van rauw voedsel naar kant-en-klare items, waardoor kruisbesmetting ontstaat die kan leiden tot voedselvergiftiging.', 5),
('G-FS-012', 'nl', 'Wat is de juiste procedure voor het desinfecteren van een werkoppervlak na het bereiden van rauwe vis?', '[{"text":"Afvegen met een droge doek","correct":false},{"text":"Alleen spoelen met water","correct":false},{"text":"Reinigen met wasmiddel, spoelen, vervolgens desinfectiemiddel aanbrengen met geschikte contacttijd","correct":true},{"text":"Alleen sprayen met desinfectiemiddel","correct":false}]', 'Goede desinfectie vereist een drietrapsproces: reinigen met wasmiddel om vuil te verwijderen, spoelen, vervolgens voedselveilig desinfectiemiddel aanbrengen voor de vereiste contacttijd.', 6),
('G-FS-012', 'nl', 'Welke praktijk vormt het hoogste kruisbesmettingsrisico in een keuken?', '[{"text":"Aparte tangen gebruiken voor elk voedselitem","correct":false},{"text":"Schoonmaakmiddelen uit de buurt van voedsel bewaren","correct":false},{"text":"Dezelfde doek gebruiken om meerdere oppervlakken af te vegen zonder tussen gebruik door te desinfecteren","correct":true},{"text":"Handen wassen voor het begin van voedselbereiding","correct":false}]', 'Dezelfde doek op meerdere oppervlakken gebruiken zonder te desinfecteren verspreidt bacteriën door de hele keuken, wat een wijdverbreid besmettingsrisico creëert.', 7),
('G-FS-012', 'nl', 'Wat is het doel van het hebben van speciale apparatuur voor allergenenvrije voedselbereiding?', '[{"text":"Om de service te versnellen","correct":false},{"text":"Om kruiscontact met allergenen te voorkomen die ernstige reacties kunnen veroorzaken","correct":true},{"text":"Om de keuken beter te organiseren","correct":false},{"text":"Om de schoonmaaktijd te verminderen","correct":false}]', 'Speciale apparatuur voor allergenenvrije bereiding voorkomt kruiscontact met allergenen, waardoor klanten met ernstige allergieën worden beschermd tegen mogelijk levensbedreigende reacties.', 8);

-- G-FS-012: Cross-Contamination Prevention (German)
INSERT INTO training_test_questions (guide_code, language, question, options, explanation, sort_order) VALUES
('G-FS-012', 'de', 'Was ist der Hauptzweck der Verwendung farbcodierter Schneidebretter?', '[{"text":"Damit die Küche organisiert aussieht","correct":false},{"text":"Um Kreuzkontamination zwischen verschiedenen Lebensmittelarten zu verhindern","correct":true},{"text":"Um zu identifizieren, welcher Koch welches Brett benutzt","correct":false},{"text":"Um ästhetische Standards zu erfüllen","correct":false}]', 'Farbcodierte Schneidebretter verhindern Kreuzkontamination, indem sichergestellt wird, dass rohe und verzehrfertige Lebensmittel auf getrennten Oberflächen zubereitet werden.', 1),
('G-FS-012', 'de', 'Wann sollten Sie Ihre Hände während der Lebensmittelzubereitung waschen?', '[{"text":"Nur zu Beginn Ihrer Schicht","correct":false},{"text":"Nur wenn sie sichtbar schmutzig sind","correct":false},{"text":"Zwischen dem Umgang mit verschiedenen Lebensmittelarten, besonders roh und gekocht","correct":true},{"text":"Einmal pro Stunde","correct":false}]', 'Hände müssen zwischen dem Umgang mit verschiedenen Lebensmittelarten gewaschen werden, um die Übertragung schädlicher Bakterien von rohen auf verzehrfertige Lebensmittel zu verhindern.', 2),
('G-FS-012', 'de', 'Wo sollte rohes Fleisch im Verhältnis zu verzehrfertigen Lebensmitteln im Kühlschrank gelagert werden?', '[{"text":"Auf dem Regal über verzehrfertigen Lebensmitteln","correct":false},{"text":"Auf demselben Regal wie verzehrfertige Lebensmittel","correct":false},{"text":"Unter verzehrfertigen Lebensmitteln, um Tropfen zu verhindern","correct":true},{"text":"Es spielt keine Rolle, solange beide abgedeckt sind","correct":false}]', 'Rohe Produkte müssen immer unter gekochten/verzehrfertigen Lebensmitteln gelagert werden, um Tropfen und Kontamination zu verhindern.', 3),
('G-FS-012', 'de', 'Was sollten Sie tun, wenn Sie von der Zubereitung rohen Huhns zur Zubereitung von Salat wechseln?', '[{"text":"Einfach die Hände an der Schürze abwischen","correct":false},{"text":"Hände waschen, Schneidebrett wechseln, Arbeitsfläche desinfizieren","correct":true},{"text":"Nur das Schneidebrett wechseln","correct":false},{"text":"Dasselbe Brett weiter verwenden, wenn Sie es umdrehen","correct":false}]', 'Vollständiges Hygieneprotokoll ist erforderlich: Hände waschen, ein anderes farbcodiertes Brett verwenden und die Arbeitsfläche zwischen rohen und verzehrfertigen Lebensmitteln desinfizieren.', 4),
('G-FS-012', 'de', 'Warum ist es gefährlich, dasselbe Messer für rohe und gekochte Lebensmittel ohne Waschen zu verwenden?', '[{"text":"Das Messer wird schneller stumpf","correct":false},{"text":"Es kann schädliche Bakterien von rohen auf gekochte Lebensmittel übertragen","correct":true},{"text":"Es beeinflusst den Geschmack des gekochten Essens","correct":false},{"text":"Es verstößt gegen Küchenorganisationsregeln","correct":false}]', 'Die Verwendung desselben ungewaschenen Messers überträgt Bakterien von rohen Lebensmitteln auf verzehrfertige Artikel und verursacht Kreuzkontamination, die zu lebensmittelbedingten Krankheiten führen kann.', 5),
('G-FS-012', 'de', 'Was ist das korrekte Verfahren zur Desinfektion einer Arbeitsfläche nach der Zubereitung rohen Fischs?', '[{"text":"Mit einem trockenen Tuch abwischen","correct":false},{"text":"Nur mit Wasser abspülen","correct":false},{"text":"Mit Reinigungsmittel reinigen, abspülen, dann Desinfektionsmittel mit angemessener Kontaktzeit auftragen","correct":true},{"text":"Nur mit Desinfektionsmittel besprühen","correct":false}]', 'Ordnungsgemäße Desinfektion erfordert einen dreistufigen Prozess: Reinigung mit Reinigungsmittel zur Entfernung von Rückständen, Abspülen, dann Auftragen von lebensmittelsicherem Desinfektionsmittel für die erforderliche Kontaktzeit.', 6),
('G-FS-012', 'de', 'Welche Praxis stellt das höchste Kreuzkontaminationsrisiko in einer Küche dar?', '[{"text":"Separate Zangen für jeden Lebensmittelartikel verwenden","correct":false},{"text":"Reinigungschemikalien von Lebensmitteln fernhalten","correct":false},{"text":"Dasselbe Tuch verwenden, um mehrere Oberflächen abzuwischen, ohne zwischen den Verwendungen zu desinfizieren","correct":true},{"text":"Hände waschen vor Beginn der Lebensmittelzubereitung","correct":false}]', 'Die Verwendung desselben Tuchs auf mehreren Oberflächen ohne Desinfektion verbreitet Bakterien in der gesamten Küche und schafft ein weit verbreitetes Kontaminationsrisiko.', 7),
('G-FS-012', 'de', 'Was ist der Zweck von spezieller Ausrüstung für allergenfreie Lebensmittelzubereitung?', '[{"text":"Um den Service zu beschleunigen","correct":false},{"text":"Um Kreuzkontakt mit Allergenen zu verhindern, die schwere Reaktionen verursachen könnten","correct":true},{"text":"Um die Küche besser zu organisieren","correct":false},{"text":"Um die Reinigungszeit zu reduzieren","correct":false}]', 'Spezielle Ausrüstung für allergenfreie Zubereitung verhindert Kreuzkontakt mit Allergenen und schützt Kunden mit schweren Allergien vor potenziell lebensbedrohlichen Reaktionen.', 8);

-- G-FS-013: Pest Control (English)
INSERT INTO training_test_questions (guide_code, language, question, options, explanation, sort_order) VALUES
('G-FS-013', 'en', 'What is the first line of defense against pests in a food establishment?', '[{"text":"Chemical pesticides","correct":false},{"text":"Physical barriers and good housekeeping","correct":true},{"text":"Electronic pest repellents","correct":false},{"text":"Calling pest control monthly","correct":false}]', 'Prevention through physical barriers (screens, door closers) and maintaining cleanliness is the most effective first defense against pest entry.', 1),
('G-FS-013', 'en', 'Why must a pest control service be provided by an authorized company?', '[{"text":"To comply with legal requirements and ensure proper treatment records","correct":true},{"text":"Because staff are not allowed to handle any pest issues","correct":false},{"text":"Authorized companies work faster","correct":false},{"text":"It is cheaper than doing it yourself","correct":false}]', 'RD 830/2010 requires authorized pest control companies to ensure proper biocide use, documentation, and compliance with safety regulations.', 2),
('G-FS-013', 'en', 'What should you do if you see a rodent in the kitchen during service?', '[{"text":"Try to catch it yourself","correct":false},{"text":"Ignore it and continue working","correct":false},{"text":"Report it immediately to your manager and document the sighting","correct":true},{"text":"Wait until the end of service to mention it","correct":false}]', 'Immediate reporting allows quick action to contain the issue, protect food safety, and initiate pest control measures.', 3),
('G-FS-013', 'en', 'Which of the following is a sign of rodent activity?', '[{"text":"Droppings, gnaw marks, or greasy rub marks along walls","correct":true},{"text":"Clean, organized storage areas","correct":false},{"text":"Bright lighting in all areas","correct":false},{"text":"Properly sealed food containers","correct":false}]', 'Droppings, gnaw marks, and greasy marks are classic indicators of rodent presence and must be reported immediately.', 4),
('G-FS-013', 'en', 'How can you prevent pest entry through delivery doors?', '[{"text":"Keep doors open for ventilation","correct":false},{"text":"Install and maintain door closers, check deliveries promptly","correct":true},{"text":"Stack boxes near the door","correct":false},{"text":"Leave gaps for air circulation","correct":false}]', 'Self-closing doors and minimizing door-open time during deliveries prevent pest entry while maintaining operational efficiency.', 5),
('G-FS-013', 'en', 'What is the correct procedure for storing food to prevent pest attraction?', '[{"text":"Leave food in original cardboard boxes on the floor","correct":false},{"text":"Store in sealed containers, elevated off the floor, in clean organized areas","correct":true},{"text":"Keep food uncovered for easy access","correct":false},{"text":"Store food near waste bins for convenience","correct":false}]', 'Sealed containers elevated off the floor deny pests access to food and breeding areas, while organized storage facilitates inspection.', 6),
('G-FS-013', 'en', 'Why is it important to seal gaps and cracks in walls and around pipes?', '[{"text":"For aesthetic purposes","correct":false},{"text":"To improve insulation","correct":false},{"text":"To prevent pest entry points into the establishment","correct":true},{"text":"To reduce cleaning time","correct":false}]', 'Gaps as small as 6mm can allow rodent entry. Sealing entry points is a critical physical barrier in integrated pest management.', 7),
('G-FS-013', 'en', 'What records must be maintained for pest control activities?', '[{"text":"No records are required","correct":false},{"text":"Only the contract with the pest control company","correct":false},{"text":"Service reports, treatment dates, products used, and any pest sightings","correct":true},{"text":"Only records of pest sightings","correct":false}]', 'Comprehensive pest control records document compliance, identify trends, and provide evidence for health inspections.', 8);

-- G-FS-013: Pest Control (Spanish)
INSERT INTO training_test_questions (guide_code, language, question, options, explanation, sort_order) VALUES
('G-FS-013', 'es', '¿Cuál es la primera línea de defensa contra plagas en un establecimiento de alimentos?', '[{"text":"Pesticidas químicos","correct":false},{"text":"Barreras físicas y buenas prácticas de limpieza","correct":true},{"text":"Repelentes electrónicos de plagas","correct":false},{"text":"Llamar al control de plagas mensualmente","correct":false}]', 'La prevención mediante barreras físicas (mallas, cierrapuertas) y el mantenimiento de la limpieza es la defensa más efectiva contra la entrada de plagas.', 1),
('G-FS-013', 'es', '¿Por qué debe ser proporcionado el servicio de control de plagas por una empresa autorizada?', '[{"text":"Para cumplir con requisitos legales y asegurar registros apropiados de tratamiento","correct":true},{"text":"Porque el personal no puede manejar ningún problema de plagas","correct":false},{"text":"Las empresas autorizadas trabajan más rápido","correct":false},{"text":"Es más barato que hacerlo uno mismo","correct":false}]', 'El RD 830/2010 requiere empresas autorizadas de control de plagas para asegurar el uso apropiado de biocidas, documentación y cumplimiento de regulaciones de seguridad.', 2),
('G-FS-013', 'es', '¿Qué debe hacer si ve un roedor en la cocina durante el servicio?', '[{"text":"Intentar atraparlo usted mismo","correct":false},{"text":"Ignorarlo y continuar trabajando","correct":false},{"text":"Reportarlo inmediatamente a su gerente y documentar el avistamiento","correct":true},{"text":"Esperar hasta el final del servicio para mencionarlo","correct":false}]', 'El reporte inmediato permite acción rápida para contener el problema, proteger la seguridad alimentaria e iniciar medidas de control de plagas.', 3),
('G-FS-013', 'es', '¿Cuál de los siguientes es un signo de actividad de roedores?', '[{"text":"Excrementos, marcas de mordiscos o marcas grasosas a lo largo de las paredes","correct":true},{"text":"Áreas de almacenamiento limpias y organizadas","correct":false},{"text":"Iluminación brillante en todas las áreas","correct":false},{"text":"Contenedores de alimentos correctamente sellados","correct":false}]', 'Los excrementos, marcas de mordiscos y marcas grasosas son indicadores clásicos de presencia de roedores y deben reportarse inmediatamente.', 4),
('G-FS-013', 'es', '¿Cómo puede prevenir la entrada de plagas a través de las puertas de entrega?', '[{"text":"Mantener las puertas abiertas para ventilación","correct":false},{"text":"Instalar y mantener cierrapuertas, revisar entregas rápidamente","correct":true},{"text":"Apilar cajas cerca de la puerta","correct":false},{"text":"Dejar espacios para circulación de aire","correct":false}]', 'Las puertas con cierre automático y minimizar el tiempo de puerta abierta durante entregas previenen la entrada de plagas mientras se mantiene la eficiencia operacional.', 5),
('G-FS-013', 'es', '¿Cuál es el procedimiento correcto para almacenar alimentos y prevenir atracción de plagas?', '[{"text":"Dejar alimentos en cajas de cartón originales en el suelo","correct":false},{"text":"Almacenar en contenedores sellados, elevados del suelo, en áreas limpias organizadas","correct":true},{"text":"Mantener alimentos descubiertos para fácil acceso","correct":false},{"text":"Almacenar alimentos cerca de los contenedores de basura por conveniencia","correct":false}]', 'Contenedores sellados elevados del suelo niegan a las plagas acceso a alimentos y áreas de cría, mientras el almacenamiento organizado facilita la inspección.', 6),
('G-FS-013', 'es', '¿Por qué es importante sellar grietas y espacios en paredes y alrededor de tuberías?', '[{"text":"Por propósitos estéticos","correct":false},{"text":"Para mejorar el aislamiento","correct":false},{"text":"Para prevenir puntos de entrada de plagas al establecimiento","correct":true},{"text":"Para reducir el tiempo de limpieza","correct":false}]', 'Espacios tan pequeños como 6mm pueden permitir la entrada de roedores. Sellar puntos de entrada es una barrera física crítica en el manejo integrado de plagas.', 7),
('G-FS-013', 'es', '¿Qué registros deben mantenerse para las actividades de control de plagas?', '[{"text":"No se requieren registros","correct":false},{"text":"Solo el contrato con la empresa de control de plagas","correct":false},{"text":"Reportes de servicio, fechas de tratamiento, productos usados y cualquier avistamiento de plagas","correct":true},{"text":"Solo registros de avistamientos de plagas","correct":false}]', 'Los registros completos de control de plagas documentan el cumplimiento, identifican tendencias y proporcionan evidencia para inspecciones sanitarias.', 8);

-- G-FS-013: Pest Control (Dutch)
INSERT INTO training_test_questions (guide_code, language, question, options, explanation, sort_order) VALUES
('G-FS-013', 'nl', 'Wat is de eerste verdedigingslinie tegen ongedierte in een voedselvestiging?', '[{"text":"Chemische pesticiden","correct":false},{"text":"Fysieke barrières en goede huishouding","correct":true},{"text":"Elektronische ongediertebestrijders","correct":false},{"text":"Maandelijks ongediertebestrijding bellen","correct":false}]', 'Preventie door fysieke barrières (horren, deursluiters) en het handhaven van netheid is de meest effectieve eerste verdediging tegen binnenkomst van ongedierte.', 1),
('G-FS-013', 'nl', 'Waarom moet een ongediertebestrijdingsdienst worden geleverd door een geautoriseerd bedrijf?', '[{"text":"Om te voldoen aan wettelijke vereisten en goede behandelingsregistraties te waarborgen","correct":true},{"text":"Omdat personeel geen ongedierteprobleem mag aanpakken","correct":false},{"text":"Geautoriseerde bedrijven werken sneller","correct":false},{"text":"Het is goedkoper dan het zelf doen","correct":false}]', 'RD 830/2010 vereist geautoriseerde ongediertebestrijdingsbedrijven om correct gebruik van biociden, documentatie en naleving van veiligheidsvoorschriften te waarborgen.', 2),
('G-FS-013', 'nl', 'Wat moet u doen als u een knaagdier in de keuken ziet tijdens de dienst?', '[{"text":"Proberen het zelf te vangen","correct":false},{"text":"Het negeren en doorgaan met werken","correct":false},{"text":"Het onmiddellijk melden bij uw manager en de waarneming documenteren","correct":true},{"text":"Wachten tot het einde van de dienst om het te vermelden","correct":false}]', 'Onmiddellijke melding maakt snelle actie mogelijk om het probleem in te dammen, voedselveiligheid te beschermen en ongediertebestrijdingsmaatregelen te initiëren.', 3),
('G-FS-013', 'nl', 'Welk van de volgende is een teken van knaagdierenactiviteit?', '[{"text":"Uitwerpselen, knaagsporen of vettige wrijfsporen langs muren","correct":true},{"text":"Schone, georganiseerde opslagruimtes","correct":false},{"text":"Heldere verlichting in alle gebieden","correct":false},{"text":"Goed afgesloten voedselcontainers","correct":false}]', 'Uitwerpselen, knaagsporen en vettige sporen zijn klassieke indicatoren van aanwezigheid van knaagdieren en moeten onmiddellijk worden gemeld.', 4),
('G-FS-013', 'nl', 'Hoe kunt u voorkomen dat ongedierte binnenkomt via leveringsdeuren?', '[{"text":"Deuren open houden voor ventilatie","correct":false},{"text":"Deursluiters installeren en onderhouden, leveringen snel controleren","correct":true},{"text":"Dozen bij de deur stapelen","correct":false},{"text":"Gaten laten voor luchtcirculatie","correct":false}]', 'Zelfsluitende deuren en het minimaliseren van de tijd dat deuren open staan tijdens leveringen voorkomt binnenkomst van ongedierte terwijl operationele efficiëntie behouden blijft.', 5),
('G-FS-013', 'nl', 'Wat is de juiste procedure voor het bewaren van voedsel om aantrekking van ongedierte te voorkomen?', '[{"text":"Voedsel in originele kartonnen dozen op de vloer laten","correct":false},{"text":"Bewaren in afgesloten containers, verhoogd van de vloer, in schone georganiseerde gebieden","correct":true},{"text":"Voedsel onbedekt houden voor gemakkelijke toegang","correct":false},{"text":"Voedsel bij afvalbakken bewaren voor gemak","correct":false}]', 'Afgesloten containers verhoogd van de vloer ontzeggen ongedierte toegang tot voedsel en broedgebieden, terwijl georganiseerde opslag inspectie vergemakkelijkt.', 6),
('G-FS-013', 'nl', 'Waarom is het belangrijk om gaten en scheuren in muren en rond leidingen te dichten?', '[{"text":"Voor esthetische doeleinden","correct":false},{"text":"Om isolatie te verbeteren","correct":false},{"text":"Om toegangspunten voor ongedierte naar de vestiging te voorkomen","correct":true},{"text":"Om schoonmaaktijd te verminderen","correct":false}]', 'Gaten zo klein als 6mm kunnen knaagdieren binnenlaten. Het afdichten van toegangspunten is een cruciale fysieke barrière in geïntegreerd ongediertebestrijding.', 7),
('G-FS-013', 'nl', 'Welke registraties moeten worden bijgehouden voor ongediertebestrijdingsactiviteiten?', '[{"text":"Geen registraties zijn vereist","correct":false},{"text":"Alleen het contract met het ongediertebestrijdingsbedrijf","correct":false},{"text":"Servicerapporten, behandeldata, gebruikte producten en eventuele waarnemingen van ongedierte","correct":true},{"text":"Alleen registraties van waarnemingen van ongedierte","correct":false}]', 'Uitgebreide ongediertebestrijdingsregistraties documenteren naleving, identificeren trends en bieden bewijs voor gezondheidsinspecties.', 8);

-- G-FS-013: Pest Control (German)
INSERT INTO training_test_questions (guide_code, language, question, options, explanation, sort_order) VALUES
('G-FS-013', 'de', 'Was ist die erste Verteidigungslinie gegen Schädlinge in einem Lebensmittelbetrieb?', '[{"text":"Chemische Pestizide","correct":false},{"text":"Physische Barrieren und gute Haushaltsführung","correct":true},{"text":"Elektronische Schädlingsbekämpfer","correct":false},{"text":"Monatlich Schädlingsbekämpfung rufen","correct":false}]', 'Prävention durch physische Barrieren (Fliegengitter, Türschließer) und Aufrechterhaltung der Sauberkeit ist die effektivste erste Verteidigung gegen Schädlingseintritt.', 1),
('G-FS-013', 'de', 'Warum muss ein Schädlingsbekämpfungsdienst von einem autorisierten Unternehmen bereitgestellt werden?', '[{"text":"Um gesetzliche Anforderungen zu erfüllen und ordnungsgemäße Behandlungsaufzeichnungen sicherzustellen","correct":true},{"text":"Weil Personal keine Schädlingsprobleme behandeln darf","correct":false},{"text":"Autorisierte Unternehmen arbeiten schneller","correct":false},{"text":"Es ist billiger als es selbst zu tun","correct":false}]', 'RD 830/2010 erfordert autorisierte Schädlingsbekämpfungsunternehmen, um ordnungsgemäße Biozidverwendung, Dokumentation und Einhaltung von Sicherheitsvorschriften sicherzustellen.', 2),
('G-FS-013', 'de', 'Was sollten Sie tun, wenn Sie während des Service ein Nagetier in der Küche sehen?', '[{"text":"Versuchen, es selbst zu fangen","correct":false},{"text":"Es ignorieren und weiterarbeiten","correct":false},{"text":"Es sofort Ihrem Manager melden und die Sichtung dokumentieren","correct":true},{"text":"Bis zum Ende des Service warten, um es zu erwähnen","correct":false}]', 'Sofortige Meldung ermöglicht schnelle Maßnahmen zur Eindämmung des Problems, zum Schutz der Lebensmittelsicherheit und zur Einleitung von Schädlingsbekämpfungsmaßnahmen.', 3),
('G-FS-013', 'de', 'Welches der folgenden ist ein Zeichen von Nagetieraktivität?', '[{"text":"Kot, Nagespuren oder fettige Reibspuren entlang der Wände","correct":true},{"text":"Saubere, organisierte Lagerbereiche","correct":false},{"text":"Helle Beleuchtung in allen Bereichen","correct":false},{"text":"Ordnungsgemäß versiegelte Lebensmittelbehälter","correct":false}]', 'Kot, Nagespuren und fettige Spuren sind klassische Indikatoren für Nagetierpräsenz und müssen sofort gemeldet werden.', 4),
('G-FS-013', 'de', 'Wie können Sie den Schädlingseintritt durch Liefertüren verhindern?', '[{"text":"Türen für Belüftung offen halten","correct":false},{"text":"Türschließer installieren und warten, Lieferungen prompt überprüfen","correct":true},{"text":"Kisten in der Nähe der Tür stapeln","correct":false},{"text":"Lücken für Luftzirkulation lassen","correct":false}]', 'Selbstschließende Türen und Minimierung der offenen Türzeit während Lieferungen verhindern Schädlingseintritt bei gleichzeitiger Aufrechterhaltung der Betriebseffizienz.', 5),
('G-FS-013', 'de', 'Was ist das korrekte Verfahren zur Lagerung von Lebensmitteln, um Schädlingsanziehung zu verhindern?', '[{"text":"Lebensmittel in original Kartons auf dem Boden lassen","correct":false},{"text":"In versiegelten Behältern lagern, vom Boden erhöht, in sauberen organisierten Bereichen","correct":true},{"text":"Lebensmittel unbedeckt für einfachen Zugang halten","correct":false},{"text":"Lebensmittel in der Nähe von Abfallbehältern für Bequemlichkeit lagern","correct":false}]', 'Versiegelte Behälter, die vom Boden erhöht sind, verwehren Schädlingen Zugang zu Nahrung und Brutgebieten, während organisierte Lagerung die Inspektion erleichtert.', 6),
('G-FS-013', 'de', 'Warum ist es wichtig, Lücken und Risse in Wänden und um Rohre herum zu versiegeln?', '[{"text":"Für ästhetische Zwecke","correct":false},{"text":"Um die Isolierung zu verbessern","correct":false},{"text":"Um Schädlingseingangspunkte in die Einrichtung zu verhindern","correct":true},{"text":"Um die Reinigungszeit zu reduzieren","correct":false}]', 'Lücken von nur 6mm können Nagetieren Eintritt ermöglichen. Das Versiegeln von Eingangspunkten ist eine kritische physische Barriere im integrierten Schädlingsmanagement.', 7),
('G-FS-013', 'de', 'Welche Aufzeichnungen müssen für Schädlingsbekämpfungsaktivitäten geführt werden?', '[{"text":"Keine Aufzeichnungen sind erforderlich","correct":false},{"text":"Nur der Vertrag mit dem Schädlingsbekämpfungsunternehmen","correct":false},{"text":"Serviceberichte, Behandlungsdaten, verwendete Produkte und alle Schädlingssichtungen","correct":true},{"text":"Nur Aufzeichnungen von Schädlingssichtungen","correct":false}]', 'Umfassende Schädlingsbekämpfungsaufzeichnungen dokumentieren Compliance, identifizieren Trends und liefern Beweise für Gesundheitsinspektionen.', 8);

