-- Training test questions for PRL guides (G-PRL-014 through G-PRL-018)
-- 5 guides × 8 questions × 4 languages = 160 rows

-- G-PRL-014: Gas Safety (English)
INSERT INTO training_test_questions (guide_code, language, question, options, explanation, sort_order) VALUES
('G-PRL-014', 'en', 'What is the most common sign of a gas leak in a kitchen?', '[{"text":"Loud banging noise","correct":false},{"text":"Distinctive odor (mercaptan smell) and hissing sound","correct":true},{"text":"Flickering lights","correct":false},{"text":"Steam rising from equipment","correct":false}]', 'Natural gas is odorless, but mercaptan is added as a safety measure giving it a distinctive sulfur or rotten egg smell. A hissing sound may also indicate escaping gas.', 1),
('G-PRL-014', 'en', 'According to RD 919/2006, what must be done immediately if a gas leak is suspected?', '[{"text":"Call the gas company and continue working","correct":false},{"text":"Evacuate, shut off gas supply, ventilate, and call emergency services","correct":true},{"text":"Light a match to locate the leak","correct":false},{"text":"Continue working but open windows","correct":false}]', 'Gas leaks pose explosion and asphyxiation risks. Immediate evacuation, gas shut-off, ventilation without creating sparks, and emergency notification are critical.', 2),
('G-PRL-014', 'en', 'Why should you NEVER use an open flame to check for gas leaks?', '[{"text":"It wastes fuel","correct":false},{"text":"It can cause an explosion or fire","correct":true},{"text":"It is not accurate","correct":false},{"text":"It damages equipment","correct":false}]', 'Natural gas is highly flammable. Any ignition source near a gas leak, including matches or lighters, can cause a catastrophic explosion.', 3),
('G-PRL-014', 'en', 'Where should every kitchen staff member know the location of the gas shut-off valve?', '[{"text":"Only managers need to know","correct":false},{"text":"All kitchen staff must know its exact location","correct":true},{"text":"Only certified technicians need access","correct":false},{"text":"It is not necessary for staff to know","correct":false}]', 'In a gas emergency, rapid shut-off is critical. All kitchen staff must be able to locate and operate the gas shut-off valve immediately.', 4),
('G-PRL-014', 'en', 'How often must gas installations be inspected by authorized technicians?', '[{"text":"Only when problems occur","correct":false},{"text":"Regularly according to manufacturer specifications and regulations","correct":true},{"text":"Every 10 years","correct":false},{"text":"Once when installed, never again","correct":false}]', 'RD 919/2006 requires regular inspection and maintenance of gas installations by certified technicians to ensure safe operation and compliance.', 5),
('G-PRL-014', 'en', 'Before relighting gas equipment after it has been shut off, what must you do?', '[{"text":"Light it immediately","correct":false},{"text":"Ventilate the area thoroughly to clear any accumulated gas","correct":true},{"text":"Check if the gas bill is paid","correct":false},{"text":"Call the fire department","correct":false}]', 'Gas can accumulate in enclosed spaces. Proper ventilation before relighting prevents ignition of accumulated gas which could cause an explosion.', 6),
('G-PRL-014', 'en', 'What maintenance practice helps prevent gas-related hazards?', '[{"text":"Painting equipment regularly","correct":false},{"text":"Following manufacturer specifications for equipment maintenance","correct":true},{"text":"Using equipment continuously without breaks","correct":false},{"text":"Keeping maintenance records secret","correct":false}]', 'Proper maintenance according to manufacturer specifications ensures safe operation, identifies potential problems early, and maintains equipment in compliance with safety standards.', 7),
('G-PRL-014', 'en', 'What should you do if you smell gas but cannot locate the source?', '[{"text":"Ignore it if it is faint","correct":false},{"text":"Evacuate immediately, shut off main gas supply, and call emergency services","correct":true},{"text":"Use air freshener to mask the smell","correct":false},{"text":"Wait to see if it goes away","correct":false}]', 'If gas is detected but the source is unknown, the risk of explosion is high. Immediate evacuation and professional response are required.', 8),

-- G-PRL-014: Gas Safety (Spanish)
('G-PRL-014', 'es', '¿Cuál es la señal más común de una fuga de gas en una cocina?', '[{"text":"Ruido fuerte de golpes","correct":false},{"text":"Olor distintivo (olor a mercaptano) y sonido de silbido","correct":true},{"text":"Luces parpadeantes","correct":false},{"text":"Vapor saliendo del equipo","correct":false}]', 'El gas natural es inodoro, pero se añade mercaptano como medida de seguridad dándole un olor distintivo a azufre o huevo podrido. Un sonido de silbido también puede indicar escape de gas.', 1),
('G-PRL-014', 'es', 'Según el RD 919/2006, ¿qué debe hacerse inmediatamente si se sospecha una fuga de gas?', '[{"text":"Llamar a la compañía de gas y continuar trabajando","correct":false},{"text":"Evacuar, cerrar el suministro de gas, ventilar y llamar a servicios de emergencia","correct":true},{"text":"Encender una cerilla para localizar la fuga","correct":false},{"text":"Continuar trabajando pero abrir ventanas","correct":false}]', 'Las fugas de gas presentan riesgos de explosión y asfixia. La evacuación inmediata, el cierre del gas, la ventilación sin crear chispas y la notificación de emergencia son críticas.', 2),
('G-PRL-014', 'es', '¿Por qué NUNCA debe usarse una llama abierta para comprobar fugas de gas?', '[{"text":"Desperdicia combustible","correct":false},{"text":"Puede causar una explosión o incendio","correct":true},{"text":"No es preciso","correct":false},{"text":"Daña el equipo","correct":false}]', 'El gas natural es altamente inflamable. Cualquier fuente de ignición cerca de una fuga de gas, incluyendo cerillas o encendedores, puede causar una explosión catastrófica.', 3),
('G-PRL-014', 'es', '¿Dónde debe conocer cada miembro del personal de cocina la ubicación de la válvula de cierre de gas?', '[{"text":"Solo los gerentes necesitan saberlo","correct":false},{"text":"Todo el personal de cocina debe conocer su ubicación exacta","correct":true},{"text":"Solo los técnicos certificados necesitan acceso","correct":false},{"text":"No es necesario que el personal lo sepa","correct":false}]', 'En una emergencia de gas, el cierre rápido es crítico. Todo el personal de cocina debe poder localizar y operar la válvula de cierre de gas inmediatamente.', 4),
('G-PRL-014', 'es', '¿Con qué frecuencia deben inspeccionarse las instalaciones de gas por técnicos autorizados?', '[{"text":"Solo cuando ocurren problemas","correct":false},{"text":"Regularmente según especificaciones del fabricante y regulaciones","correct":true},{"text":"Cada 10 años","correct":false},{"text":"Una vez al instalar, nunca más","correct":false}]', 'El RD 919/2006 requiere inspección y mantenimiento regular de instalaciones de gas por técnicos certificados para asegurar operación segura y cumplimiento.', 5),
('G-PRL-014', 'es', 'Antes de reencender equipo de gas después de haberlo apagado, ¿qué debe hacer?', '[{"text":"Encenderlo inmediatamente","correct":false},{"text":"Ventilar el área completamente para eliminar cualquier gas acumulado","correct":true},{"text":"Comprobar si la factura de gas está pagada","correct":false},{"text":"Llamar al departamento de bomberos","correct":false}]', 'El gas puede acumularse en espacios cerrados. La ventilación adecuada antes de reencender previene la ignición de gas acumulado que podría causar una explosión.', 6),
('G-PRL-014', 'es', '¿Qué práctica de mantenimiento ayuda a prevenir peligros relacionados con el gas?', '[{"text":"Pintar el equipo regularmente","correct":false},{"text":"Seguir las especificaciones del fabricante para el mantenimiento del equipo","correct":true},{"text":"Usar el equipo continuamente sin descansos","correct":false},{"text":"Mantener los registros de mantenimiento en secreto","correct":false}]', 'El mantenimiento adecuado según las especificaciones del fabricante asegura operación segura, identifica problemas potenciales temprano y mantiene el equipo en cumplimiento con estándares de seguridad.', 7),
('G-PRL-014', 'es', '¿Qué debe hacer si huele gas pero no puede localizar la fuente?', '[{"text":"Ignorarlo si es tenue","correct":false},{"text":"Evacuar inmediatamente, cerrar el suministro principal de gas y llamar a servicios de emergencia","correct":true},{"text":"Usar ambientador para enmascarar el olor","correct":false},{"text":"Esperar a ver si desaparece","correct":false}]', 'Si se detecta gas pero la fuente es desconocida, el riesgo de explosión es alto. Se requiere evacuación inmediata y respuesta profesional.', 8),

-- G-PRL-014: Gas Safety (Dutch)
('G-PRL-014', 'nl', 'Wat is het meest voorkomende teken van een gaslek in een keuken?', '[{"text":"Luid bonzend geluid","correct":false},{"text":"Kenmerkende geur (mercaptaangeur) en sissend geluid","correct":true},{"text":"Knipperende lichten","correct":false},{"text":"Stoom die opstijgt van apparatuur","correct":false}]', 'Aardgas is geurloos, maar mercaptaan wordt toegevoegd als veiligheidsmaatregel die het een kenmerkende zwavel- of bedorven eierengeur geeft. Een sissend geluid kan ook ontsnappend gas aangeven.', 1),
('G-PRL-014', 'nl', 'Volgens RD 919/2006, wat moet onmiddellijk worden gedaan als een gaslek wordt vermoed?', '[{"text":"Bel het gasbedrijf en blijf doorwerken","correct":false},{"text":"Evacueer, sluit gastoevoer af, ventileer en bel hulpdiensten","correct":true},{"text":"Steek een lucifer aan om het lek te lokaliseren","correct":false},{"text":"Blijf doorwerken maar open ramen","correct":false}]', 'Gaslekken vormen explosie- en verstikkingsrisico\'s. Onmiddellijke evacuatie, gassluiting, ventilatie zonder vonken te creëren en noodmelding zijn kritiek.', 2),
('G-PRL-014', 'nl', 'Waarom mag je NOOIT een open vlam gebruiken om gaslekken te controleren?', '[{"text":"Het verspilt brandstof","correct":false},{"text":"Het kan een explosie of brand veroorzaken","correct":true},{"text":"Het is niet nauwkeurig","correct":false},{"text":"Het beschadigt apparatuur","correct":false}]', 'Aardgas is zeer ontvlambaar. Elke ontstekingsbron bij een gaslek, inclusief lucifers of aanstekers, kan een catastrofale explosie veroorzaken.', 3),
('G-PRL-014', 'nl', 'Waar moet elk keukenpersoneelslid de locatie van de gasafsluitklep kennen?', '[{"text":"Alleen managers hoeven het te weten","correct":false},{"text":"Al het keukenpersoneel moet de exacte locatie kennen","correct":true},{"text":"Alleen gecertificeerde technici hebben toegang nodig","correct":false},{"text":"Het is niet nodig dat personeel het weet","correct":false}]', 'Bij een gasnoodsituatie is snelle afsluiting kritiek. Al het keukenpersoneel moet de gasafsluitklep onmiddellijk kunnen lokaliseren en bedienen.', 4),
('G-PRL-014', 'nl', 'Hoe vaak moeten gasinstallaties worden geïnspecteerd door geautoriseerde technici?', '[{"text":"Alleen wanneer problemen optreden","correct":false},{"text":"Regelmatig volgens fabrieksspecificaties en regelgeving","correct":true},{"text":"Elke 10 jaar","correct":false},{"text":"Eenmaal bij installatie, nooit meer","correct":false}]', 'RD 919/2006 vereist regelmatige inspectie en onderhoud van gasinstallaties door gecertificeerde technici om veilige werking en naleving te waarborgen.', 5),
('G-PRL-014', 'nl', 'Voordat u gasapparatuur opnieuw aansteekt nadat deze is uitgeschakeld, wat moet u doen?', '[{"text":"Steek het onmiddellijk aan","correct":false},{"text":"Ventileer het gebied grondig om geaccumuleerd gas te verwijderen","correct":true},{"text":"Controleer of de gasrekening is betaald","correct":false},{"text":"Bel de brandweer","correct":false}]', 'Gas kan zich ophopen in afgesloten ruimtes. Goede ventilatie voor herontsteking voorkomt ontsteking van opgehoopt gas dat een explosie zou kunnen veroorzaken.', 6),
('G-PRL-014', 'nl', 'Welke onderhoudspraktijk helpt gasgerelateerde gevaren te voorkomen?', '[{"text":"Apparatuur regelmatig schilderen","correct":false},{"text":"Fabrieksspecificaties volgen voor apparatuuronderhoud","correct":true},{"text":"Apparatuur continu gebruiken zonder pauzes","correct":false},{"text":"Onderhoudsrecords geheim houden","correct":false}]', 'Correct onderhoud volgens fabrieksspecificaties zorgt voor veilige werking, identificeert potentiële problemen vroeg en houdt apparatuur in overeenstemming met veiligheidsnormen.', 7),
('G-PRL-014', 'nl', 'Wat moet u doen als u gas ruikt maar de bron niet kunt lokaliseren?', '[{"text":"Negeer het als het vaag is","correct":false},{"text":"Evacueer onmiddellijk, sluit hoofdgastoevoer af en bel hulpdiensten","correct":true},{"text":"Gebruik luchtverfrisser om de geur te maskeren","correct":false},{"text":"Wacht om te zien of het verdwijnt","correct":false}]', 'Als gas wordt gedetecteerd maar de bron is onbekend, is het explosierisico hoog. Onmiddellijke evacuatie en professionele respons zijn vereist.', 8),

-- G-PRL-014: Gas Safety (German)
('G-PRL-014', 'de', 'Was ist das häufigste Anzeichen eines Gaslecks in einer Küche?', '[{"text":"Lautes Schlaggeräusch","correct":false},{"text":"Charakteristischer Geruch (Mercaptangeruch) und zischendes Geräusch","correct":true},{"text":"Flackernde Lichter","correct":false},{"text":"Dampf steigt von Geräten auf","correct":false}]', 'Erdgas ist geruchlos, aber Mercaptan wird als Sicherheitsmaßnahme hinzugefügt, was ihm einen charakteristischen Schwefel- oder faulen Eiergeruch verleiht. Ein zischendes Geräusch kann auch austretendes Gas anzeigen.', 1),
('G-PRL-014', 'de', 'Gemäß RD 919/2006, was muss sofort getan werden, wenn ein Gasleck vermutet wird?', '[{"text":"Gasunternehmen anrufen und weiterarbeiten","correct":false},{"text":"Evakuieren, Gaszufuhr abschalten, lüften und Notdienste rufen","correct":true},{"text":"Streichholz anzünden, um das Leck zu lokalisieren","correct":false},{"text":"Weiterarbeiten, aber Fenster öffnen","correct":false}]', 'Gaslecks stellen Explosions- und Erstickungsrisiken dar. Sofortige Evakuierung, Gasabschaltung, Belüftung ohne Funken zu erzeugen und Notfallbenachrichtigung sind kritisch.', 2),
('G-PRL-014', 'de', 'Warum sollten Sie NIEMALS eine offene Flamme verwenden, um Gaslecks zu prüfen?', '[{"text":"Es verschwendet Kraftstoff","correct":false},{"text":"Es kann eine Explosion oder Brand verursachen","correct":true},{"text":"Es ist nicht genau","correct":false},{"text":"Es beschädigt Geräte","correct":false}]', 'Erdgas ist hochentzündlich. Jede Zündquelle in der Nähe eines Gaslecks, einschließlich Streichhölzer oder Feuerzeuge, kann eine katastrophale Explosion verursachen.', 3),
('G-PRL-014', 'de', 'Wo sollte jedes Küchenpersonal den Standort des Gasabsperrventils kennen?', '[{"text":"Nur Manager müssen es wissen","correct":false},{"text":"Alles Küchenpersonal muss den genauen Standort kennen","correct":true},{"text":"Nur zertifizierte Techniker benötigen Zugang","correct":false},{"text":"Es ist nicht notwendig, dass Personal es weiß","correct":false}]', 'In einem Gasnotfall ist schnelle Abschaltung kritisch. Alles Küchenpersonal muss das Gasabsperrventil sofort lokalisieren und bedienen können.', 4),
('G-PRL-014', 'de', 'Wie oft müssen Gasinstallationen von autorisierten Technikern inspiziert werden?', '[{"text":"Nur wenn Probleme auftreten","correct":false},{"text":"Regelmäßig gemäß Herstellerspezifikationen und Vorschriften","correct":true},{"text":"Alle 10 Jahre","correct":false},{"text":"Einmal bei Installation, nie wieder","correct":false}]', 'RD 919/2006 verlangt regelmäßige Inspektion und Wartung von Gasinstallationen durch zertifizierte Techniker, um sicheren Betrieb und Konformität zu gewährleisten.', 5),
('G-PRL-014', 'de', 'Bevor Sie Gasgeräte nach dem Ausschalten wieder anzünden, was müssen Sie tun?', '[{"text":"Sofort anzünden","correct":false},{"text":"Bereich gründlich lüften, um angesammeltes Gas zu entfernen","correct":true},{"text":"Prüfen, ob Gasrechnung bezahlt ist","correct":false},{"text":"Feuerwehr anrufen","correct":false}]', 'Gas kann sich in geschlossenen Räumen ansammeln. Ordnungsgemäße Belüftung vor dem Wiederanzünden verhindert Entzündung von angesammeltem Gas, das eine Explosion verursachen könnte.', 6),
('G-PRL-014', 'de', 'Welche Wartungspraxis hilft, gasbezogene Gefahren zu verhindern?', '[{"text":"Geräte regelmäßig streichen","correct":false},{"text":"Herstellerspezifikationen für Gerätewartung befolgen","correct":true},{"text":"Geräte kontinuierlich ohne Pausen verwenden","correct":false},{"text":"Wartungsaufzeichnungen geheim halten","correct":false}]', 'Ordnungsgemäße Wartung gemäß Herstellerspezifikationen gewährleistet sicheren Betrieb, identifiziert potenzielle Probleme früh und hält Geräte in Übereinstimmung mit Sicherheitsstandards.', 7),
('G-PRL-014', 'de', 'Was sollten Sie tun, wenn Sie Gas riechen, aber die Quelle nicht lokalisieren können?', '[{"text":"Ignorieren, wenn es schwach ist","correct":false},{"text":"Sofort evakuieren, Hauptgaszufuhr abschalten und Notdienste rufen","correct":true},{"text":"Lufterfrischer verwenden, um Geruch zu maskieren","correct":false},{"text":"Warten, ob es verschwindet","correct":false}]', 'Wenn Gas erkannt wird, aber die Quelle unbekannt ist, ist das Explosionsrisiko hoch. Sofortige Evakuierung und professionelle Reaktion sind erforderlich.', 8),

-- G-PRL-015: Pregnancy & Lactation Protection (English)
INSERT INTO training_test_questions (guide_code, language, question, options, explanation, sort_order) VALUES
('G-PRL-015', 'en', 'According to Ley 31/1995, what must employers do when a worker becomes pregnant?', '[{"text":"Terminate the contract","correct":false},{"text":"Conduct a specific risk assessment for the pregnant worker","correct":true},{"text":"Reduce salary","correct":false},{"text":"Nothing, standard rules apply","correct":false}]', 'Employers must conduct a specific risk assessment considering the worker\'s role and adapt working conditions to eliminate or minimize risks to pregnancy.', 1),
('G-PRL-015', 'en', 'Which of the following tasks should pregnant hospitality workers be exempt from?', '[{"text":"Customer service","correct":false},{"text":"Heavy lifting, prolonged standing, and exposure to hazardous chemicals","correct":true},{"text":"Light food preparation","correct":false},{"text":"Administrative tasks","correct":false}]', 'Pregnant workers must be protected from heavy manual handling, prolonged standing without breaks, chemical exposure, and other tasks that pose risks to pregnancy.', 2),
('G-PRL-015', 'en', 'Are pregnant workers entitled to exemption from night shifts?', '[{"text":"No, all workers must work night shifts","correct":false},{"text":"Yes, if medically advised or if risks cannot be eliminated","correct":true},{"text":"Only in the final month of pregnancy","correct":false},{"text":"Only if they specifically request it","correct":false}]', 'RD 298/2009 provides that pregnant workers should be exempted from night work if medically advised or if workplace risks during night hours cannot be adequately controlled.', 3),
('G-PRL-015', 'en', 'What is the legal entitlement for breastfeeding breaks for mothers returning to work?', '[{"text":"30 minutes per day","correct":false},{"text":"1 hour daily, which can be divided into two half-hour periods","correct":true},{"text":"No specific entitlement exists","correct":false},{"text":"15 minutes per shift","correct":false}]', 'Breastfeeding mothers are entitled to 1 hour of absence from work per day (paid), which can be divided into two half-hour periods or accumulated as preferred.', 4),
('G-PRL-015', 'en', 'If workplace risks to a pregnant worker cannot be eliminated through adaptation, what must the employer offer?', '[{"text":"Unpaid leave","correct":false},{"text":"Temporary reassignment to a different, risk-free role","correct":true},{"text":"Immediate termination","correct":false},{"text":"Remote work only","correct":false}]', 'If risks cannot be eliminated, the employer must offer temporary reassignment to a suitable alternative role with no reduction in salary or benefits.', 5),
('G-PRL-015', 'en', 'Can a pregnant worker be dismissed due to her pregnancy?', '[{"text":"Yes, if she cannot perform her role","correct":false},{"text":"No, dismissal due to pregnancy is illegal and discriminatory","correct":true},{"text":"Yes, with proper compensation","correct":false},{"text":"Only during probation period","correct":false}]', 'Dismissal due to pregnancy or related absence is illegal under Spanish law and constitutes discrimination. Pregnant workers have strong employment protection.', 6),
('G-PRL-015', 'en', 'What type of chemicals should pregnant workers avoid exposure to?', '[{"text":"Only radioactive materials","correct":false},{"text":"Cleaning chemicals, degreasers, and any hazardous substances","correct":true},{"text":"Food preservatives only","correct":false},{"text":"No restrictions apply","correct":false}]', 'Pregnant workers should avoid exposure to cleaning chemicals, degreasers, solvents, and any substances classified as hazardous, as these can affect fetal development.', 7),
('G-PRL-015', 'en', 'What support should employers provide to facilitate breastfeeding for returning mothers?', '[{"text":"No support is legally required","correct":false},{"text":"Allow breastfeeding breaks and provide a private, hygienic space if possible","correct":true},{"text":"Only allow breaks outside working hours","correct":false},{"text":"Require mothers to work from home","correct":false}]', 'Employers should facilitate breastfeeding by allowing the legal breaks and, where possible, providing a private, clean space for breastfeeding or milk expression.', 8),

-- G-PRL-015: Pregnancy & Lactation Protection (Spanish)
('G-PRL-015', 'es', 'Según la Ley 31/1995, ¿qué deben hacer los empleadores cuando una trabajadora queda embarazada?', '[{"text":"Rescindir el contrato","correct":false},{"text":"Realizar una evaluación de riesgos específica para la trabajadora embarazada","correct":true},{"text":"Reducir el salario","correct":false},{"text":"Nada, aplican reglas estándar","correct":false}]', 'Los empleadores deben realizar una evaluación de riesgos específica considerando el rol de la trabajadora y adaptar las condiciones laborales para eliminar o minimizar riesgos para el embarazo.', 1),
('G-PRL-015', 'es', '¿De cuál de las siguientes tareas deben estar exentas las trabajadoras embarazadas en hostelería?', '[{"text":"Servicio al cliente","correct":false},{"text":"Levantamiento de cargas pesadas, bipedestación prolongada y exposición a químicos peligrosos","correct":true},{"text":"Preparación ligera de alimentos","correct":false},{"text":"Tareas administrativas","correct":false}]', 'Las trabajadoras embarazadas deben estar protegidas de la manipulación manual de cargas pesadas, bipedestación prolongada sin descansos, exposición química y otras tareas que representen riesgos para el embarazo.', 2),
('G-PRL-015', 'es', '¿Tienen derecho las trabajadoras embarazadas a exención de turnos nocturnos?', '[{"text":"No, todas las trabajadoras deben trabajar turnos nocturnos","correct":false},{"text":"Sí, si está médicamente aconsejado o si los riesgos no pueden eliminarse","correct":true},{"text":"Solo en el último mes de embarazo","correct":false},{"text":"Solo si lo solicitan específicamente","correct":false}]', 'El RD 298/2009 establece que las trabajadoras embarazadas deben estar exentas del trabajo nocturno si está médicamente aconsejado o si los riesgos laborales durante horas nocturnas no pueden controlarse adecuadamente.', 3),
('G-PRL-015', 'es', '¿Cuál es el derecho legal de descansos para lactancia para madres que regresan al trabajo?', '[{"text":"30 minutos por día","correct":false},{"text":"1 hora diaria, que puede dividirse en dos períodos de media hora","correct":true},{"text":"No existe derecho específico","correct":false},{"text":"15 minutos por turno","correct":false}]', 'Las madres lactantes tienen derecho a 1 hora de ausencia del trabajo por día (pagada), que puede dividirse en dos períodos de media hora o acumularse según prefieran.', 4),
('G-PRL-015', 'es', 'Si los riesgos laborales para una trabajadora embarazada no pueden eliminarse mediante adaptación, ¿qué debe ofrecer el empleador?', '[{"text":"Licencia sin sueldo","correct":false},{"text":"Reasignación temporal a un rol diferente sin riesgos","correct":true},{"text":"Terminación inmediata","correct":false},{"text":"Solo trabajo remoto","correct":false}]', 'Si los riesgos no pueden eliminarse, el empleador debe ofrecer reasignación temporal a un rol alternativo adecuado sin reducción de salario o beneficios.', 5),
('G-PRL-015', 'es', '¿Puede despedirse a una trabajadora embarazada debido a su embarazo?', '[{"text":"Sí, si no puede realizar su rol","correct":false},{"text":"No, el despido por embarazo es ilegal y discriminatorio","correct":true},{"text":"Sí, con compensación adecuada","correct":false},{"text":"Solo durante período de prueba","correct":false}]', 'El despido debido al embarazo o ausencia relacionada es ilegal bajo la ley española y constituye discriminación. Las trabajadoras embarazadas tienen fuerte protección laboral.', 6),
('G-PRL-015', 'es', '¿Qué tipo de químicos deben evitar la exposición las trabajadoras embarazadas?', '[{"text":"Solo materiales radiactivos","correct":false},{"text":"Productos de limpieza, desengrasantes y cualquier sustancia peligrosa","correct":true},{"text":"Solo conservantes alimentarios","correct":false},{"text":"No aplican restricciones","correct":false}]', 'Las trabajadoras embarazadas deben evitar la exposición a productos de limpieza, desengrasantes, disolventes y cualquier sustancia clasificada como peligrosa, ya que pueden afectar el desarrollo fetal.', 7),
('G-PRL-015', 'es', '¿Qué apoyo deben proporcionar los empleadores para facilitar la lactancia a madres que regresan?', '[{"text":"No se requiere apoyo legalmente","correct":false},{"text":"Permitir descansos para lactancia y proporcionar un espacio privado e higiénico si es posible","correct":true},{"text":"Solo permitir descansos fuera del horario laboral","correct":false},{"text":"Requerir que las madres trabajen desde casa","correct":false}]', 'Los empleadores deben facilitar la lactancia permitiendo los descansos legales y, cuando sea posible, proporcionando un espacio privado y limpio para amamantar o extraer leche.', 8),

-- G-PRL-015: Pregnancy & Lactation Protection (Dutch)
('G-PRL-015', 'nl', 'Volgens Ley 31/1995, wat moeten werkgevers doen wanneer een werknemer zwanger wordt?', '[{"text":"Contract beëindigen","correct":false},{"text":"Specifieke risicobeoordeling uitvoeren voor de zwangere werknemer","correct":true},{"text":"Salaris verlagen","correct":false},{"text":"Niets, standaardregels zijn van toepassing","correct":false}]', 'Werkgevers moeten een specifieke risicobeoordeling uitvoeren met inachtneming van de rol van de werknemer en arbeidsomstandigheden aanpassen om risico\'s voor zwangerschap te elimineren of minimaliseren.', 1),
('G-PRL-015', 'nl', 'Van welke van de volgende taken moeten zwangere horecamedewerkers worden vrijgesteld?', '[{"text":"Klantenservice","correct":false},{"text":"Zwaar tillen, langdurig staan en blootstelling aan gevaarlijke chemicaliën","correct":true},{"text":"Lichte voedselbereiding","correct":false},{"text":"Administratieve taken","correct":false}]', 'Zwangere werknemers moeten worden beschermd tegen zware handmatige handling, langdurig staan zonder pauzes, blootstelling aan chemicaliën en andere taken die risico\'s voor zwangerschap vormen.', 2),
('G-PRL-015', 'nl', 'Hebben zwangere werknemers recht op vrijstelling van nachtdiensten?', '[{"text":"Nee, alle werknemers moeten nachtdiensten werken","correct":false},{"text":"Ja, indien medisch geadviseerd of als risico\'s niet kunnen worden geëlimineerd","correct":true},{"text":"Alleen in de laatste maand van zwangerschap","correct":false},{"text":"Alleen als ze het specifiek vragen","correct":false}]', 'RD 298/2009 bepaalt dat zwangere werknemers moeten worden vrijgesteld van nachtwerk indien medisch geadviseerd of als werkplekrisico\'s tijdens nachtelijke uren niet adequaat kunnen worden beheerst.', 3),
('G-PRL-015', 'nl', 'Wat is het wettelijke recht op borstvoedingspauzes voor moeders die terugkeren naar het werk?', '[{"text":"30 minuten per dag","correct":false},{"text":"1 uur per dag, dat kan worden verdeeld in twee periodes van een half uur","correct":true},{"text":"Er bestaat geen specifiek recht","correct":false},{"text":"15 minuten per dienst","correct":false}]', 'Borstvoeding gevende moeders hebben recht op 1 uur afwezigheid van het werk per dag (betaald), dat kan worden verdeeld in twee periodes van een half uur of naar voorkeur geaccumuleerd.', 4),
('G-PRL-015', 'nl', 'Als werkplekrisico\'s voor een zwangere werknemer niet kunnen worden geëlimineerd door aanpassing, wat moet de werkgever aanbieden?', '[{"text":"Onbetaald verlof","correct":false},{"text":"Tijdelijke herplaatsing naar een andere, risicovrije rol","correct":true},{"text":"Onmiddellijke beëindiging","correct":false},{"text":"Alleen thuiswerk","correct":false}]', 'Als risico\'s niet kunnen worden geëlimineerd, moet de werkgever tijdelijke herplaatsing naar een geschikte alternatieve rol aanbieden zonder verlaging van salaris of voordelen.', 5),
('G-PRL-015', 'nl', 'Kan een zwangere werknemer worden ontslagen vanwege haar zwangerschap?', '[{"text":"Ja, als ze haar rol niet kan uitvoeren","correct":false},{"text":"Nee, ontslag vanwege zwangerschap is illegaal en discriminerend","correct":true},{"text":"Ja, met juiste compensatie","correct":false},{"text":"Alleen tijdens proeftijd","correct":false}]', 'Ontslag vanwege zwangerschap of gerelateerde afwezigheid is illegaal onder Spaanse wetgeving en vormt discriminatie. Zwangere werknemers hebben sterke werkgelegenheidsbescherming.', 6),
('G-PRL-015', 'nl', 'Welk type chemicaliën moeten zwangere werknemers vermijden?', '[{"text":"Alleen radioactieve materialen","correct":false},{"text":"Schoonmaakchemicaliën, ontvetter en alle gevaarlijke stoffen","correct":true},{"text":"Alleen voedselconserveermiddelen","correct":false},{"text":"Er gelden geen restricties","correct":false}]', 'Zwangere werknemers moeten blootstelling aan schoonmaakchemicaliën, ontvetter, oplosmiddelen en elke stof geclassificeerd als gevaarlijk vermijden, omdat deze de foetale ontwikkeling kunnen beïnvloeden.', 7),
('G-PRL-015', 'nl', 'Welke ondersteuning moeten werkgevers bieden om borstvoeding voor terugkerende moeders te faciliteren?', '[{"text":"Geen ondersteuning is wettelijk vereist","correct":false},{"text":"Borstvoedingspauzes toestaan en indien mogelijk een privé, hygiënische ruimte bieden","correct":true},{"text":"Alleen pauzes buiten werktijden toestaan","correct":false},{"text":"Vereisen dat moeders vanuit huis werken","correct":false}]', 'Werkgevers moeten borstvoeding faciliteren door de wettelijke pauzes toe te staan en waar mogelijk een privé, schone ruimte te bieden voor borstvoeding of melkafkolving.', 8),

-- G-PRL-015: Pregnancy & Lactation Protection (German)
('G-PRL-015', 'de', 'Gemäß Ley 31/1995, was müssen Arbeitgeber tun, wenn eine Arbeitnehmerin schwanger wird?', '[{"text":"Vertrag kündigen","correct":false},{"text":"Spezifische Risikobewertung für die schwangere Arbeitnehmerin durchführen","correct":true},{"text":"Gehalt reduzieren","correct":false},{"text":"Nichts, Standardregeln gelten","correct":false}]', 'Arbeitgeber müssen eine spezifische Risikobewertung unter Berücksichtigung der Rolle der Arbeitnehmerin durchführen und Arbeitsbedingungen anpassen, um Risiken für die Schwangerschaft zu eliminieren oder zu minimieren.', 1),
('G-PRL-015', 'de', 'Von welchen der folgenden Aufgaben sollten schwangere Gastronomiearbeiterinnen befreit werden?', '[{"text":"Kundenservice","correct":false},{"text":"Schweres Heben, langes Stehen und Exposition gegenüber gefährlichen Chemikalien","correct":true},{"text":"Leichte Lebensmittelzubereitung","correct":false},{"text":"Verwaltungsaufgaben","correct":false}]', 'Schwangere Arbeiterinnen müssen vor schwerem manuellen Handling, längerem Stehen ohne Pausen, Chemikalienexposition und anderen Aufgaben geschützt werden, die Risiken für die Schwangerschaft darstellen.', 2),
('G-PRL-015', 'de', 'Haben schwangere Arbeiterinnen Anspruch auf Befreiung von Nachtschichten?', '[{"text":"Nein, alle Arbeiter müssen Nachtschichten arbeiten","correct":false},{"text":"Ja, wenn medizinisch geraten oder wenn Risiken nicht eliminiert werden können","correct":true},{"text":"Nur im letzten Monat der Schwangerschaft","correct":false},{"text":"Nur wenn sie es spezifisch anfordern","correct":false}]', 'RD 298/2009 sieht vor, dass schwangere Arbeiterinnen von Nachtarbeit befreit werden sollten, wenn medizinisch geraten oder wenn Arbeitsplatzrisiken während der Nachtstunden nicht angemessen kontrolliert werden können.', 3),
('G-PRL-015', 'de', 'Was ist der gesetzliche Anspruch auf Stillpausen für Mütter, die zur Arbeit zurückkehren?', '[{"text":"30 Minuten pro Tag","correct":false},{"text":"1 Stunde täglich, die in zwei halbstündige Perioden aufgeteilt werden kann","correct":true},{"text":"Es gibt keinen spezifischen Anspruch","correct":false},{"text":"15 Minuten pro Schicht","correct":false}]', 'Stillende Mütter haben Anspruch auf 1 Stunde Abwesenheit von der Arbeit pro Tag (bezahlt), die in zwei halbstündige Perioden aufgeteilt oder nach Belieben akkumuliert werden kann.', 4),
('G-PRL-015', 'de', 'Wenn Arbeitsplatzrisiken für eine schwangere Arbeitnehmerin nicht durch Anpassung eliminiert werden können, was muss der Arbeitgeber anbieten?', '[{"text":"Unbezahlten Urlaub","correct":false},{"text":"Vorübergehende Versetzung in eine andere, risikofreie Rolle","correct":true},{"text":"Sofortige Kündigung","correct":false},{"text":"Nur Heimarbeit","correct":false}]', 'Wenn Risiken nicht eliminiert werden können, muss der Arbeitgeber vorübergehende Versetzung in eine geeignete alternative Rolle ohne Gehalts- oder Leistungskürzung anbieten.', 5),
('G-PRL-015', 'de', 'Kann eine schwangere Arbeitnehmerin wegen ihrer Schwangerschaft entlassen werden?', '[{"text":"Ja, wenn sie ihre Rolle nicht ausführen kann","correct":false},{"text":"Nein, Entlassung wegen Schwangerschaft ist illegal und diskriminierend","correct":true},{"text":"Ja, mit angemessener Entschädigung","correct":false},{"text":"Nur während der Probezeit","correct":false}]', 'Entlassung wegen Schwangerschaft oder damit verbundener Abwesenheit ist nach spanischem Recht illegal und stellt Diskriminierung dar. Schwangere Arbeiterinnen haben starken Beschäftigungsschutz.', 6),
('G-PRL-015', 'de', 'Welche Art von Chemikalien sollten schwangere Arbeiterinnen meiden?', '[{"text":"Nur radioaktive Materialien","correct":false},{"text":"Reinigungschemikalien, Entfetter und alle gefährlichen Substanzen","correct":true},{"text":"Nur Lebensmittelkonservierungsmittel","correct":false},{"text":"Es gelten keine Einschränkungen","correct":false}]', 'Schwangere Arbeiterinnen sollten Exposition gegenüber Reinigungschemikalien, Entfettern, Lösungsmitteln und allen als gefährlich eingestuften Substanzen vermeiden, da diese die fetale Entwicklung beeinträchtigen können.', 7),
('G-PRL-015', 'de', 'Welche Unterstützung sollten Arbeitgeber bereitstellen, um das Stillen für zurückkehrende Mütter zu erleichtern?', '[{"text":"Keine Unterstützung ist gesetzlich erforderlich","correct":false},{"text":"Stillpausen erlauben und wenn möglich einen privaten, hygienischen Raum bereitstellen","correct":true},{"text":"Nur Pausen außerhalb der Arbeitszeit erlauben","correct":false},{"text":"Verlangen, dass Mütter von zu Hause arbeiten","correct":false}]', 'Arbeitgeber sollten das Stillen erleichtern, indem sie die gesetzlichen Pausen erlauben und wo möglich einen privaten, sauberen Raum zum Stillen oder Milchabpumpen bereitstellen.', 8),

-- G-PRL-016: Young Worker Protection (English)
INSERT INTO training_test_questions (guide_code, language, question, options, explanation, sort_order) VALUES
('G-PRL-016', 'en', 'What is the minimum legal working age in Spain for hospitality employment?', '[{"text":"14 years","correct":false},{"text":"16 years with parental consent or legal emancipation","correct":true},{"text":"18 years","correct":false},{"text":"15 years","correct":false}]', 'Workers under 16 require parental or guardian consent. The minimum working age is 16, though restrictions and protections apply to workers under 18.', 1),
('G-PRL-016', 'en', 'Are workers under 18 permitted to work night shifts (22:00-06:00)?', '[{"text":"Yes, with higher pay","correct":false},{"text":"No, night work is prohibited for workers under 18","correct":true},{"text":"Yes, if they volunteer","correct":false},{"text":"Only on weekends","correct":false}]', 'RD 1/1995 and Ley 31/1995 prohibit night work for workers under 18 to protect their health, development, and education.', 2),
('G-PRL-016', 'en', 'What is the maximum daily working time for workers under 18?', '[{"text":"10 hours","correct":false},{"text":"8 hours including any training time","correct":true},{"text":"12 hours with breaks","correct":false},{"text":"No maximum applies","correct":false}]', 'Workers under 18 cannot work more than 8 hours per day, and this includes any time spent in work-related training.', 3),
('G-PRL-016', 'en', 'What type of risk assessment is required for young workers?', '[{"text":"Standard risk assessment","correct":false},{"text":"Specific risk assessment considering their age, inexperience, and development","correct":true},{"text":"No risk assessment required","correct":false},{"text":"Only physical risks need to be assessed","correct":false}]', 'Young workers require a specific risk assessment that considers their physical and psychological immaturity, lack of experience, and developmental needs.', 4),
('G-PRL-016', 'en', 'Which equipment are workers under 18 generally prohibited from operating?', '[{"text":"Cash registers","correct":false},{"text":"Dangerous machinery such as slicers, meat grinders, and deep fryers","correct":true},{"text":"Coffee machines","correct":false},{"text":"Dishwashers","correct":false}]', 'Young workers must not operate equipment that poses significant injury risk, including slicers, meat grinders, industrial mixers, and fryers, unless under close supervision and after thorough training.', 5),
('G-PRL-016', 'en', 'Are young workers entitled to additional rest breaks compared to adult workers?', '[{"text":"No, same breaks apply","correct":false},{"text":"Yes, they are entitled to a 30-minute break after 4.5 hours of work","correct":true},{"text":"Only if they request it","correct":false},{"text":"Only during school holidays","correct":false}]', 'Workers under 18 must receive a break of at least 30 minutes if their working day exceeds 4.5 hours, which is more protective than adult worker requirements.', 6),
('G-PRL-016', 'en', 'What is required before a worker under 16 can begin employment?', '[{"text":"Nothing special","correct":false},{"text":"Written parental or guardian consent","correct":true},{"text":"University enrollment","correct":false},{"text":"Driver\'s license","correct":false}]', 'Workers under 16 require explicit written consent from parents or legal guardians before they can be employed, in addition to meeting other legal requirements.', 7),
('G-PRL-016', 'en', 'Why are young workers considered a vulnerable group requiring special protection?', '[{"text":"They work slower","correct":false},{"text":"They lack experience, awareness of risks, and are still developing physically and psychologically","correct":true},{"text":"They require higher wages","correct":false},{"text":"They have limited availability","correct":false}]', 'Young workers are more vulnerable due to lack of work experience, limited hazard awareness, ongoing physical and psychological development, and potential difficulty asserting their rights.', 8),

-- G-PRL-016: Young Worker Protection (Spanish)
('G-PRL-016', 'es', '¿Cuál es la edad mínima legal de trabajo en España para empleo en hostelería?', '[{"text":"14 años","correct":false},{"text":"16 años con consentimiento parental o emancipación legal","correct":true},{"text":"18 años","correct":false},{"text":"15 años","correct":false}]', 'Los trabajadores menores de 16 requieren consentimiento de padres o tutores. La edad mínima de trabajo es 16, aunque se aplican restricciones y protecciones a trabajadores menores de 18.', 1),
('G-PRL-016', 'es', '¿Está permitido que los trabajadores menores de 18 trabajen turnos nocturnos (22:00-06:00)?', '[{"text":"Sí, con salario más alto","correct":false},{"text":"No, el trabajo nocturno está prohibido para trabajadores menores de 18","correct":true},{"text":"Sí, si son voluntarios","correct":false},{"text":"Solo los fines de semana","correct":false}]', 'El RD 1/1995 y la Ley 31/1995 prohíben el trabajo nocturno para trabajadores menores de 18 para proteger su salud, desarrollo y educación.', 2),
('G-PRL-016', 'es', '¿Cuál es el tiempo máximo de trabajo diario para trabajadores menores de 18?', '[{"text":"10 horas","correct":false},{"text":"8 horas incluyendo cualquier tiempo de formación","correct":true},{"text":"12 horas con descansos","correct":false},{"text":"No se aplica máximo","correct":false}]', 'Los trabajadores menores de 18 no pueden trabajar más de 8 horas por día, y esto incluye cualquier tiempo dedicado a formación relacionada con el trabajo.', 3),
('G-PRL-016', 'es', '¿Qué tipo de evaluación de riesgos se requiere para trabajadores jóvenes?', '[{"text":"Evaluación de riesgos estándar","correct":false},{"text":"Evaluación de riesgos específica considerando su edad, inexperiencia y desarrollo","correct":true},{"text":"No se requiere evaluación de riesgos","correct":false},{"text":"Solo se necesitan evaluar riesgos físicos","correct":false}]', 'Los trabajadores jóvenes requieren una evaluación de riesgos específica que considere su inmadurez física y psicológica, falta de experiencia y necesidades de desarrollo.', 4),
('G-PRL-016', 'es', '¿Qué equipos tienen generalmente prohibido operar los trabajadores menores de 18?', '[{"text":"Cajas registradoras","correct":false},{"text":"Maquinaria peligrosa como cortadoras, picadoras de carne y freidoras profundas","correct":true},{"text":"Máquinas de café","correct":false},{"text":"Lavavajillas","correct":false}]', 'Los trabajadores jóvenes no deben operar equipos que representen riesgo significativo de lesión, incluyendo cortadoras, picadoras de carne, mezcladoras industriales y freidoras, a menos que estén bajo supervisión cercana y después de formación exhaustiva.', 5),
('G-PRL-016', 'es', '¿Tienen derecho los trabajadores jóvenes a descansos adicionales en comparación con trabajadores adultos?', '[{"text":"No, se aplican los mismos descansos","correct":false},{"text":"Sí, tienen derecho a un descanso de 30 minutos después de 4,5 horas de trabajo","correct":true},{"text":"Solo si lo solicitan","correct":false},{"text":"Solo durante vacaciones escolares","correct":false}]', 'Los trabajadores menores de 18 deben recibir un descanso de al menos 30 minutos si su jornada laboral supera las 4,5 horas, lo cual es más protector que los requisitos para trabajadores adultos.', 6),
('G-PRL-016', 'es', '¿Qué se requiere antes de que un trabajador menor de 16 pueda comenzar el empleo?', '[{"text":"Nada especial","correct":false},{"text":"Consentimiento escrito de padres o tutores","correct":true},{"text":"Matrícula universitaria","correct":false},{"text":"Licencia de conducir","correct":false}]', 'Los trabajadores menores de 16 requieren consentimiento explícito por escrito de padres o tutores legales antes de poder ser empleados, además de cumplir otros requisitos legales.', 7),
('G-PRL-016', 'es', '¿Por qué se consideran los trabajadores jóvenes un grupo vulnerable que requiere protección especial?', '[{"text":"Trabajan más lento","correct":false},{"text":"Carecen de experiencia, conciencia de riesgos y aún están desarrollándose física y psicológicamente","correct":true},{"text":"Requieren salarios más altos","correct":false},{"text":"Tienen disponibilidad limitada","correct":false}]', 'Los trabajadores jóvenes son más vulnerables debido a la falta de experiencia laboral, conciencia limitada de peligros, desarrollo físico y psicológico en curso y dificultad potencial para hacer valer sus derechos.', 8),

-- G-PRL-016: Young Worker Protection (Dutch)
('G-PRL-016', 'nl', 'Wat is de minimale wettelijke leeftijd voor werk in Spanje voor horeca werkgelegenheid?', '[{"text":"14 jaar","correct":false},{"text":"16 jaar met ouderlijke toestemming of wettelijke emancipatie","correct":true},{"text":"18 jaar","correct":false},{"text":"15 jaar","correct":false}]', 'Werknemers onder 16 hebben ouderlijke of voogdijtoestemming nodig. De minimumleeftijd voor werk is 16, hoewel beperkingen en beschermingen gelden voor werknemers onder 18.', 1),
('G-PRL-016', 'nl', 'Mogen werknemers onder 18 nachtdiensten werken (22:00-06:00)?', '[{"text":"Ja, met hoger loon","correct":false},{"text":"Nee, nachtwerk is verboden voor werknemers onder 18","correct":true},{"text":"Ja, als ze vrijwillig zijn","correct":false},{"text":"Alleen in weekenden","correct":false}]', 'RD 1/1995 en Ley 31/1995 verbieden nachtwerk voor werknemers onder 18 om hun gezondheid, ontwikkeling en onderwijs te beschermen.', 2),
('G-PRL-016', 'nl', 'Wat is de maximale dagelijkse werktijd voor werknemers onder 18?', '[{"text":"10 uur","correct":false},{"text":"8 uur inclusief opleidingstijd","correct":true},{"text":"12 uur met pauzes","correct":false},{"text":"Er geldt geen maximum","correct":false}]', 'Werknemers onder 18 kunnen niet meer dan 8 uur per dag werken, en dit omvat alle tijd besteed aan werkgerelateerde training.', 3),
('G-PRL-016', 'nl', 'Welk type risicobeoordeling is vereist voor jonge werknemers?', '[{"text":"Standaard risicobeoordeling","correct":false},{"text":"Specifieke risicobeoordeling rekening houdend met hun leeftijd, onervarenheid en ontwikkeling","correct":true},{"text":"Geen risicobeoordeling vereist","correct":false},{"text":"Alleen fysieke risico\'s hoeven te worden beoordeeld","correct":false}]', 'Jonge werknemers hebben een specifieke risicobeoordeling nodig die hun fysieke en psychologische onrijpheid, gebrek aan ervaring en ontwikkelingsbehoeften in overweging neemt.', 4),
('G-PRL-016', 'nl', 'Welke apparatuur mogen werknemers onder 18 over het algemeen niet bedienen?', '[{"text":"Kassa\'s","correct":false},{"text":"Gevaarlijke machines zoals snijmachines, vleesmolens en diepe friteuses","correct":true},{"text":"Koffiemachines","correct":false},{"text":"Vaatwassers","correct":false}]', 'Jonge werknemers mogen geen apparatuur bedienen die aanzienlijk letselrisico vormt, inclusief snijmachines, vleesmolens, industriële mixers en friteuses, tenzij onder nauw toezicht en na grondige training.', 5),
('G-PRL-016', 'nl', 'Hebben jonge werknemers recht op extra rustpauzes vergeleken met volwassen werknemers?', '[{"text":"Nee, dezelfde pauzes zijn van toepassing","correct":false},{"text":"Ja, ze hebben recht op een pauze van 30 minuten na 4,5 uur werk","correct":true},{"text":"Alleen als ze erom vragen","correct":false},{"text":"Alleen tijdens schoolvakanties","correct":false}]', 'Werknemers onder 18 moeten een pauze van ten minste 30 minuten ontvangen als hun werkdag langer dan 4,5 uur duurt, wat beschermender is dan vereisten voor volwassen werknemers.', 6),
('G-PRL-016', 'nl', 'Wat is vereist voordat een werknemer onder 16 kan beginnen met werken?', '[{"text":"Niets speciaals","correct":false},{"text":"Schriftelijke ouderlijke of voogdij toestemming","correct":true},{"text":"Universitaire inschrijving","correct":false},{"text":"Rijbewijs","correct":false}]', 'Werknemers onder 16 hebben expliciete schriftelijke toestemming van ouders of wettelijke voogden nodig voordat ze tewerkgesteld kunnen worden, naast het voldoen aan andere wettelijke vereisten.', 7),
('G-PRL-016', 'nl', 'Waarom worden jonge werknemers beschouwd als een kwetsbare groep die speciale bescherming vereist?', '[{"text":"Ze werken langzamer","correct":false},{"text":"Ze missen ervaring, bewustzijn van risico\'s en zijn nog fysiek en psychologisch aan het ontwikkelen","correct":true},{"text":"Ze vereisen hogere lonen","correct":false},{"text":"Ze hebben beperkte beschikbaarheid","correct":false}]', 'Jonge werknemers zijn kwetsbaarder door gebrek aan werkervaring, beperkt gevarenbewustzijn, voortdurende fysieke en psychologische ontwikkeling en potentiële moeilijkheid om hun rechten te doen gelden.', 8),

-- G-PRL-016: Young Worker Protection (German)
('G-PRL-016', 'de', 'Was ist das gesetzliche Mindestalter in Spanien für Beschäftigung in der Gastronomie?', '[{"text":"14 Jahre","correct":false},{"text":"16 Jahre mit elterlicher Zustimmung oder rechtlicher Emanzipation","correct":true},{"text":"18 Jahre","correct":false},{"text":"15 Jahre","correct":false}]', 'Arbeiter unter 16 benötigen elterliche oder Vormund-Zustimmung. Das Mindestalter für Arbeit ist 16, obwohl Einschränkungen und Schutzmaßnahmen für Arbeiter unter 18 gelten.', 1),
('G-PRL-016', 'de', 'Dürfen Arbeiter unter 18 Nachtschichten arbeiten (22:00-06:00)?', '[{"text":"Ja, mit höherem Lohn","correct":false},{"text":"Nein, Nachtarbeit ist für Arbeiter unter 18 verboten","correct":true},{"text":"Ja, wenn sie freiwillig sind","correct":false},{"text":"Nur am Wochenende","correct":false}]', 'RD 1/1995 und Ley 31/1995 verbieten Nachtarbeit für Arbeiter unter 18, um ihre Gesundheit, Entwicklung und Bildung zu schützen.', 2),
('G-PRL-016', 'de', 'Was ist die maximale tägliche Arbeitszeit für Arbeiter unter 18?', '[{"text":"10 Stunden","correct":false},{"text":"8 Stunden einschließlich jeder Ausbildungszeit","correct":true},{"text":"12 Stunden mit Pausen","correct":false},{"text":"Es gilt kein Maximum","correct":false}]', 'Arbeiter unter 18 können nicht mehr als 8 Stunden pro Tag arbeiten, und dies schließt jede Zeit ein, die für arbeitsbezogene Schulung aufgewendet wird.', 3),
('G-PRL-016', 'de', 'Welche Art von Risikobewertung ist für junge Arbeiter erforderlich?', '[{"text":"Standard-Risikobewertung","correct":false},{"text":"Spezifische Risikobewertung unter Berücksichtigung ihres Alters, ihrer Unerfahrenheit und Entwicklung","correct":true},{"text":"Keine Risikobewertung erforderlich","correct":false},{"text":"Nur physische Risiken müssen bewertet werden","correct":false}]', 'Junge Arbeiter benötigen eine spezifische Risikobewertung, die ihre körperliche und psychologische Unreife, mangelnde Erfahrung und Entwicklungsbedürfnisse berücksichtigt.', 4),
('G-PRL-016', 'de', 'Welche Geräte dürfen Arbeiter unter 18 generell nicht bedienen?', '[{"text":"Registrierkassen","correct":false},{"text":"Gefährliche Maschinen wie Aufschnittmaschinen, Fleischwölfe und Fritteusen","correct":true},{"text":"Kaffeemaschinen","correct":false},{"text":"Geschirrspüler","correct":false}]', 'Junge Arbeiter dürfen keine Geräte bedienen, die erhebliches Verletzungsrisiko darstellen, einschließlich Aufschnittmaschinen, Fleischwölfe, Industriemixer und Fritteusen, es sei denn unter enger Aufsicht und nach gründlicher Schulung.', 5),
('G-PRL-016', 'de', 'Haben junge Arbeiter Anspruch auf zusätzliche Ruhepausen im Vergleich zu erwachsenen Arbeitern?', '[{"text":"Nein, dieselben Pausen gelten","correct":false},{"text":"Ja, sie haben Anspruch auf eine 30-minütige Pause nach 4,5 Stunden Arbeit","correct":true},{"text":"Nur wenn sie danach fragen","correct":false},{"text":"Nur während Schulferien","correct":false}]', 'Arbeiter unter 18 müssen eine Pause von mindestens 30 Minuten erhalten, wenn ihr Arbeitstag 4,5 Stunden überschreitet, was schützender ist als Anforderungen für erwachsene Arbeiter.', 6),
('G-PRL-016', 'de', 'Was ist erforderlich, bevor ein Arbeiter unter 16 eine Beschäftigung beginnen kann?', '[{"text":"Nichts Besonderes","correct":false},{"text":"Schriftliche elterliche oder Vormund-Zustimmung","correct":true},{"text":"Universitätseinschreibung","correct":false},{"text":"Führerschein","correct":false}]', 'Arbeiter unter 16 benötigen ausdrückliche schriftliche Zustimmung von Eltern oder rechtlichen Vormündern, bevor sie beschäftigt werden können, zusätzlich zu anderen gesetzlichen Anforderungen.', 7),
('G-PRL-016', 'de', 'Warum werden junge Arbeiter als gefährdete Gruppe betrachtet, die besonderen Schutz erfordert?', '[{"text":"Sie arbeiten langsamer","correct":false},{"text":"Sie fehlen Erfahrung, Bewusstsein für Risiken und entwickeln sich noch körperlich und psychologisch","correct":true},{"text":"Sie benötigen höhere Löhne","correct":false},{"text":"Sie haben begrenzte Verfügbarkeit","correct":false}]', 'Junge Arbeiter sind gefährdeter aufgrund mangelnder Arbeitserfahrung, begrenztem Gefahrenbewusstsein, laufender körperlicher und psychologischer Entwicklung und potenzieller Schwierigkeit, ihre Rechte durchzusetzen.', 8),

-- G-PRL-017: Night Work Health Surveillance (English)
INSERT INTO training_test_questions (guide_code, language, question, options, explanation, sort_order) VALUES
('G-PRL-017', 'en', 'What defines a "night worker" under Spanish labor law?', '[{"text":"Anyone who occasionally works at night","correct":false},{"text":"A worker who regularly works at least 3 hours during the period 22:00-06:00","correct":true},{"text":"Only workers on the midnight shift","correct":false},{"text":"Anyone working after 20:00","correct":false}]', 'Night workers are those who regularly perform at least 3 hours of their daily work between 22:00 and 06:00, or who work a significant portion of their annual hours during this period.', 1),
('G-PRL-017', 'en', 'According to Ley 31/1995, what are night workers entitled to regarding health surveillance?', '[{"text":"No special entitlement","correct":false},{"text":"Free, periodic medical examinations specific to night work risks","correct":true},{"text":"One medical check at hiring only","correct":false},{"text":"Medical exams only if they request them","correct":false}]', 'Night workers are entitled to free, periodic health surveillance to assess specific health risks associated with night work, including sleep disorders and circadian rhythm disruption.', 2),
('G-PRL-017', 'en', 'What is the maximum average working time for night workers in any 15-day period?', '[{"text":"9 hours","correct":false},{"text":"8 hours","correct":true},{"text":"10 hours","correct":false},{"text":"No limit applies","correct":false}]', 'Night workers may not average more than 8 hours of work in any 15-day period, providing additional protection due to the health impacts of night work.', 3),
('G-PRL-017', 'en', 'If a night worker develops health problems related to night work, what must the employer offer?', '[{"text":"Dismissal with compensation","correct":false},{"text":"Transfer to day work whenever possible","correct":true},{"text":"Reduced pay for less demanding work","correct":false},{"text":"Nothing, the worker must adapt","correct":false}]', 'Employers must transfer night workers to day shifts whenever possible if they develop health problems certified by medical services as related to night work.', 4),
('G-PRL-017', 'en', 'What specific health risks are associated with night work that should be monitored?', '[{"text":"Only physical injuries","correct":false},{"text":"Sleep disorders, cardiovascular issues, digestive problems, and mental health concerns","correct":true},{"text":"Only fatigue","correct":false},{"text":"No specific risks exist","correct":false}]', 'Night work is associated with disrupted circadian rhythms leading to sleep disorders, increased cardiovascular and metabolic risks, digestive issues, and mental health problems including depression.', 5),
('G-PRL-017', 'en', 'Are night workers entitled to additional rest periods compared to day workers?', '[{"text":"No difference in rest entitlements","correct":false},{"text":"Yes, adequate rest between shifts must be ensured to allow for sleep recovery","correct":true},{"text":"Only if they request it","correct":false},{"text":"Only during weekends","correct":false}]', 'Night workers require adequate rest between shifts (minimum 12 hours) to allow for proper sleep and recovery, which is particularly important due to circadian disruption.', 6),
('G-PRL-017', 'en', 'How should employers support night workers\' health and wellbeing?', '[{"text":"No specific support required","correct":false},{"text":"Provide health surveillance, adequate breaks, proper lighting, and access to food and drink","correct":true},{"text":"Only provide transportation","correct":false},{"text":"Increase salary only","correct":false}]', 'Employers should provide periodic health checks, ensure adequate breaks, maintain proper workplace lighting and temperature, provide access to healthy food and beverages, and monitor for signs of fatigue.', 7),
('G-PRL-017', 'en', 'Why is health surveillance particularly important for night workers in hospitality?', '[{"text":"They are more likely to be injured","correct":false},{"text":"Night work disrupts natural circadian rhythms, affecting long-term health and safety","correct":true},{"text":"They have higher absenteeism","correct":false},{"text":"It is not particularly important","correct":false}]', 'Working against natural circadian rhythms has cumulative effects on physical and mental health, increasing accident risk and chronic health conditions over time, making monitoring essential.', 8),

-- G-PRL-017: Night Work Health Surveillance (Spanish)
('G-PRL-017', 'es', '¿Qué define a un "trabajador nocturno" según la ley laboral española?', '[{"text":"Cualquiera que trabaje ocasionalmente de noche","correct":false},{"text":"Un trabajador que realiza regularmente al menos 3 horas durante el período 22:00-06:00","correct":true},{"text":"Solo trabajadores en turno de medianoche","correct":false},{"text":"Cualquiera que trabaje después de las 20:00","correct":false}]', 'Los trabajadores nocturnos son aquellos que realizan regularmente al menos 3 horas de su trabajo diario entre las 22:00 y las 06:00, o que trabajan una parte significativa de sus horas anuales durante este período.', 1),
('G-PRL-017', 'es', 'Según la Ley 31/1995, ¿a qué tienen derecho los trabajadores nocturnos respecto a la vigilancia de la salud?', '[{"text":"Ningún derecho especial","correct":false},{"text":"Exámenes médicos periódicos gratuitos específicos para riesgos del trabajo nocturno","correct":true},{"text":"Un chequeo médico solo al contratar","correct":false},{"text":"Exámenes médicos solo si los solicitan","correct":false}]', 'Los trabajadores nocturnos tienen derecho a vigilancia de salud periódica gratuita para evaluar riesgos específicos asociados con el trabajo nocturno, incluyendo trastornos del sueño y alteración del ritmo circadiano.', 2),
('G-PRL-017', 'es', '¿Cuál es el tiempo máximo promedio de trabajo para trabajadores nocturnos en cualquier período de 15 días?', '[{"text":"9 horas","correct":false},{"text":"8 horas","correct":true},{"text":"10 horas","correct":false},{"text":"No se aplica límite","correct":false}]', 'Los trabajadores nocturnos no pueden promediar más de 8 horas de trabajo en cualquier período de 15 días, proporcionando protección adicional debido a los impactos en la salud del trabajo nocturno.', 3),
('G-PRL-017', 'es', 'Si un trabajador nocturno desarrolla problemas de salud relacionados con el trabajo nocturno, ¿qué debe ofrecer el empleador?', '[{"text":"Despido con compensación","correct":false},{"text":"Traslado a trabajo diurno siempre que sea posible","correct":true},{"text":"Salario reducido por trabajo menos exigente","correct":false},{"text":"Nada, el trabajador debe adaptarse","correct":false}]', 'Los empleadores deben trasladar a los trabajadores nocturnos a turnos diurnos siempre que sea posible si desarrollan problemas de salud certificados por servicios médicos como relacionados con el trabajo nocturno.', 4),
('G-PRL-017', 'es', '¿Qué riesgos específicos para la salud asociados con el trabajo nocturno deben monitorearse?', '[{"text":"Solo lesiones físicas","correct":false},{"text":"Trastornos del sueño, problemas cardiovasculares, problemas digestivos y preocupaciones de salud mental","correct":true},{"text":"Solo fatiga","correct":false},{"text":"No existen riesgos específicos","correct":false}]', 'El trabajo nocturno está asociado con ritmos circadianos alterados que conducen a trastornos del sueño, riesgos cardiovasculares y metabólicos aumentados, problemas digestivos y problemas de salud mental incluyendo depresión.', 5),
('G-PRL-017', 'es', '¿Tienen derecho los trabajadores nocturnos a períodos de descanso adicionales en comparación con trabajadores diurnos?', '[{"text":"No hay diferencia en derechos de descanso","correct":false},{"text":"Sí, debe asegurarse descanso adecuado entre turnos para permitir recuperación del sueño","correct":true},{"text":"Solo si lo solicitan","correct":false},{"text":"Solo durante fines de semana","correct":false}]', 'Los trabajadores nocturnos requieren descanso adecuado entre turnos (mínimo 12 horas) para permitir sueño y recuperación adecuados, lo cual es particularmente importante debido a la alteración circadiana.', 6),
('G-PRL-017', 'es', '¿Cómo deben los empleadores apoyar la salud y bienestar de los trabajadores nocturnos?', '[{"text":"No se requiere apoyo específico","correct":false},{"text":"Proporcionar vigilancia de salud, descansos adecuados, iluminación apropiada y acceso a comida y bebida","correct":true},{"text":"Solo proporcionar transporte","correct":false},{"text":"Solo aumentar salario","correct":false}]', 'Los empleadores deben proporcionar chequeos de salud periódicos, asegurar descansos adecuados, mantener iluminación y temperatura apropiadas en el lugar de trabajo, proporcionar acceso a comida y bebidas saludables, y monitorear signos de fatiga.', 7),
('G-PRL-017', 'es', '¿Por qué es particularmente importante la vigilancia de la salud para trabajadores nocturnos en hostelería?', '[{"text":"Son más propensos a lesionarse","correct":false},{"text":"El trabajo nocturno altera los ritmos circadianos naturales, afectando la salud y seguridad a largo plazo","correct":true},{"text":"Tienen mayor absentismo","correct":false},{"text":"No es particularmente importante","correct":false}]', 'Trabajar contra los ritmos circadianos naturales tiene efectos acumulativos en la salud física y mental, aumentando el riesgo de accidentes y condiciones de salud crónicas con el tiempo, haciendo esencial el monitoreo.', 8),

-- G-PRL-017: Night Work Health Surveillance (Dutch)
('G-PRL-017', 'nl', 'Wat definieert een "nachtwerker" volgens Spaanse arbeidswetgeving?', '[{"text":"Iedereen die af en toe \'s nachts werkt","correct":false},{"text":"Een werknemer die regelmatig minstens 3 uur werkt tijdens de periode 22:00-06:00","correct":true},{"text":"Alleen werknemers op de middernachtdienst","correct":false},{"text":"Iedereen die werkt na 20:00","correct":false}]', 'Nachtwerkers zijn degenen die regelmatig minstens 3 uur van hun dagelijks werk tussen 22:00 en 06:00 uitvoeren, of die een significant deel van hun jaarlijkse uren tijdens deze periode werken.', 1),
('G-PRL-017', 'nl', 'Volgens Ley 31/1995, waar hebben nachtwerkers recht op met betrekking tot gezondheidstoezicht?', '[{"text":"Geen speciale rechten","correct":false},{"text":"Gratis, periodieke medische onderzoeken specifiek voor nachtwerk risico\'s","correct":true},{"text":"Één medische controle alleen bij aanwerving","correct":false},{"text":"Medische onderzoeken alleen als ze erom vragen","correct":false}]', 'Nachtwerkers hebben recht op gratis, periodiek gezondheidstoezicht om specifieke gezondheidsrisico\'s geassocieerd met nachtwerk te beoordelen, inclusief slaapstoornissen en verstoring van het circadiaans ritme.', 2),
('G-PRL-017', 'nl', 'Wat is de maximale gemiddelde werktijd voor nachtwerkers in een willekeurige periode van 15 dagen?', '[{"text":"9 uur","correct":false},{"text":"8 uur","correct":true},{"text":"10 uur","correct":false},{"text":"Er geldt geen limiet","correct":false}]', 'Nachtwerkers mogen niet meer dan gemiddeld 8 uur werk in een willekeurige periode van 15 dagen verrichten, wat extra bescherming biedt vanwege de gezondheidseffecten van nachtwerk.', 3),
('G-PRL-017', 'nl', 'Als een nachtwerker gezondheidsproblemen ontwikkelt gerelateerd aan nachtwerk, wat moet de werkgever aanbieden?', '[{"text":"Ontslag met compensatie","correct":false},{"text":"Overplaatsing naar dagwerk wanneer mogelijk","correct":true},{"text":"Verlaagd loon voor minder veeleisend werk","correct":false},{"text":"Niets, de werknemer moet zich aanpassen","correct":false}]', 'Werkgevers moeten nachtwerkers naar dagdiensten overplaatsen wanneer mogelijk als ze gezondheidsproblemen ontwikkelen die door medische diensten zijn gecertificeerd als gerelateerd aan nachtwerk.', 4),
('G-PRL-017', 'nl', 'Welke specifieke gezondheidsrisico\'s geassocieerd met nachtwerk moeten worden gemonitord?', '[{"text":"Alleen fysieke verwondingen","correct":false},{"text":"Slaapstoornissen, cardiovasculaire problemen, spijsverteringsproblemen en geestelijke gezondheidsproblemen","correct":true},{"text":"Alleen vermoeidheid","correct":false},{"text":"Er bestaan geen specifieke risico\'s","correct":false}]', 'Nachtwerk is geassocieerd met verstoorde circadiane ritmes die leiden tot slaapstoornissen, verhoogde cardiovasculaire en metabole risico\'s, spijsverteringsproblemen en geestelijke gezondheidsproblemen inclusief depressie.', 5),
('G-PRL-017', 'nl', 'Hebben nachtwerkers recht op extra rustperiodes vergeleken met dagwerkers?', '[{"text":"Geen verschil in rustrechten","correct":false},{"text":"Ja, adequate rust tussen diensten moet worden gewaarborgd om slaapherstel mogelijk te maken","correct":true},{"text":"Alleen als ze erom vragen","correct":false},{"text":"Alleen tijdens weekenden","correct":false}]', 'Nachtwerkers hebben adequate rust tussen diensten nodig (minimum 12 uur) om behoorlijke slaap en herstel mogelijk te maken, wat bijzonder belangrijk is vanwege circadiaanse verstoring.', 6),
('G-PRL-017', 'nl', 'Hoe moeten werkgevers de gezondheid en welzijn van nachtwerkers ondersteunen?', '[{"text":"Geen specifieke ondersteuning vereist","correct":false},{"text":"Gezondheidstoezicht bieden, adequate pauzes, juiste verlichting en toegang tot eten en drinken","correct":true},{"text":"Alleen vervoer bieden","correct":false},{"text":"Alleen salaris verhogen","correct":false}]', 'Werkgevers moeten periodieke gezondheidscontroles bieden, adequate pauzes waarborgen, juiste werkplekverlichting en temperatuur handhaven, toegang tot gezond eten en drinken bieden en monitoren op tekenen van vermoeidheid.', 7),
('G-PRL-017', 'nl', 'Waarom is gezondheidstoezicht bijzonder belangrijk voor nachtwerkers in de horeca?', '[{"text":"Ze zijn waarschijnlijker gewond","correct":false},{"text":"Nachtwerk verstoort natuurlijke circadiane ritmes, wat langetermijn gezondheid en veiligheid beïnvloedt","correct":true},{"text":"Ze hebben hoger ziekteverzuim","correct":false},{"text":"Het is niet bijzonder belangrijk","correct":false}]', 'Werken tegen natuurlijke circadiane ritmes heeft cumulatieve effecten op fysieke en mentale gezondheid, verhoogt ongevallenrisico en chronische gezondheidsproblemen in de loop der tijd, waardoor monitoring essentieel is.', 8),

-- G-PRL-017: Night Work Health Surveillance (German)
('G-PRL-017', 'de', 'Was definiert einen "Nachtarbeiter" nach spanischem Arbeitsrecht?', '[{"text":"Jeder, der gelegentlich nachts arbeitet","correct":false},{"text":"Ein Arbeiter, der regelmäßig mindestens 3 Stunden während der Zeit 22:00-06:00 arbeitet","correct":true},{"text":"Nur Arbeiter in Mitternachtsschicht","correct":false},{"text":"Jeder, der nach 20:00 arbeitet","correct":false}]', 'Nachtarbeiter sind diejenigen, die regelmäßig mindestens 3 Stunden ihrer täglichen Arbeit zwischen 22:00 und 06:00 ausführen, oder die einen signifikanten Teil ihrer Jahresstunden während dieser Periode arbeiten.', 1),
('G-PRL-017', 'de', 'Gemäß Ley 31/1995, worauf haben Nachtarbeiter Anspruch bezüglich Gesundheitsüberwachung?', '[{"text":"Keine besonderen Ansprüche","correct":false},{"text":"Kostenlose, periodische medizinische Untersuchungen spezifisch für Nachtarbeitsrisiken","correct":true},{"text":"Eine medizinische Untersuchung nur bei Einstellung","correct":false},{"text":"Medizinische Untersuchungen nur wenn sie danach fragen","correct":false}]', 'Nachtarbeiter haben Anspruch auf kostenlose, periodische Gesundheitsüberwachung zur Bewertung spezifischer Gesundheitsrisiken im Zusammenhang mit Nachtarbeit, einschließlich Schlafstörungen und Störung des zirkadianen Rhythmus.', 2),
('G-PRL-017', 'de', 'Was ist die maximale durchschnittliche Arbeitszeit für Nachtarbeiter in einem beliebigen 15-Tage-Zeitraum?', '[{"text":"9 Stunden","correct":false},{"text":"8 Stunden","correct":true},{"text":"10 Stunden","correct":false},{"text":"Es gilt keine Grenze","correct":false}]', 'Nachtarbeiter dürfen in einem beliebigen 15-Tage-Zeitraum durchschnittlich nicht mehr als 8 Stunden arbeiten, was zusätzlichen Schutz aufgrund der Gesundheitsauswirkungen von Nachtarbeit bietet.', 3),
('G-PRL-017', 'de', 'Wenn ein Nachtarbeiter Gesundheitsprobleme im Zusammenhang mit Nachtarbeit entwickelt, was muss der Arbeitgeber anbieten?', '[{"text":"Entlassung mit Entschädigung","correct":false},{"text":"Versetzung zu Tagarbeit wann immer möglich","correct":true},{"text":"Reduziertes Gehalt für weniger anspruchsvolle Arbeit","correct":false},{"text":"Nichts, der Arbeiter muss sich anpassen","correct":false}]', 'Arbeitgeber müssen Nachtarbeiter zu Tagschichten versetzen, wann immer möglich, wenn sie Gesundheitsprobleme entwickeln, die von medizinischen Diensten als im Zusammenhang mit Nachtarbeit stehend zertifiziert werden.', 4),
('G-PRL-017', 'de', 'Welche spezifischen Gesundheitsrisiken im Zusammenhang mit Nachtarbeit sollten überwacht werden?', '[{"text":"Nur körperliche Verletzungen","correct":false},{"text":"Schlafstörungen, kardiovaskuläre Probleme, Verdauungsprobleme und psychische Gesundheitsprobleme","correct":true},{"text":"Nur Müdigkeit","correct":false},{"text":"Es gibt keine spezifischen Risiken","correct":false}]', 'Nachtarbeit ist mit gestörten zirkadianen Rhythmen verbunden, die zu Schlafstörungen, erhöhten kardiovaskulären und metabolischen Risiken, Verdauungsproblemen und psychischen Gesundheitsproblemen einschließlich Depression führen.', 5),
('G-PRL-017', 'de', 'Haben Nachtarbeiter Anspruch auf zusätzliche Ruhezeiten im Vergleich zu Tagarbeitern?', '[{"text":"Kein Unterschied bei Ruheansprüchen","correct":false},{"text":"Ja, angemessene Ruhe zwischen Schichten muss gewährleistet werden, um Schlaferholung zu ermöglichen","correct":true},{"text":"Nur wenn sie danach fragen","correct":false},{"text":"Nur während Wochenenden","correct":false}]', 'Nachtarbeiter benötigen angemessene Ruhe zwischen Schichten (mindestens 12 Stunden), um ordnungsgemäßen Schlaf und Erholung zu ermöglichen, was besonders wichtig ist aufgrund zirkadianer Störung.', 6),
('G-PRL-017', 'de', 'Wie sollten Arbeitgeber Gesundheit und Wohlbefinden von Nachtarbeitern unterstützen?', '[{"text":"Keine spezifische Unterstützung erforderlich","correct":false},{"text":"Gesundheitsüberwachung bereitstellen, angemessene Pausen, richtige Beleuchtung und Zugang zu Essen und Trinken","correct":true},{"text":"Nur Transport bereitstellen","correct":false},{"text":"Nur Gehalt erhöhen","correct":false}]', 'Arbeitgeber sollten periodische Gesundheitschecks bereitstellen, angemessene Pausen sicherstellen, ordnungsgemäße Arbeitsplatzbeleuchtung und Temperatur aufrechterhalten, Zugang zu gesundem Essen und Getränken bieten und auf Anzeichen von Müdigkeit überwachen.', 7),
('G-PRL-017', 'de', 'Warum ist Gesundheitsüberwachung besonders wichtig für Nachtarbeiter in der Gastronomie?', '[{"text":"Sie sind wahrscheinlicher verletzt","correct":false},{"text":"Nachtarbeit stört natürliche zirkadiane Rhythmen, beeinflusst Langzeitgesundheit und Sicherheit","correct":true},{"text":"Sie haben höheren Absentismus","correct":false},{"text":"Es ist nicht besonders wichtig","correct":false}]', 'Arbeiten gegen natürliche zirkadiane Rhythmen hat kumulative Auswirkungen auf körperliche und geistige Gesundheit, erhöht Unfallrisiko und chronische Gesundheitszustände im Laufe der Zeit, was Überwachung essentiell macht.', 8),

-- G-PRL-018: Psychosocial Risk Prevention (English)
INSERT INTO training_test_questions (guide_code, language, question, options, explanation, sort_order) VALUES
('G-PRL-018', 'en', 'What are psychosocial risks in the workplace?', '[{"text":"Only physical safety hazards","correct":false},{"text":"Work-related stress, burnout, harassment, and factors affecting mental health","correct":true},{"text":"Equipment malfunctions","correct":false},{"text":"Chemical exposures only","correct":false}]', 'Psychosocial risks include work organization factors, interpersonal relationships, workload, job insecurity, harassment, and other factors that affect workers\' psychological and social wellbeing.', 1),
('G-PRL-018', 'en', 'Are psychosocial risks required to be included in workplace risk assessments?', '[{"text":"No, only physical risks must be assessed","correct":false},{"text":"Yes, psychosocial risks must be assessed as part of comprehensive risk assessment","correct":true},{"text":"Only in large companies","correct":false},{"text":"Only if workers complain","correct":false}]', 'Ley 31/1995 requires assessment of ALL workplace risks including psychosocial factors such as workload, work pace, shift patterns, role clarity, and interpersonal relationships.', 2),
('G-PRL-018', 'en', 'Which of the following is a common psychosocial risk in hospitality?', '[{"text":"Insufficient lighting","correct":false},{"text":"High workload, irregular hours, customer aggression, and inadequate staffing","correct":true},{"text":"Cold storage temperatures","correct":false},{"text":"Food allergens","correct":false}]', 'Hospitality workers face high psychosocial risks including excessive workload, irregular and unsocial hours, dealing with difficult customers, job insecurity, and often inadequate support.', 3),
('G-PRL-018', 'en', 'What must employers implement to prevent workplace harassment and bullying?', '[{"text":"Nothing specific is required","correct":false},{"text":"Clear anti-harassment policies, complaint procedures, and training","correct":true},{"text":"Only verbal warnings","correct":false},{"text":"Cameras in all areas","correct":false}]', 'Employers must have documented anti-harassment protocols covering sexual harassment, harassment based on protected characteristics, and bullying, with clear reporting and investigation procedures.', 4),
('G-PRL-018', 'en', 'What are signs of work-related stress that managers should recognize?', '[{"text":"Only absenteeism","correct":false},{"text":"Changes in behavior, mood, performance, increased absenteeism, and health complaints","correct":true},{"text":"Only formal complaints","correct":false},{"text":"Punctuality issues only","correct":false}]', 'Warning signs include irritability, withdrawal, performance decline, increased errors, absenteeism, physical complaints (headaches, fatigue), sleep problems, and difficulty concentrating.', 5),
('G-PRL-018', 'en', 'How can employers reduce psychosocial risks in hospitality?', '[{"text":"Increase surveillance","correct":false},{"text":"Ensure reasonable workloads, predictable schedules, adequate staffing, and supportive management","correct":true},{"text":"Reduce breaks","correct":false},{"text":"Increase performance pressure","correct":false}]', 'Prevention measures include reasonable and predictable schedules, adequate staffing levels, clear role definitions, supportive management, opportunities for worker input, and promoting work-life balance.', 6),
('G-PRL-018', 'en', 'What should workers do if they experience workplace harassment or excessive stress?', '[{"text":"Ignore it and hope it improves","correct":false},{"text":"Report it through official channels to HR, management, or worker representatives","correct":true},{"text":"Quit immediately","correct":false},{"text":"Only discuss with coworkers","correct":false}]', 'Workers should use formal reporting channels including HR, management, union representatives, or the designated person responsible for harassment complaints. All complaints must be investigated.', 7),
('G-PRL-018', 'en', 'Why is promoting work-life balance important for psychosocial health?', '[{"text":"It is not important","correct":false},{"text":"Chronic work-life imbalance leads to burnout, health problems, and reduced performance","correct":true},{"text":"Only for productivity","correct":false},{"text":"Only for part-time workers","correct":false}]', 'Sustained work-life imbalance causes chronic stress, burnout, relationship problems, physical and mental health issues, and ultimately reduces work performance and increases errors and accidents.', 8),

-- G-PRL-018: Psychosocial Risk Prevention (Spanish)
('G-PRL-018', 'es', '¿Qué son los riesgos psicosociales en el lugar de trabajo?', '[{"text":"Solo peligros de seguridad física","correct":false},{"text":"Estrés laboral, agotamiento, acoso y factores que afectan la salud mental","correct":true},{"text":"Mal funcionamiento de equipos","correct":false},{"text":"Solo exposiciones químicas","correct":false}]', 'Los riesgos psicosociales incluyen factores de organización del trabajo, relaciones interpersonales, carga de trabajo, inseguridad laboral, acoso y otros factores que afectan el bienestar psicológico y social de los trabajadores.', 1),
('G-PRL-018', 'es', '¿Se requiere que los riesgos psicosociales se incluyan en las evaluaciones de riesgos laborales?', '[{"text":"No, solo deben evaluarse riesgos físicos","correct":false},{"text":"Sí, los riesgos psicosociales deben evaluarse como parte de la evaluación integral de riesgos","correct":true},{"text":"Solo en grandes empresas","correct":false},{"text":"Solo si los trabajadores se quejan","correct":false}]', 'La Ley 31/1995 requiere evaluación de TODOS los riesgos laborales incluyendo factores psicosociales como carga de trabajo, ritmo de trabajo, patrones de turnos, claridad de roles y relaciones interpersonales.', 2),
('G-PRL-018', 'es', '¿Cuál de los siguientes es un riesgo psicosocial común en hostelería?', '[{"text":"Iluminación insuficiente","correct":false},{"text":"Alta carga de trabajo, horarios irregulares, agresión de clientes y personal insuficiente","correct":true},{"text":"Temperaturas de almacenamiento frío","correct":false},{"text":"Alérgenos alimentarios","correct":false}]', 'Los trabajadores de hostelería enfrentan altos riesgos psicosociales incluyendo carga de trabajo excesiva, horarios irregulares y antisociales, trato con clientes difíciles, inseguridad laboral y a menudo apoyo inadecuado.', 3),
('G-PRL-018', 'es', '¿Qué deben implementar los empleadores para prevenir el acoso y el bullying laboral?', '[{"text":"Nada específico se requiere","correct":false},{"text":"Políticas claras contra el acoso, procedimientos de queja y capacitación","correct":true},{"text":"Solo advertencias verbales","correct":false},{"text":"Cámaras en todas las áreas","correct":false}]', 'Los empleadores deben tener protocolos contra el acoso documentados que cubran acoso sexual, acoso basado en características protegidas y bullying, con procedimientos claros de reporte e investigación.', 4),
('G-PRL-018', 'es', '¿Cuáles son señales de estrés relacionado con el trabajo que los gerentes deben reconocer?', '[{"text":"Solo absentismo","correct":false},{"text":"Cambios en comportamiento, estado de ánimo, rendimiento, aumento de absentismo y quejas de salud","correct":true},{"text":"Solo quejas formales","correct":false},{"text":"Solo problemas de puntualidad","correct":false}]', 'Las señales de advertencia incluyen irritabilidad, retraimiento, disminución del rendimiento, aumento de errores, absentismo, quejas físicas (dolores de cabeza, fatiga), problemas de sueño y dificultad para concentrarse.', 5),
('G-PRL-018', 'es', '¿Cómo pueden los empleadores reducir los riesgos psicosociales en hostelería?', '[{"text":"Aumentar vigilancia","correct":false},{"text":"Asegurar cargas de trabajo razonables, horarios predecibles, personal adecuado y gestión de apoyo","correct":true},{"text":"Reducir descansos","correct":false},{"text":"Aumentar presión de rendimiento","correct":false}]', 'Las medidas de prevención incluyen horarios razonables y predecibles, niveles adecuados de personal, definiciones claras de roles, gestión de apoyo, oportunidades para aporte de trabajadores y promoción del equilibrio trabajo-vida.', 6),
('G-PRL-018', 'es', '¿Qué deben hacer los trabajadores si experimentan acoso laboral o estrés excesivo?', '[{"text":"Ignorarlo y esperar que mejore","correct":false},{"text":"Reportarlo a través de canales oficiales a RRHH, gerencia o representantes de trabajadores","correct":true},{"text":"Renunciar inmediatamente","correct":false},{"text":"Solo discutirlo con compañeros","correct":false}]', 'Los trabajadores deben usar canales formales de reporte incluyendo RRHH, gerencia, representantes sindicales o la persona designada responsable de quejas de acoso. Todas las quejas deben ser investigadas.', 7),
('G-PRL-018', 'es', '¿Por qué es importante promover el equilibrio trabajo-vida para la salud psicosocial?', '[{"text":"No es importante","correct":false},{"text":"El desequilibrio crónico trabajo-vida conduce a agotamiento, problemas de salud y rendimiento reducido","correct":true},{"text":"Solo por productividad","correct":false},{"text":"Solo para trabajadores a tiempo parcial","correct":false}]', 'El desequilibrio sostenido trabajo-vida causa estrés crónico, agotamiento, problemas de relaciones, problemas de salud física y mental, y finalmente reduce el rendimiento laboral y aumenta errores y accidentes.', 8),

-- G-PRL-018: Psychosocial Risk Prevention (Dutch)
('G-PRL-018', 'nl', 'Wat zijn psychosociale risico\'s op de werkplek?', '[{"text":"Alleen fysieke veiligheidsrisico\'s","correct":false},{"text":"Werkgerelateerde stress, burn-out, intimidatie en factoren die mentale gezondheid beïnvloeden","correct":true},{"text":"Apparatuur storingen","correct":false},{"text":"Alleen chemische blootstellingen","correct":false}]', 'Psychosociale risico\'s omvatten werkorganisatiefactoren, interpersoonlijke relaties, werkdruk, baanonzekerheid, intimidatie en andere factoren die het psychologisch en sociaal welzijn van werknemers beïnvloeden.', 1),
('G-PRL-018', 'nl', 'Moeten psychosociale risico\'s worden opgenomen in werkplekrisico-beoordelingen?', '[{"text":"Nee, alleen fysieke risico\'s moeten worden beoordeeld","correct":false},{"text":"Ja, psychosociale risico\'s moeten worden beoordeeld als onderdeel van uitgebreide risicobeoordeling","correct":true},{"text":"Alleen in grote bedrijven","correct":false},{"text":"Alleen als werknemers klagen","correct":false}]', 'Ley 31/1995 vereist beoordeling van ALLE werkplekrisico\'s inclusief psychosociale factoren zoals werkdruk, werktempo, dienstroosters, rolduidelijkheid en interpersoonlijke relaties.', 2),
('G-PRL-018', 'nl', 'Welke van de volgende is een veelvoorkomend psychosociaal risico in de horeca?', '[{"text":"Onvoldoende verlichting","correct":false},{"text":"Hoge werkdruk, onregelmatige uren, klantagressie en onvoldoende personeel","correct":true},{"text":"Koude opslagtemperaturen","correct":false},{"text":"Voedselallergenen","correct":false}]', 'Horecamedewerkers worden geconfronteerd met hoge psychosociale risico\'s inclusief overmatige werkdruk, onregelmatige en onmaatschappelijke uren, omgaan met moeilijke klanten, baanonzekerheid en vaak onvoldoende ondersteuning.', 3),
('G-PRL-018', 'nl', 'Wat moeten werkgevers implementeren om intimidatie en pesten op de werkplek te voorkomen?', '[{"text":"Niets specifieks is vereist","correct":false},{"text":"Duidelijk anti-intimidatiebeleid, klachtenprocedures en training","correct":true},{"text":"Alleen mondelinge waarschuwingen","correct":false},{"text":"Camera\'s in alle gebieden","correct":false}]', 'Werkgevers moeten gedocumenteerde anti-intimidatieprotocollen hebben die seksuele intimidatie, intimidatie op basis van beschermde kenmerken en pesten dekken, met duidelijke rapportage- en onderzoeksprocedures.', 4),
('G-PRL-018', 'nl', 'Wat zijn tekenen van werkgerelateerde stress die managers moeten herkennen?', '[{"text":"Alleen ziekteverzuim","correct":false},{"text":"Veranderingen in gedrag, stemming, prestaties, verhoogd ziekteverzuim en gezondheidsklachten","correct":true},{"text":"Alleen formele klachten","correct":false},{"text":"Alleen punctualiteitsproblemen","correct":false}]', 'Waarschuwingssignalen zijn onder meer prikkelbaarheid, terugtrekking, prestatievermindering, verhoogde fouten, ziekteverzuim, fysieke klachten (hoofdpijn, vermoeidheid), slaapproblemen en concentratieproblemen.', 5),
('G-PRL-018', 'nl', 'Hoe kunnen werkgevers psychosociale risico\'s in de horeca verminderen?', '[{"text":"Toezicht verhogen","correct":false},{"text":"Zorgen voor redelijke werkdruk, voorspelbare roosters, adequaat personeel en ondersteunend management","correct":true},{"text":"Pauzes verminderen","correct":false},{"text":"Prestatiedruk verhogen","correct":false}]', 'Preventiemaatregelen omvatten redelijke en voorspelbare roosters, adequate personeelsniveaus, duidelijke roldefinities, ondersteunend management, mogelijkheden voor werknemerinbreng en bevordering van werk-privébalans.', 6),
('G-PRL-018', 'nl', 'Wat moeten werknemers doen als ze intimidatie of overmatige stress op de werkplek ervaren?', '[{"text":"Het negeren en hopen dat het verbetert","correct":false},{"text":"Rapporteren via officiële kanalen aan HR, management of werknemersvertegenwoordigers","correct":true},{"text":"Onmiddellijk ontslag nemen","correct":false},{"text":"Alleen met collega\'s bespreken","correct":false}]', 'Werknemers moeten formele rapportagekanalen gebruiken inclusief HR, management, vakbondsvertegenwoordigers of de aangewezen persoon verantwoordelijk voor intimidatieklachten. Alle klachten moeten worden onderzocht.', 7),
('G-PRL-018', 'nl', 'Waarom is het bevorderen van werk-privébalans belangrijk voor psychosociale gezondheid?', '[{"text":"Het is niet belangrijk","correct":false},{"text":"Chronische werk-privé onbalans leidt tot burn-out, gezondheidsproblemen en verminderde prestaties","correct":true},{"text":"Alleen voor productiviteit","correct":false},{"text":"Alleen voor deeltijdwerkers","correct":false}]', 'Aanhoudende werk-privé onbalans veroorzaakt chronische stress, burn-out, relatieproblemen, fysieke en mentale gezondheidsproblemen en vermindert uiteindelijk werkprestaties en verhoogt fouten en ongelukken.', 8),

-- G-PRL-018: Psychosocial Risk Prevention (German)
('G-PRL-018', 'de', 'Was sind psychosoziale Risiken am Arbeitsplatz?', '[{"text":"Nur physische Sicherheitsgefahren","correct":false},{"text":"Arbeitsbedingter Stress, Burnout, Belästigung und Faktoren, die die psychische Gesundheit beeinflussen","correct":true},{"text":"Gerätestörungen","correct":false},{"text":"Nur chemische Expositionen","correct":false}]', 'Psychosoziale Risiken umfassen Arbeitsorganisationsfaktoren, zwischenmenschliche Beziehungen, Arbeitsbelastung, Arbeitsplatzunsicherheit, Belästigung und andere Faktoren, die das psychologische und soziale Wohlbefinden der Arbeiter beeinflussen.', 1),
('G-PRL-018', 'de', 'Müssen psychosoziale Risiken in Arbeitsplatzrisikobewertungen einbezogen werden?', '[{"text":"Nein, nur physische Risiken müssen bewertet werden","correct":false},{"text":"Ja, psychosoziale Risiken müssen als Teil der umfassenden Risikobewertung bewertet werden","correct":true},{"text":"Nur in großen Unternehmen","correct":false},{"text":"Nur wenn Arbeiter sich beschweren","correct":false}]', 'Ley 31/1995 verlangt Bewertung ALLER Arbeitsplatzrisiken einschließlich psychosozialer Faktoren wie Arbeitsbelastung, Arbeitstempo, Schichtmuster, Rollenklarheit und zwischenmenschliche Beziehungen.', 2),
('G-PRL-018', 'de', 'Welches der folgenden ist ein häufiges psychosoziales Risiko in der Gastronomie?', '[{"text":"Unzureichende Beleuchtung","correct":false},{"text":"Hohe Arbeitsbelastung, unregelmäßige Stunden, Kundenaggression und unzureichende Personalbesetzung","correct":true},{"text":"Kalte Lagertemperaturen","correct":false},{"text":"Lebensmittelallergene","correct":false}]', 'Gastronomiearbeiter sind hohen psychosozialen Risiken ausgesetzt, einschließlich übermäßiger Arbeitsbelastung, unregelmäßiger und unsozialer Stunden, Umgang mit schwierigen Kunden, Arbeitsplatzunsicherheit und oft unzureichender Unterstützung.', 3),
('G-PRL-018', 'de', 'Was müssen Arbeitgeber implementieren, um Belästigung und Mobbing am Arbeitsplatz zu verhindern?', '[{"text":"Nichts Spezifisches ist erforderlich","correct":false},{"text":"Klare Anti-Belästigungsrichtlinien, Beschwerdeverfahren und Schulungen","correct":true},{"text":"Nur mündliche Warnungen","correct":false},{"text":"Kameras in allen Bereichen","correct":false}]', 'Arbeitgeber müssen dokumentierte Anti-Belästigungsprotokolle haben, die sexuelle Belästigung, Belästigung aufgrund geschützter Merkmale und Mobbing abdecken, mit klaren Melde- und Untersuchungsverfahren.', 4),
('G-PRL-018', 'de', 'Was sind Anzeichen von arbeitsbedingtem Stress, die Manager erkennen sollten?', '[{"text":"Nur Absentismus","correct":false},{"text":"Verhaltensänderungen, Stimmung, Leistung, erhöhter Absentismus und Gesundheitsbeschwerden","correct":true},{"text":"Nur formelle Beschwerden","correct":false},{"text":"Nur Pünktlichkeitsprobleme","correct":false}]', 'Warnzeichen umfassen Reizbarkeit, Rückzug, Leistungsabfall, erhöhte Fehler, Absentismus, körperliche Beschwerden (Kopfschmerzen, Müdigkeit), Schlafprobleme und Konzentrationsschwierigkeiten.', 5),
('G-PRL-018', 'de', 'Wie können Arbeitgeber psychosoziale Risiken in der Gastronomie reduzieren?', '[{"text":"Überwachung erhöhen","correct":false},{"text":"Angemessene Arbeitsbelastung, vorhersehbare Dienstpläne, angemessene Personalbesetzung und unterstützendes Management sicherstellen","correct":true},{"text":"Pausen reduzieren","correct":false},{"text":"Leistungsdruck erhöhen","correct":false}]', 'Präventionsmaßnahmen umfassen angemessene und vorhersehbare Dienstpläne, angemessene Personalstärken, klare Rollendefinitionen, unterstützendes Management, Möglichkeiten für Arbeitnehmerbeiträge und Förderung der Work-Life-Balance.', 6),
('G-PRL-018', 'de', 'Was sollten Arbeiter tun, wenn sie Belästigung am Arbeitsplatz oder übermäßigen Stress erleben?', '[{"text":"Ignorieren und hoffen, dass es sich verbessert","correct":false},{"text":"Über offizielle Kanäle an HR, Management oder Arbeitnehmervertreter melden","correct":true},{"text":"Sofort kündigen","correct":false},{"text":"Nur mit Kollegen besprechen","correct":false}]', 'Arbeiter sollten formelle Meldekanäle verwenden, einschließlich HR, Management, Gewerkschaftsvertreter oder der benannten Person, die für Belästigungsbeschwerden verantwortlich ist. Alle Beschwerden müssen untersucht werden.', 7),
('G-PRL-018', 'de', 'Warum ist die Förderung der Work-Life-Balance wichtig für psychosoziale Gesundheit?', '[{"text":"Es ist nicht wichtig","correct":false},{"text":"Chronische Work-Life-Unausgeglichenheit führt zu Burnout, Gesundheitsproblemen und reduzierter Leistung","correct":true},{"text":"Nur für Produktivität","correct":false},{"text":"Nur für Teilzeitarbeiter","correct":false}]', 'Anhaltende Work-Life-Unausgeglichenheit verursacht chronischen Stress, Burnout, Beziehungsprobleme, körperliche und psychische Gesundheitsprobleme und reduziert letztendlich Arbeitsleistung und erhöht Fehler und Unfälle.', 8);
