-- Training test questions for PRL guides (G-PRL-010 through G-PRL-018)
-- 9 guides × 8 questions × 4 languages = 288 rows

-- G-PRL-010: Thermal Stress Prevention (English)
INSERT INTO training_test_questions (guide_code, language, question, options, explanation, sort_order) VALUES
('G-PRL-010', 'en', 'What is the primary cause of thermal stress in kitchen environments?', '[{"text":"Inadequate air conditioning","correct":false},{"text":"High ambient temperatures combined with heat-generating equipment","correct":true},{"text":"Insufficient breaks","correct":false},{"text":"Heavy workload","correct":false}]', 'Kitchen environments reach extreme temperatures due to ovens, stoves, and grills operating simultaneously in enclosed spaces. Adequate ventilation is the primary preventive measure.', 1),
('G-PRL-010', 'en', 'Which of the following is NOT a recommended measure to prevent thermal stress?', '[{"text":"Provide free access to drinking water","correct":false},{"text":"Rotate staff between hot and cool areas","correct":false},{"text":"Increase shift length to reduce staffing needs","correct":true},{"text":"Ensure adequate ventilation","correct":false}]', 'Increasing shift length would worsen thermal stress exposure. Shorter shifts or more frequent rotation are recommended instead.', 2),
('G-PRL-010', 'en', 'According to RD 486/1997, what must be provided to kitchen staff working in high-temperature environments?', '[{"text":"Air-conditioned uniforms","correct":false},{"text":"Free access to drinking water","correct":true},{"text":"Reduced working hours","correct":false},{"text":"Temperature bonuses","correct":false}]', 'Employers must provide free, constant access to drinking water to prevent dehydration in high-temperature work environments.', 3),
('G-PRL-010', 'en', 'What are early symptoms of heat stress that staff should monitor for?', '[{"text":"Increased appetite and energy","correct":false},{"text":"Dizziness, excessive sweating, nausea, and fatigue","correct":true},{"text":"Cold hands and feet","correct":false},{"text":"Improved concentration","correct":false}]', 'Heat stress symptoms include dizziness, heavy sweating, nausea, weakness, and confusion. Staff experiencing these should move to a cool area and hydrate immediately.', 4),
('G-PRL-010', 'en', 'What type of clothing is recommended for kitchen staff to help manage thermal stress?', '[{"text":"Heavy cotton uniforms for protection","correct":false},{"text":"Breathable, moisture-wicking fabrics","correct":true},{"text":"Synthetic materials that retain heat","correct":false},{"text":"Multiple layers for insulation","correct":false}]', 'Breathable fabrics allow air circulation and moisture evaporation, helping regulate body temperature in hot environments.', 5),
('G-PRL-010', 'en', 'How should work be organized to minimize thermal stress in kitchens?', '[{"text":"Assign all hot station work to the same person","correct":false},{"text":"Rotate staff between hot and cool workstations","correct":true},{"text":"Schedule all cooking tasks consecutively","correct":false},{"text":"Minimize breaks to complete work faster","correct":false}]', 'Job rotation between hot stations (grill, fryer) and cooler areas (prep, plating) reduces continuous exposure to extreme heat.', 6),
('G-PRL-010', 'en', 'When should additional breaks be provided to kitchen staff?', '[{"text":"Only during official heat waves","correct":false},{"text":"When staff request them","correct":false},{"text":"During periods of extreme heat or heavy workload","correct":true},{"text":"Never, regular breaks are sufficient","correct":false}]', 'During extreme heat conditions or peak service periods, additional short breaks help prevent heat exhaustion and maintain performance.', 7),
('G-PRL-010', 'en', 'What is the employer\'s responsibility regarding ventilation in kitchen areas?', '[{"text":"Provide fans for staff to use personally","correct":false},{"text":"Ensure adequate mechanical ventilation and extraction systems","correct":true},{"text":"Open windows during service","correct":false},{"text":"No specific requirements exist","correct":false}]', 'RD 486/1997 requires employers to ensure adequate ventilation through properly designed and maintained mechanical extraction systems, not just basic air movement.', 8),

-- G-PRL-010: Thermal Stress Prevention (Spanish)
('G-PRL-010', 'es', '¿Cuál es la causa principal del estrés térmico en cocinas?', '[{"text":"Aire acondicionado inadecuado","correct":false},{"text":"Altas temperaturas ambientales combinadas con equipos generadores de calor","correct":true},{"text":"Descansos insuficientes","correct":false},{"text":"Carga de trabajo pesada","correct":false}]', 'Los entornos de cocina alcanzan temperaturas extremas debido a hornos, fogones y parrillas operando simultáneamente en espacios cerrados. La ventilación adecuada es la medida preventiva principal.', 1),
('G-PRL-010', 'es', '¿Cuál de las siguientes NO es una medida recomendada para prevenir el estrés térmico?', '[{"text":"Proporcionar acceso libre a agua potable","correct":false},{"text":"Rotar al personal entre áreas calientes y frescas","correct":false},{"text":"Aumentar la duración de los turnos para reducir necesidades de personal","correct":true},{"text":"Asegurar ventilación adecuada","correct":false}]', 'Aumentar la duración del turno empeoraría la exposición al estrés térmico. Se recomiendan turnos más cortos o rotación más frecuente.', 2),
('G-PRL-010', 'es', 'Según el RD 486/1997, ¿qué debe proporcionarse al personal de cocina que trabaja en ambientes de alta temperatura?', '[{"text":"Uniformes climatizados","correct":false},{"text":"Acceso libre a agua potable","correct":true},{"text":"Jornada reducida","correct":false},{"text":"Plus de temperatura","correct":false}]', 'Los empleadores deben proporcionar acceso libre y constante a agua potable para prevenir la deshidratación en ambientes de trabajo de alta temperatura.', 3),
('G-PRL-010', 'es', '¿Cuáles son los síntomas tempranos de estrés por calor que el personal debe vigilar?', '[{"text":"Mayor apetito y energía","correct":false},{"text":"Mareos, sudoración excesiva, náuseas y fatiga","correct":true},{"text":"Manos y pies fríos","correct":false},{"text":"Mejor concentración","correct":false}]', 'Los síntomas de estrés por calor incluyen mareos, sudoración abundante, náuseas, debilidad y confusión. El personal que los experimente debe moverse a un área fresca e hidratarse inmediatamente.', 4),
('G-PRL-010', 'es', '¿Qué tipo de ropa se recomienda para el personal de cocina para ayudar a manejar el estrés térmico?', '[{"text":"Uniformes de algodón pesado para protección","correct":false},{"text":"Tejidos transpirables que absorben la humedad","correct":true},{"text":"Materiales sintéticos que retienen el calor","correct":false},{"text":"Múltiples capas para aislamiento","correct":false}]', 'Los tejidos transpirables permiten la circulación de aire y la evaporación de humedad, ayudando a regular la temperatura corporal en ambientes calurosos.', 5),
('G-PRL-010', 'es', '¿Cómo debe organizarse el trabajo para minimizar el estrés térmico en cocinas?', '[{"text":"Asignar todo el trabajo de estaciones calientes a la misma persona","correct":false},{"text":"Rotar al personal entre estaciones calientes y frescas","correct":true},{"text":"Programar todas las tareas de cocción consecutivamente","correct":false},{"text":"Minimizar descansos para completar el trabajo más rápido","correct":false}]', 'La rotación de tareas entre estaciones calientes (parrilla, freidora) y áreas más frescas (preparación, emplatado) reduce la exposición continua al calor extremo.', 6),
('G-PRL-010', 'es', '¿Cuándo deben proporcionarse descansos adicionales al personal de cocina?', '[{"text":"Solo durante olas de calor oficiales","correct":false},{"text":"Cuando el personal los solicite","correct":false},{"text":"Durante períodos de calor extremo o carga de trabajo intensa","correct":true},{"text":"Nunca, los descansos regulares son suficientes","correct":false}]', 'Durante condiciones de calor extremo o períodos pico de servicio, los descansos adicionales cortos ayudan a prevenir el agotamiento por calor y mantener el rendimiento.', 7),
('G-PRL-010', 'es', '¿Cuál es la responsabilidad del empleador respecto a la ventilación en áreas de cocina?', '[{"text":"Proporcionar ventiladores para uso personal del personal","correct":false},{"text":"Asegurar ventilación mecánica y sistemas de extracción adecuados","correct":true},{"text":"Abrir ventanas durante el servicio","correct":false},{"text":"No existen requisitos específicos","correct":false}]', 'El RD 486/1997 requiere que los empleadores aseguren ventilación adecuada mediante sistemas de extracción mecánica diseñados y mantenidos apropiadamente, no solo movimiento básico de aire.', 8),

-- G-PRL-010: Thermal Stress Prevention (Dutch)
('G-PRL-010', 'nl', 'Wat is de primaire oorzaak van thermische stress in keukenomgevingen?', '[{"text":"Onvoldoende airconditioning","correct":false},{"text":"Hoge omgevingstemperaturen gecombineerd met warmte-producerende apparatuur","correct":true},{"text":"Onvoldoende pauzes","correct":false},{"text":"Zware werkdruk","correct":false}]', 'Keukenomgevingen bereiken extreme temperaturen door ovens, fornuizen en grills die gelijktijdig in gesloten ruimtes werken. Adequate ventilatie is de primaire preventieve maatregel.', 1),
('G-PRL-010', 'nl', 'Welke van de volgende is GEEN aanbevolen maatregel om thermische stress te voorkomen?', '[{"text":"Gratis toegang tot drinkwater bieden","correct":false},{"text":"Personeel rouleren tussen warme en koele gebieden","correct":false},{"text":"Dienstlengte verhogen om personeelsbehoeften te verminderen","correct":true},{"text":"Zorgen voor adequate ventilatie","correct":false}]', 'Het verlengen van diensten zou thermische stress blootstelling verergeren. Kortere diensten of frequentere rotatie worden in plaats daarvan aanbevolen.', 2),
('G-PRL-010', 'nl', 'Volgens RD 486/1997, wat moet worden verstrekt aan keukenpersoneel dat werkt in hoge-temperatuur omgevingen?', '[{"text":"Geklimatiseerde uniformen","correct":false},{"text":"Gratis toegang tot drinkwater","correct":true},{"text":"Verminderde werktijden","correct":false},{"text":"Temperatuurbonussen","correct":false}]', 'Werkgevers moeten gratis, constante toegang tot drinkwater bieden om dehydratie in hoge-temperatuur werkomgevingen te voorkomen.', 3),
('G-PRL-010', 'nl', 'Wat zijn vroege symptomen van hittestress waar personeel op moet letten?', '[{"text":"Verhoogde eetlust en energie","correct":false},{"text":"Duizeligheid, overmatig zweten, misselijkheid en vermoeidheid","correct":true},{"text":"Koude handen en voeten","correct":false},{"text":"Verbeterde concentratie","correct":false}]', 'Hittestress symptomen omvatten duizeligheid, hevig zweten, misselijkheid, zwakte en verwarring. Personeel dat deze ervaart moet naar een koele plek gaan en onmiddellijk hydrateren.', 4),
('G-PRL-010', 'nl', 'Welk type kleding wordt aanbevolen voor keukenpersoneel om thermische stress te helpen beheersen?', '[{"text":"Zware katoenen uniformen voor bescherming","correct":false},{"text":"Ademende, vocht-afvoerende stoffen","correct":true},{"text":"Synthetische materialen die warmte vasthouden","correct":false},{"text":"Meerdere lagen voor isolatie","correct":false}]', 'Ademende stoffen zorgen voor luchtcirculatie en vochtafgifte, wat helpt bij het reguleren van lichaamstemperatuur in warme omgevingen.', 5),
('G-PRL-010', 'nl', 'Hoe moet werk worden georganiseerd om thermische stress in keukens te minimaliseren?', '[{"text":"Al het werk aan warme stations aan dezelfde persoon toewijzen","correct":false},{"text":"Personeel rouleren tussen warme en koele werkstations","correct":true},{"text":"Alle kooktaken achter elkaar plannen","correct":false},{"text":"Pauzes minimaliseren om werk sneller af te ronden","correct":false}]', 'Taakrotatie tussen warme stations (grill, friteuse) en koelere gebieden (voorbereiding, opmaken) vermindert continue blootstelling aan extreme hitte.', 6),
('G-PRL-010', 'nl', 'Wanneer moeten extra pauzes worden gegeven aan keukenpersoneel?', '[{"text":"Alleen tijdens officiële hittegolven","correct":false},{"text":"Wanneer personeel erom vraagt","correct":false},{"text":"Tijdens periodes van extreme hitte of zware werkdruk","correct":true},{"text":"Nooit, reguliere pauzes zijn voldoende","correct":false}]', 'Tijdens extreme hitteomstandigheden of piekperiodes helpen extra korte pauzes hitte-uitputting te voorkomen en prestaties te behouden.', 7),
('G-PRL-010', 'nl', 'Wat is de verantwoordelijkheid van de werkgever met betrekking tot ventilatie in keukengebieden?', '[{"text":"Ventilatoren verstrekken voor persoonlijk gebruik van personeel","correct":false},{"text":"Zorgen voor adequate mechanische ventilatie en afzuigsystemen","correct":true},{"text":"Ramen openen tijdens service","correct":false},{"text":"Er bestaan geen specifieke vereisten","correct":false}]', 'RD 486/1997 vereist dat werkgevers adequate ventilatie waarborgen via goed ontworpen en onderhouden mechanische afzuigsystemen, niet alleen basale luchtbeweging.', 8),

-- G-PRL-010: Thermal Stress Prevention (German)
('G-PRL-010', 'de', 'Was ist die Hauptursache für thermischen Stress in Küchenumgebungen?', '[{"text":"Unzureichende Klimaanlage","correct":false},{"text":"Hohe Umgebungstemperaturen kombiniert mit wärmeerzeugende Geräte","correct":true},{"text":"Unzureichende Pausen","correct":false},{"text":"Schwere Arbeitsbelastung","correct":false}]', 'Küchenumgebungen erreichen extreme Temperaturen durch Öfen, Herde und Grills, die gleichzeitig in geschlossenen Räumen betrieben werden. Angemessene Belüftung ist die primäre Präventionsmaßnahme.', 1),
('G-PRL-010', 'de', 'Welche der folgenden ist KEINE empfohlene Maßnahme zur Verhinderung von thermischem Stress?', '[{"text":"Freien Zugang zu Trinkwasser bieten","correct":false},{"text":"Personal zwischen heißen und kühlen Bereichen rotieren","correct":false},{"text":"Schichtlänge erhöhen, um Personalbedarf zu reduzieren","correct":true},{"text":"Angemessene Belüftung sicherstellen","correct":false}]', 'Die Verlängerung der Schichtlänge würde die thermische Stressbelastung verschlimmern. Kürzere Schichten oder häufigere Rotation werden stattdessen empfohlen.', 2),
('G-PRL-010', 'de', 'Gemäß RD 486/1997, was muss Küchenpersonal bereitgestellt werden, das in Hochtemperaturumgebungen arbeitet?', '[{"text":"Klimatisierte Uniformen","correct":false},{"text":"Freier Zugang zu Trinkwasser","correct":true},{"text":"Reduzierte Arbeitszeiten","correct":false},{"text":"Temperaturboni","correct":false}]', 'Arbeitgeber müssen freien, ständigen Zugang zu Trinkwasser bieten, um Dehydrierung in Hochtemperatur-Arbeitsumgebungen zu verhindern.', 3),
('G-PRL-010', 'de', 'Was sind frühe Symptome von Hitzestress, auf die Personal achten sollte?', '[{"text":"Erhöhter Appetit und Energie","correct":false},{"text":"Schwindel, übermäßiges Schwitzen, Übelkeit und Müdigkeit","correct":true},{"text":"Kalte Hände und Füße","correct":false},{"text":"Verbesserte Konzentration","correct":false}]', 'Hitzestress-Symptome umfassen Schwindel, starkes Schwitzen, Übelkeit, Schwäche und Verwirrung. Personal, das diese erfährt, sollte sich an einen kühlen Ort begeben und sofort hydratisieren.', 4),
('G-PRL-010', 'de', 'Welche Art von Kleidung wird für Küchenpersonal empfohlen, um thermischen Stress zu bewältigen?', '[{"text":"Schwere Baumwolluniform zum Schutz","correct":false},{"text":"Atmungsaktive, feuchtigkeitsableitende Stoffe","correct":true},{"text":"Synthetische Materialien, die Wärme speichern","correct":false},{"text":"Mehrere Schichten zur Isolierung","correct":false}]', 'Atmungsaktive Stoffe ermöglichen Luftzirkulation und Feuchtigkeitsverdunstung und helfen, die Körpertemperatur in heißen Umgebungen zu regulieren.', 5),
('G-PRL-010', 'de', 'Wie sollte die Arbeit organisiert werden, um thermischen Stress in Küchen zu minimieren?', '[{"text":"Alle Arbeit an heißen Stationen derselben Person zuweisen","correct":false},{"text":"Personal zwischen heißen und kühlen Arbeitsstationen rotieren","correct":true},{"text":"Alle Kochaufgaben nacheinander planen","correct":false},{"text":"Pausen minimieren, um Arbeit schneller zu erledigen","correct":false}]', 'Aufgabenrotation zwischen heißen Stationen (Grill, Friteuse) und kühleren Bereichen (Vorbereitung, Anrichten) reduziert kontinuierliche Exposition gegenüber extremer Hitze.', 6),
('G-PRL-010', 'de', 'Wann sollten zusätzliche Pausen für Küchenpersonal gewährt werden?', '[{"text":"Nur während offizieller Hitzewellen","correct":false},{"text":"Wenn Personal darum bittet","correct":false},{"text":"Während Perioden extremer Hitze oder schwerer Arbeitsbelastung","correct":true},{"text":"Nie, reguläre Pausen sind ausreichend","correct":false}]', 'Während extremen Hitzebedingungen oder Spitzenbetriebszeiten helfen zusätzliche kurze Pausen, Hitzeerschöpfung zu verhindern und Leistung aufrechtzuerhalten.', 7),
('G-PRL-010', 'de', 'Was ist die Verantwortung des Arbeitgebers bezüglich Belüftung in Küchenbereichen?', '[{"text":"Ventilatoren für persönliche Nutzung des Personals bereitstellen","correct":false},{"text":"Angemessene mechanische Belüftung und Absaugsysteme sicherstellen","correct":true},{"text":"Fenster während des Service öffnen","correct":false},{"text":"Es gibt keine spezifischen Anforderungen","correct":false}]', 'RD 486/1997 verlangt von Arbeitgebern, angemessene Belüftung durch ordnungsgemäß entworfene und gewartete mechanische Absaugsysteme sicherzustellen, nicht nur grundlegende Luftbewegung.', 8);

-- G-PRL-011: Noise Exposure (English)
INSERT INTO training_test_questions (guide_code, language, question, options, explanation, sort_order) VALUES
('G-PRL-011', 'en', 'At what decibel level does Spanish law require hearing protection to be provided?', '[{"text":"75 dB","correct":false},{"text":"80 dB","correct":false},{"text":"85 dB","correct":true},{"text":"90 dB","correct":false}]', 'RD 286/2006 mandates that hearing protection must be provided when noise levels reach 85 dB. This is the action level requiring preventive measures.', 1),
('G-PRL-011', 'en', 'Which hospitality environments are most likely to exceed safe noise levels?', '[{"text":"Kitchen prep areas","correct":false},{"text":"Bars with live music and event spaces","correct":true},{"text":"Dining rooms during lunch service","correct":false},{"text":"Storage areas","correct":false}]', 'Bars with live music, DJs, and event spaces commonly exceed 85 dB due to amplified sound. Staff in these areas require hearing protection and exposure monitoring.', 2),
('G-PRL-011', 'en', 'What is the primary health risk of prolonged exposure to high noise levels?', '[{"text":"Temporary headaches","correct":false},{"text":"Permanent hearing loss (noise-induced hearing loss)","correct":true},{"text":"Increased blood pressure only","correct":false},{"text":"Fatigue","correct":false}]', 'Noise-induced hearing loss is permanent and irreversible. Prolonged exposure above 85 dB damages the delicate hair cells in the inner ear.', 3),
('G-PRL-011', 'en', 'According to RD 286/2006, what must employers do if noise levels exceed 85 dB?', '[{"text":"Post warning signs only","correct":false},{"text":"Conduct noise assessments and provide hearing protection","correct":true},{"text":"Reduce staff working hours automatically","correct":false},{"text":"Nothing, it is the employee\'s responsibility","correct":false}]', 'Employers must conduct noise level assessments, provide appropriate hearing protection free of charge, train staff on proper use, and implement exposure reduction measures.', 4),
('G-PRL-011', 'en', 'Where should staff be positioned in relation to loudspeakers to minimize noise exposure?', '[{"text":"Directly in front for better communication","correct":false},{"text":"As far away as operationally possible","correct":true},{"text":"Underneath for better sound distribution","correct":false},{"text":"Position does not matter","correct":false}]', 'Staff workstations should be positioned away from direct speaker lines to reduce exposure. Sound intensity decreases significantly with distance.', 5),
('G-PRL-011', 'en', 'What type of hearing protection should be provided for staff working in loud bar environments?', '[{"text":"Cotton earplugs","correct":false},{"text":"Properly rated earplugs or earmuffs (with appropriate SNR rating)","correct":true},{"text":"Noise-canceling headphones","correct":false},{"text":"No protection needed if exposure is intermittent","correct":false}]', 'Hearing protection must have an appropriate Single Number Rating (SNR) to reduce noise to safe levels. Cotton plugs are ineffective.', 6),
('G-PRL-011', 'en', 'How often should noise level assessments be conducted in hospitality venues?', '[{"text":"Once when opening, never again","correct":false},{"text":"Initially and whenever conditions change significantly","correct":true},{"text":"Every 5 years","correct":false},{"text":"Only if staff complain","correct":false}]', 'Noise assessments must be conducted initially, when layout or sound systems change, and if staff report hearing-related issues.', 7),
('G-PRL-011', 'en', 'Besides hearing protection, what other measure can reduce noise exposure for bar staff?', '[{"text":"Speaking louder","correct":false},{"text":"Rotating staff to limit continuous exposure time","correct":true},{"text":"Playing music at maximum volume","correct":false},{"text":"Working faster to finish shifts early","correct":false}]', 'Job rotation between high-noise and quieter areas limits cumulative exposure. Combined with hearing protection, this provides effective prevention.', 8);

-- G-PRL-011: Noise Exposure (Spanish)
INSERT INTO training_test_questions (guide_code, language, question, options, explanation, sort_order) VALUES
('G-PRL-011', 'es', '¿A qué nivel de decibelios requiere la ley española que se proporcione protección auditiva?', '[{"text":"75 dB","correct":false},{"text":"80 dB","correct":false},{"text":"85 dB","correct":true},{"text":"90 dB","correct":false}]', 'El RD 286/2006 exige que se proporcione protección auditiva cuando los niveles de ruido alcancen 85 dB. Este es el nivel de acción que requiere medidas preventivas.', 1),
('G-PRL-011', 'es', '¿Qué entornos de hostelería tienen más probabilidades de superar los niveles de ruido seguros?', '[{"text":"Áreas de preparación de cocina","correct":false},{"text":"Bares con música en vivo y espacios para eventos","correct":true},{"text":"Comedores durante el servicio de almuerzo","correct":false},{"text":"Áreas de almacenamiento","correct":false}]', 'Los bares con música en vivo, DJs y espacios para eventos comúnmente superan los 85 dB debido al sonido amplificado. El personal en estas áreas requiere protección auditiva y monitoreo de exposición.', 2),
('G-PRL-011', 'es', '¿Cuál es el principal riesgo para la salud de la exposición prolongada a altos niveles de ruido?', '[{"text":"Dolores de cabeza temporales","correct":false},{"text":"Pérdida auditiva permanente (hipoacusia inducida por ruido)","correct":true},{"text":"Presión arterial elevada solamente","correct":false},{"text":"Fatiga","correct":false}]', 'La pérdida auditiva inducida por ruido es permanente e irreversible. La exposición prolongada por encima de 85 dB daña las delicadas células ciliadas del oído interno.', 3),
('G-PRL-011', 'es', 'Según el RD 286/2006, ¿qué deben hacer los empleadores si los niveles de ruido superan los 85 dB?', '[{"text":"Publicar solo señales de advertencia","correct":false},{"text":"Realizar evaluaciones de ruido y proporcionar protección auditiva","correct":true},{"text":"Reducir automáticamente las horas de trabajo del personal","correct":false},{"text":"Nada, es responsabilidad del empleado","correct":false}]', 'Los empleadores deben realizar evaluaciones de nivel de ruido, proporcionar protección auditiva apropiada sin costo, capacitar al personal sobre el uso correcto e implementar medidas de reducción de exposición.', 4),
('G-PRL-011', 'es', '¿Dónde debe posicionarse el personal en relación con los altavoces para minimizar la exposición al ruido?', '[{"text":"Directamente enfrente para mejor comunicación","correct":false},{"text":"Lo más lejos posible operacionalmente","correct":true},{"text":"Debajo para mejor distribución del sonido","correct":false},{"text":"La posición no importa","correct":false}]', 'Las estaciones de trabajo del personal deben posicionarse lejos de las líneas directas de los altavoces para reducir la exposición. La intensidad del sonido disminuye significativamente con la distancia.', 5),
('G-PRL-011', 'es', '¿Qué tipo de protección auditiva debe proporcionarse al personal que trabaja en ambientes de bar ruidosos?', '[{"text":"Tapones de algodón","correct":false},{"text":"Tapones o orejeras con clasificación adecuada (con calificación SNR apropiada)","correct":true},{"text":"Auriculares con cancelación de ruido","correct":false},{"text":"No se necesita protección si la exposición es intermitente","correct":false}]', 'La protección auditiva debe tener una Clasificación de Número Único (SNR) apropiada para reducir el ruido a niveles seguros. Los tapones de algodón son ineficaces.', 6),
('G-PRL-011', 'es', '¿Con qué frecuencia deben realizarse las evaluaciones de nivel de ruido en establecimientos de hostelería?', '[{"text":"Una vez al abrir, nunca más","correct":false},{"text":"Inicialmente y siempre que las condiciones cambien significativamente","correct":true},{"text":"Cada 5 años","correct":false},{"text":"Solo si el personal se queja","correct":false}]', 'Las evaluaciones de ruido deben realizarse inicialmente, cuando cambia el diseño o los sistemas de sonido, y si el personal informa problemas relacionados con la audición.', 7),
('G-PRL-011', 'es', 'Además de la protección auditiva, ¿qué otra medida puede reducir la exposición al ruido para el personal de bar?', '[{"text":"Hablar más alto","correct":false},{"text":"Rotar al personal para limitar el tiempo de exposición continua","correct":true},{"text":"Reproducir música a volumen máximo","correct":false},{"text":"Trabajar más rápido para terminar los turnos temprano","correct":false}]', 'La rotación de tareas entre áreas de alto ruido y más silenciosas limita la exposición acumulativa. Combinado con protección auditiva, esto proporciona prevención efectiva.', 8);

-- G-PRL-011: Noise Exposure (Dutch)
INSERT INTO training_test_questions (guide_code, language, question, options, explanation, sort_order) VALUES
('G-PRL-011', 'nl', 'Bij welk decibelniveau vereist de Spaanse wet dat gehoorbescherming wordt verstrekt?', '[{"text":"75 dB","correct":false},{"text":"80 dB","correct":false},{"text":"85 dB","correct":true},{"text":"90 dB","correct":false}]', 'RD 286/2006 verplicht dat gehoorbescherming moet worden verstrekt wanneer geluidsniveaus 85 dB bereiken. Dit is het actieniveau dat preventieve maatregelen vereist.', 1),
('G-PRL-011', 'nl', 'Welke horeca-omgevingen overschrijden waarschijnlijk veilige geluidsniveaus?', '[{"text":"Keuken voorbereidingsgebieden","correct":false},{"text":"Bars met live muziek en evenementenruimtes","correct":true},{"text":"Eetkamers tijdens lunchservice","correct":false},{"text":"Opslaggebieden","correct":false}]', 'Bars met live muziek, DJ\'s en evenementenruimtes overschrijden vaak 85 dB door versterkt geluid. Personeel in deze gebieden heeft gehoorbescherming en blootstellingsmonitoring nodig.', 2),
('G-PRL-011', 'nl', 'Wat is het primaire gezondheidsrisico van langdurige blootstelling aan hoge geluidsniveaus?', '[{"text":"Tijdelijke hoofdpijn","correct":false},{"text":"Permanent gehoorverlies (lawaai-geïnduceerd gehoorverlies)","correct":true},{"text":"Alleen verhoogde bloeddruk","correct":false},{"text":"Vermoeidheid","correct":false}]', 'Lawaai-geïnduceerd gehoorverlies is permanent en onomkeerbaar. Langdurige blootstelling boven 85 dB beschadigt de delicate haarcellen in het binnenoor.', 3),
('G-PRL-011', 'nl', 'Volgens RD 286/2006, wat moeten werkgevers doen als geluidsniveaus 85 dB overschrijden?', '[{"text":"Alleen waarschuwingsborden plaatsen","correct":false},{"text":"Geluidsbeoordelingen uitvoeren en gehoorbescherming verstrekken","correct":true},{"text":"Werktijden van personeel automatisch verminderen","correct":false},{"text":"Niets, het is de verantwoordelijkheid van de werknemer","correct":false}]', 'Werkgevers moeten geluidsniveaubeoordelingen uitvoeren, passende gehoorbescherming gratis verstrekken, personeel trainen in correct gebruik en blootstellingsreducerende maatregelen implementeren.', 4),
('G-PRL-011', 'nl', 'Waar moet personeel worden gepositioneerd ten opzichte van luidsprekers om geluidsblootstelling te minimaliseren?', '[{"text":"Direct ervoor voor betere communicatie","correct":false},{"text":"Zo ver mogelijk operationeel haalbaar","correct":true},{"text":"Eronder voor betere geluidsdistributie","correct":false},{"text":"Positie maakt niet uit","correct":false}]', 'Werkstations van personeel moeten worden gepositioneerd weg van directe speakerlijnen om blootstelling te verminderen. Geluidsintensiteit neemt aanzienlijk af met afstand.', 5),
('G-PRL-011', 'nl', 'Welk type gehoorbescherming moet worden verstrekt voor personeel dat werkt in luide baromgevingen?', '[{"text":"Katoenen oordoppen","correct":false},{"text":"Correct geclassificeerde oordoppen of oorwarmers (met passende SNR-rating)","correct":true},{"text":"Noise-cancelling koptelefoons","correct":false},{"text":"Geen bescherming nodig als blootstelling intermitterend is","correct":false}]', 'Gehoorbescherming moet een passende Single Number Rating (SNR) hebben om geluid naar veilige niveaus te verminderen. Katoenen doppen zijn ineffectief.', 6),
('G-PRL-011', 'nl', 'Hoe vaak moeten geluidsniveaubeoordelingen worden uitgevoerd in horecagelegenheden?', '[{"text":"Eenmaal bij opening, nooit meer","correct":false},{"text":"Aanvankelijk en wanneer omstandigheden aanzienlijk veranderen","correct":true},{"text":"Elke 5 jaar","correct":false},{"text":"Alleen als personeel klaagt","correct":false}]', 'Geluidsbeoordelingen moeten aanvankelijk worden uitgevoerd, wanneer layout of geluidssystemen veranderen, en als personeel gehoor-gerelateerde problemen meldt.', 7),
('G-PRL-011', 'nl', 'Naast gehoorbescherming, welke andere maatregel kan geluidsblootstelling voor barpersoneel verminderen?', '[{"text":"Harder spreken","correct":false},{"text":"Personeel rouleren om continue blootstellingstijd te beperken","correct":true},{"text":"Muziek op maximaal volume spelen","correct":false},{"text":"Sneller werken om diensten vroeg te beëindigen","correct":false}]', 'Taakrotatie tussen gebieden met veel lawaai en stillere gebieden beperkt cumulatieve blootstelling. Gecombineerd met gehoorbescherming biedt dit effectieve preventie.', 8);

-- G-PRL-011: Noise Exposure (German)
INSERT INTO training_test_questions (guide_code, language, question, options, explanation, sort_order) VALUES
('G-PRL-011', 'de', 'Bei welchem Dezibelpegel verlangt das spanische Gesetz, dass Gehörschutz bereitgestellt wird?', '[{"text":"75 dB","correct":false},{"text":"80 dB","correct":false},{"text":"85 dB","correct":true},{"text":"90 dB","correct":false}]', 'RD 286/2006 schreibt vor, dass Gehörschutz bereitgestellt werden muss, wenn Geräuschpegel 85 dB erreichen. Dies ist der Aktionspegel, der Präventionsmaßnahmen erfordert.', 1),
('G-PRL-011', 'de', 'Welche Gastronomieumgebungen überschreiten wahrscheinlich sichere Geräuschpegel?', '[{"text":"Küchen-Vorbereitungsbereiche","correct":false},{"text":"Bars mit Live-Musik und Veranstaltungsräume","correct":true},{"text":"Speisesäle während des Mittagsservice","correct":false},{"text":"Lagerbereiche","correct":false}]', 'Bars mit Live-Musik, DJs und Veranstaltungsräume überschreiten häufig 85 dB aufgrund verstärkten Klangs. Personal in diesen Bereichen benötigt Gehörschutz und Expositionsüberwachung.', 2),
('G-PRL-011', 'de', 'Was ist das primäre Gesundheitsrisiko längerer Exposition gegenüber hohen Geräuschpegeln?', '[{"text":"Vorübergehende Kopfschmerzen","correct":false},{"text":"Permanenter Hörverlust (lärmbedingter Hörverlust)","correct":true},{"text":"Nur erhöhter Blutdruck","correct":false},{"text":"Müdigkeit","correct":false}]', 'Lärmbedingter Hörverlust ist permanent und irreversibel. Längere Exposition über 85 dB schädigt die empfindlichen Haarzellen im Innenohr.', 3),
('G-PRL-011', 'de', 'Gemäß RD 286/2006, was müssen Arbeitgeber tun, wenn Geräuschpegel 85 dB überschreiten?', '[{"text":"Nur Warnschilder anbringen","correct":false},{"text":"Geräuschbewertungen durchführen und Gehörschutz bereitstellen","correct":true},{"text":"Arbeitszeiten des Personals automatisch reduzieren","correct":false},{"text":"Nichts, es ist die Verantwortung des Arbeitnehmers","correct":false}]', 'Arbeitgeber müssen Geräuschpegelbewertungen durchführen, angemessenen Gehörschutz kostenlos bereitstellen, Personal in korrekter Nutzung schulen und expositionsmindernde Maßnahmen implementieren.', 4),
('G-PRL-011', 'de', 'Wo sollte Personal in Bezug auf Lautsprecher positioniert werden, um Geräuschexposition zu minimieren?', '[{"text":"Direkt davor für bessere Kommunikation","correct":false},{"text":"So weit wie operativ möglich entfernt","correct":true},{"text":"Darunter für bessere Klangverteilung","correct":false},{"text":"Position spielt keine Rolle","correct":false}]', 'Arbeitsstationen des Personals sollten von direkten Lautsprecherlinien entfernt positioniert werden, um Exposition zu reduzieren. Klangintensität nimmt mit Entfernung deutlich ab.', 5),
('G-PRL-011', 'de', 'Welche Art von Gehörschutz sollte für Personal bereitgestellt werden, das in lauten Barumgebungen arbeitet?', '[{"text":"Baumwoll-Ohrstöpsel","correct":false},{"text":"Ordnungsgemäß bewertete Ohrstöpsel oder Ohrenschützer (mit angemessenem SNR-Rating)","correct":true},{"text":"Geräuschunterdrückende Kopfhörer","correct":false},{"text":"Kein Schutz erforderlich, wenn Exposition intermittierend ist","correct":false}]', 'Gehörschutz muss eine angemessene Single Number Rating (SNR) haben, um Geräusch auf sichere Pegel zu reduzieren. Baumwollstöpsel sind ineffektiv.', 6),
('G-PRL-011', 'de', 'Wie oft sollten Geräuschpegelbewertungen in Gastronomiebetrieben durchgeführt werden?', '[{"text":"Einmal bei Eröffnung, nie wieder","correct":false},{"text":"Anfänglich und wann immer sich Bedingungen wesentlich ändern","correct":true},{"text":"Alle 5 Jahre","correct":false},{"text":"Nur wenn Personal sich beschwert","correct":false}]', 'Geräuschbewertungen müssen anfänglich durchgeführt werden, wenn sich Layout oder Soundsysteme ändern, und wenn Personal hör-bezogene Probleme meldet.', 7),
('G-PRL-011', 'de', 'Neben Gehörschutz, welche andere Maßnahme kann Geräuschexposition für Barpersonal reduzieren?', '[{"text":"Lauter sprechen","correct":false},{"text":"Personal rotieren, um kontinuierliche Expositionszeit zu begrenzen","correct":true},{"text":"Musik auf maximaler Lautstärke spielen","correct":false},{"text":"Schneller arbeiten, um Schichten früh zu beenden","correct":false}]', 'Aufgabenrotation zwischen hochlärmigen und ruhigeren Bereichen begrenzt kumulative Exposition. Kombiniert mit Gehörschutz bietet dies effektive Prävention.', 8);

-- G-PRL-012: Electrical Safety (English)
INSERT INTO training_test_questions (guide_code, language, question, options, explanation, sort_order) VALUES
('G-PRL-012', 'en', 'What is the most important rule when dealing with damaged electrical equipment?', '[{"text":"Try to repair it yourself","correct":false},{"text":"Never use it and report it immediately","correct":true},{"text":"Use it carefully","correct":false},{"text":"Unplug and replug to reset","correct":false}]', 'Damaged electrical equipment poses serious shock and fire risks. It must be tagged out of service and reported immediately to maintenance or management.', 1),
('G-PRL-012', 'en', 'According to RD 614/2001, who is authorized to perform electrical repairs in the workplace?', '[{"text":"Any experienced staff member","correct":false},{"text":"Only qualified and certified electricians","correct":true},{"text":"The maintenance manager","correct":false},{"text":"Anyone with basic tools","correct":false}]', 'Only qualified electricians with proper certification may perform electrical work. Unauthorized repairs can result in electrocution, fire, and legal liability.', 2),
('G-PRL-012', 'en', 'What is the primary hazard when water and electricity come into contact in a kitchen?', '[{"text":"Equipment damage","correct":false},{"text":"Electric shock or electrocution","correct":true},{"text":"Water contamination","correct":false},{"text":"Noise from sparking","correct":false}]', 'Water conducts electricity and dramatically increases the risk of severe or fatal electric shock. Kitchen environments require special attention to keeping water away from electrical outlets and equipment.', 3),
('G-PRL-012', 'en', 'Before cleaning electrical equipment, what is the essential first step?', '[{"text":"Spray it with water","correct":false},{"text":"Unplug it from the power source","correct":true},{"text":"Turn it off with the switch","correct":false},{"text":"Put on rubber gloves","correct":false}]', 'Equipment must be completely disconnected from power before cleaning. Simply turning it off is not sufficient—the plug must be removed to eliminate all electrical hazards.', 4),
('G-PRL-012', 'en', 'What should you check regularly on electrical equipment to prevent hazards?', '[{"text":"The manufacturer warranty","correct":false},{"text":"Plugs, cables, and visible damage","correct":true},{"text":"The equipment serial number","correct":false},{"text":"The paint condition","correct":false}]', 'Regular visual inspection of plugs, cables, and equipment housing can identify frayed wires, exposed conductors, or damage before they cause injury or fire.', 5),
('G-PRL-012', 'en', 'Where should you locate the main electrical shut-off switch in your workplace?', '[{"text":"It is not necessary to know","correct":false},{"text":"Every staff member should know its location","correct":true},{"text":"Only electricians need to know","correct":false},{"text":"In the manager\'s office","correct":false}]', 'In an electrical emergency (shock, fire, sparking), the main switch must be turned off immediately. All staff should know its location and how to operate it safely.', 6),
('G-PRL-012', 'en', 'What is the danger of overloading electrical outlets with multiple devices?', '[{"text":"Higher electricity bills","correct":false},{"text":"Overheating, fire risk, and circuit failure","correct":true},{"text":"Slower equipment operation","correct":false},{"text":"Equipment warranty void","correct":false}]', 'Overloaded circuits overheat, damage insulation, and can ignite fires. Use appropriate power distribution and never daisy-chain extension cords or power strips.', 7),
('G-PRL-012', 'en', 'What type of environment increases electrical hazards in hospitality settings?', '[{"text":"Air-conditioned spaces","correct":false},{"text":"Wet or humid environments like kitchens and bars","correct":true},{"text":"Well-lit areas","correct":false},{"text":"Carpeted floors","correct":false}]', 'Moisture dramatically increases electrical conductivity and shock risk. Kitchens, bars, and dishwashing areas require waterproof electrical installations and constant vigilance.', 8);

-- G-PRL-012: Electrical Safety (Spanish)
INSERT INTO training_test_questions (guide_code, language, question, options, explanation, sort_order) VALUES
('G-PRL-012', 'es', '¿Cuál es la regla más importante al tratar con equipos eléctricos dañados?', '[{"text":"Intentar repararlo uno mismo","correct":false},{"text":"Nunca usarlo e informarlo inmediatamente","correct":true},{"text":"Usarlo con cuidado","correct":false},{"text":"Desenchufar y volver a enchufar para reiniciar","correct":false}]', 'Los equipos eléctricos dañados presentan graves riesgos de descarga e incendio. Deben etiquetarse fuera de servicio e informarse inmediatamente al mantenimiento o la gerencia.', 1),
('G-PRL-012', 'es', 'Según el RD 614/2001, ¿quién está autorizado para realizar reparaciones eléctricas en el lugar de trabajo?', '[{"text":"Cualquier miembro del personal con experiencia","correct":false},{"text":"Solo electricistas cualificados y certificados","correct":true},{"text":"El gerente de mantenimiento","correct":false},{"text":"Cualquiera con herramientas básicas","correct":false}]', 'Solo electricistas cualificados con certificación adecuada pueden realizar trabajos eléctricos. Las reparaciones no autorizadas pueden resultar en electrocución, incendio y responsabilidad legal.', 2),
('G-PRL-012', 'es', '¿Cuál es el peligro principal cuando el agua y la electricidad entran en contacto en una cocina?', '[{"text":"Daño al equipo","correct":false},{"text":"Descarga eléctrica o electrocución","correct":true},{"text":"Contaminación del agua","correct":false},{"text":"Ruido por chispas","correct":false}]', 'El agua conduce electricidad y aumenta dramáticamente el riesgo de descarga eléctrica grave o fatal. Los entornos de cocina requieren atención especial para mantener el agua alejada de enchufes y equipos eléctricos.', 3),
('G-PRL-012', 'es', 'Antes de limpiar equipos eléctricos, ¿cuál es el primer paso esencial?', '[{"text":"Rociarlo con agua","correct":false},{"text":"Desenchufarlo de la fuente de alimentación","correct":true},{"text":"Apagarlo con el interruptor","correct":false},{"text":"Ponerse guantes de goma","correct":false}]', 'El equipo debe estar completamente desconectado de la alimentación antes de limpiar. Simplemente apagarlo no es suficiente: el enchufe debe retirarse para eliminar todos los peligros eléctricos.', 4),
('G-PRL-012', 'es', '¿Qué debe verificar regularmente en el equipo eléctrico para prevenir peligros?', '[{"text":"La garantía del fabricante","correct":false},{"text":"Enchufes, cables y daños visibles","correct":true},{"text":"El número de serie del equipo","correct":false},{"text":"El estado de la pintura","correct":false}]', 'La inspección visual regular de enchufes, cables y carcasa del equipo puede identificar cables desgastados, conductores expuestos o daños antes de que causen lesiones o incendio.', 5),
('G-PRL-012', 'es', '¿Dónde debe ubicar el interruptor principal de apagado eléctrico en su lugar de trabajo?', '[{"text":"No es necesario saberlo","correct":false},{"text":"Cada miembro del personal debe conocer su ubicación","correct":true},{"text":"Solo los electricistas necesitan saberlo","correct":false},{"text":"En la oficina del gerente","correct":false}]', 'En una emergencia eléctrica (descarga, incendio, chispas), el interruptor principal debe apagarse inmediatamente. Todo el personal debe conocer su ubicación y cómo operarlo de manera segura.', 6),
('G-PRL-012', 'es', '¿Cuál es el peligro de sobrecargar los enchufes eléctricos con múltiples dispositivos?', '[{"text":"Facturas de electricidad más altas","correct":false},{"text":"Sobrecalentamiento, riesgo de incendio y falla del circuito","correct":true},{"text":"Operación más lenta del equipo","correct":false},{"text":"Anulación de garantía del equipo","correct":false}]', 'Los circuitos sobrecargados se sobrecalientan, dañan el aislamiento y pueden iniciar incendios. Use distribución de energía apropiada y nunca encadene cables de extensión o regletas.', 7),
('G-PRL-012', 'es', '¿Qué tipo de entorno aumenta los peligros eléctricos en entornos de hostelería?', '[{"text":"Espacios con aire acondicionado","correct":false},{"text":"Ambientes húmedos o mojados como cocinas y bares","correct":true},{"text":"Áreas bien iluminadas","correct":false},{"text":"Pisos alfombrados","correct":false}]', 'La humedad aumenta dramáticamente la conductividad eléctrica y el riesgo de descarga. Cocinas, bares y áreas de lavado de platos requieren instalaciones eléctricas a prueba de agua y vigilancia constante.', 8);

-- G-PRL-012: Electrical Safety (Dutch)
INSERT INTO training_test_questions (guide_code, language, question, options, explanation, sort_order) VALUES
('G-PRL-012', 'nl', 'Wat is de belangrijkste regel bij het omgaan met beschadigde elektrische apparatuur?', '[{"text":"Probeer het zelf te repareren","correct":false},{"text":"Gebruik het nooit en meld het onmiddellijk","correct":true},{"text":"Gebruik het voorzichtig","correct":false},{"text":"Ontkoppelen en opnieuw aansluiten om te resetten","correct":false}]', 'Beschadigde elektrische apparatuur vormt ernstige schok- en brandrisico\'s. Het moet worden gelabeld als buiten gebruik en onmiddellijk worden gemeld aan onderhoud of management.', 1),
('G-PRL-012', 'nl', 'Volgens RD 614/2001, wie is bevoegd om elektrische reparaties op de werkplek uit te voeren?', '[{"text":"Elk ervaren personeelslid","correct":false},{"text":"Alleen gekwalificeerde en gecertificeerde elektriciens","correct":true},{"text":"De onderhoudsmanager","correct":false},{"text":"Iedereen met basisgereedschap","correct":false}]', 'Alleen gekwalificeerde elektriciens met de juiste certificering mogen elektrisch werk uitvoeren. Ongeautoriseerde reparaties kunnen leiden tot elektrocutie, brand en juridische aansprakelijkheid.', 2),
('G-PRL-012', 'nl', 'Wat is het primaire gevaar wanneer water en elektriciteit in contact komen in een keuken?', '[{"text":"Schade aan apparatuur","correct":false},{"text":"Elektrische schok of elektrocutie","correct":true},{"text":"Waterverontreiniging","correct":false},{"text":"Geluid van vonken","correct":false}]', 'Water geleidt elektriciteit en verhoogt het risico op ernstige of fatale elektrische schok dramatisch. Keukenomgevingen vereisen speciale aandacht om water weg te houden van elektrische stopcontacten en apparatuur.', 3),
('G-PRL-012', 'nl', 'Voordat u elektrische apparatuur schoonmaakt, wat is de essentiële eerste stap?', '[{"text":"Spuit het met water","correct":false},{"text":"Haal de stekker uit het stopcontact","correct":true},{"text":"Schakel het uit met de schakelaar","correct":false},{"text":"Trek rubberen handschoenen aan","correct":false}]', 'Apparatuur moet volledig losgekoppeld zijn van stroom voordat u schoonmaakt. Simpelweg uitschakelen is niet voldoende—de stekker moet worden verwijderd om alle elektrische gevaren te elimineren.', 4),
('G-PRL-012', 'nl', 'Wat moet u regelmatig controleren op elektrische apparatuur om gevaren te voorkomen?', '[{"text":"De fabrieksgarantie","correct":false},{"text":"Stekkers, kabels en zichtbare schade","correct":true},{"text":"Het serienummer van de apparatuur","correct":false},{"text":"De verfconditie","correct":false}]', 'Regelmatige visuele inspectie van stekkers, kabels en behuizing van apparatuur kan gerafelde draden, blootgestelde geleiders of schade identificeren voordat ze letsel of brand veroorzaken.', 5),
('G-PRL-012', 'nl', 'Waar moet u de hoofd elektrische uitschakelaar op uw werkplek lokaliseren?', '[{"text":"Het is niet nodig om te weten","correct":false},{"text":"Elk personeelslid moet de locatie kennen","correct":true},{"text":"Alleen elektriciens moeten het weten","correct":false},{"text":"In het kantoor van de manager","correct":false}]', 'In een elektrische noodsituatie (schok, brand, vonken) moet de hoofdschakelaar onmiddellijk worden uitgeschakeld. Alle personeelsleden moeten de locatie kennen en hoe het veilig te bedienen.', 6),
('G-PRL-012', 'nl', 'Wat is het gevaar van het overbelasten van elektrische stopcontacten met meerdere apparaten?', '[{"text":"Hogere elektriciteitsrekeningen","correct":false},{"text":"Oververhitting, brandrisico en circuitfalen","correct":true},{"text":"Langzamere apparaatwerking","correct":false},{"text":"Apparatuurgarantie nietig","correct":false}]', 'Overbelaste circuits raken oververhit, beschadigen isolatie en kunnen brand veroorzaken. Gebruik geschikte stroomdistributie en keten nooit verlengsnoeren of stekkerdozen aan elkaar.', 7),
('G-PRL-012', 'nl', 'Welk type omgeving verhoogt elektrische gevaren in horecasettings?', '[{"text":"Ruimtes met airconditioning","correct":false},{"text":"Natte of vochtige omgevingen zoals keukens en bars","correct":true},{"text":"Goed verlichte gebieden","correct":false},{"text":"Tapijtvloeren","correct":false}]', 'Vocht verhoogt de elektrische geleidbaarheid en het schokrisico dramatisch. Keukens, bars en afwasgebieden vereisen waterdichte elektrische installaties en constante waakzaamheid.', 8);

-- G-PRL-012: Electrical Safety (German)
INSERT INTO training_test_questions (guide_code, language, question, options, explanation, sort_order) VALUES
('G-PRL-012', 'de', 'Was ist die wichtigste Regel beim Umgang mit beschädigter elektrischer Ausrüstung?', '[{"text":"Versuchen, es selbst zu reparieren","correct":false},{"text":"Niemals verwenden und sofort melden","correct":true},{"text":"Vorsichtig verwenden","correct":false},{"text":"Ausstecken und wieder einstecken zum Zurücksetzen","correct":false}]', 'Beschädigte elektrische Geräte stellen ernsthafte Schock- und Brandrisiken dar. Sie müssen außer Betrieb gekennzeichnet und sofort der Wartung oder dem Management gemeldet werden.', 1),
('G-PRL-012', 'de', 'Gemäß RD 614/2001, wer ist berechtigt, elektrische Reparaturen am Arbeitsplatz durchzuführen?', '[{"text":"Jedes erfahrene Personalmitglied","correct":false},{"text":"Nur qualifizierte und zertifizierte Elektriker","correct":true},{"text":"Der Wartungsmanager","correct":false},{"text":"Jeder mit Basiswerkzeugen","correct":false}]', 'Nur qualifizierte Elektriker mit ordnungsgemäßer Zertifizierung dürfen elektrische Arbeiten durchführen. Unautorisierte Reparaturen können zu Elektroschock, Brand und rechtlicher Haftung führen.', 2),
('G-PRL-012', 'de', 'Was ist die primäre Gefahr, wenn Wasser und Elektrizität in einer Küche in Kontakt kommen?', '[{"text":"Geräteschaden","correct":false},{"text":"Elektrischer Schock oder Elektroschock","correct":true},{"text":"Wasserverunreinigung","correct":false},{"text":"Lärm durch Funkenbildung","correct":false}]', 'Wasser leitet Elektrizität und erhöht das Risiko eines schweren oder tödlichen elektrischen Schocks dramatisch. Küchenumgebungen erfordern besondere Aufmerksamkeit, um Wasser von elektrischen Steckdosen und Geräten fernzuhalten.', 3),
('G-PRL-012', 'de', 'Vor dem Reinigen elektrischer Geräte, was ist der wesentliche erste Schritt?', '[{"text":"Mit Wasser besprühen","correct":false},{"text":"Vom Stromnetz trennen","correct":true},{"text":"Mit dem Schalter ausschalten","correct":false},{"text":"Gummihandschuhe anziehen","correct":false}]', 'Geräte müssen vor der Reinigung vollständig von der Stromversorgung getrennt werden. Einfaches Ausschalten ist nicht ausreichend—der Stecker muss entfernt werden, um alle elektrischen Gefahren zu beseitigen.', 4),
('G-PRL-012', 'de', 'Was sollten Sie regelmäßig an elektrischen Geräten überprüfen, um Gefahren zu vermeiden?', '[{"text":"Die Herstellergarantie","correct":false},{"text":"Stecker, Kabel und sichtbare Schäden","correct":true},{"text":"Die Geräteseriennummer","correct":false},{"text":"Den Farbzustand","correct":false}]', 'Regelmäßige Sichtprüfung von Steckern, Kabeln und Gerätegehäuse kann ausgefranste Drähte, freiliegende Leiter oder Schäden identifizieren, bevor sie Verletzungen oder Brände verursachen.', 5),
('G-PRL-012', 'de', 'Wo sollten Sie den Hauptstrom-Ausschalter an Ihrem Arbeitsplatz lokalisieren?', '[{"text":"Es ist nicht notwendig zu wissen","correct":false},{"text":"Jedes Personalmitglied sollte seinen Standort kennen","correct":true},{"text":"Nur Elektriker müssen es wissen","correct":false},{"text":"Im Büro des Managers","correct":false}]', 'In einem elektrischen Notfall (Schock, Brand, Funken) muss der Hauptschalter sofort ausgeschaltet werden. Alle Mitarbeiter sollten seinen Standort und die sichere Bedienung kennen.', 6),
('G-PRL-012', 'de', 'Was ist die Gefahr der Überlastung elektrischer Steckdosen mit mehreren Geräten?', '[{"text":"Höhere Stromrechnungen","correct":false},{"text":"Überhitzung, Brandgefahr und Schaltkreisausfall","correct":true},{"text":"Langsamerer Gerätebetrieb","correct":false},{"text":"Gerätegarantie ungültig","correct":false}]', 'Überlas tete Schaltkreise überhitzen, beschädigen die Isolierung und können Brände entzünden. Verwenden Sie geeignete Stromverteilung und verketten Sie niemals Verlängerungskabel oder Steckdosenleisten.', 7),
('G-PRL-012', 'de', 'Welche Art von Umgebung erhöht elektrische Gefahren in Gastronomieeinrichtungen?', '[{"text":"Klimatisierte Räume","correct":false},{"text":"Nasse oder feuchte Umgebungen wie Küchen und Bars","correct":true},{"text":"Gut beleuchtete Bereiche","correct":false},{"text":"Teppichböden","correct":false}]', 'Feuchtigkeit erhöht die elektrische Leitfähigkeit und das Schockrisiko dramatisch. Küchen, Bars und Geschirrspülbereiche erfordern wasserdichte elektrische Installationen und ständige Wachsamkeit.', 8);

-- G-PRL-013: Fire Prevention (English)
INSERT INTO training_test_questions (guide_code, language, question, options, explanation, sort_order) VALUES
('G-PRL-013', 'en', 'How often should fire drills be conducted in hospitality establishments?', '[{"text":"Once per year","correct":false},{"text":"Every 6 months","correct":true},{"text":"Once every 3 years","correct":false},{"text":"Only when required by inspection","correct":false}]', 'RD 513/2017 requires fire drills to be conducted at least twice per year to ensure staff are familiar with evacuation procedures and emergency protocols.', 1),
('G-PRL-013', 'en', 'What type of fire extinguisher is specifically designed for grease fires in kitchens?', '[{"text":"Class A (water)","correct":false},{"text":"Class F (wet chemical)","correct":true},{"text":"Class C (CO2)","correct":false},{"text":"Class D (dry powder)","correct":false}]', 'Class F extinguishers contain wet chemical agents designed for high-temperature cooking oil and grease fires. Never use water on grease fires as it causes explosive spreading.', 2),
('G-PRL-013', 'en', 'What is the most important rule regarding fire exits in a hospitality venue?', '[{"text":"They should be locked for security","correct":false},{"text":"They must remain clear and accessible at all times","correct":true},{"text":"They can be used for storage during quiet periods","correct":false},{"text":"Only one exit needs to be accessible","correct":false}]', 'Fire exits must never be obstructed. Blocked exits can result in fatalities during emergencies and significant legal penalties for the establishment.', 3),
('G-PRL-013', 'en', 'How often must fire suppression hood systems in kitchens be maintained?', '[{"text":"Every 5 years","correct":false},{"text":"Annually","correct":false},{"text":"Every 6 months or as per manufacturer specifications","correct":true},{"text":"Only when malfunction occurs","correct":false}]', 'Kitchen fire suppression systems require regular professional inspection and maintenance, typically every 6 months, to ensure they function correctly in an emergency.', 4),
('G-PRL-013', 'en', 'What should you do if you discover a small fire in the kitchen?', '[{"text":"Attempt to fight it only if trained, safe, and you have an escape route","correct":true},{"text":"Always attempt to extinguish it yourself","correct":false},{"text":"Ignore it if it seems small","correct":false},{"text":"Wait for the fire department before evacuating","correct":false}]', 'Only attempt to fight small fires if you are trained, have the correct extinguisher, it is safe to do so, and you have a clear escape route. When in doubt, evacuate immediately and call emergency services.', 5),
('G-PRL-013', 'en', 'Why are kitchen hood filters critical for fire prevention?', '[{"text":"They improve air quality","correct":false},{"text":"Grease buildup in filters is a major fire hazard","correct":true},{"text":"They reduce energy costs","correct":false},{"text":"They are required for health inspections only","correct":false}]', 'Accumulated grease in hood filters is highly flammable. Regular cleaning (typically weekly) prevents grease fires from spreading through the ventilation system.', 6),
('G-PRL-013', 'en', 'What is the minimum frequency for checking fire safety equipment?', '[{"text":"Weekly","correct":false},{"text":"Monthly","correct":true},{"text":"Annually","correct":false},{"text":"Only during official inspections","correct":false}]', 'Fire extinguishers, alarms, emergency lighting, and signage should be checked monthly to ensure they are present, accessible, and in working condition.', 7),
('G-PRL-013', 'en', 'In case of fire, what should staff do FIRST before attempting evacuation assistance?', '[{"text":"Activate the fire alarm","correct":true},{"text":"Attempt to extinguish the fire","correct":false},{"text":"Call the manager","correct":false},{"text":"Gather personal belongings","correct":false}]', 'The immediate priority is activating the fire alarm to alert all occupants and automatically notify emergency services. This saves lives by providing early warning.', 8);
