-- Migration: Training Test Questions for Labor Regulations Guides (Part 2)
-- Generated: 2026-02-08
--
-- This migration populates the training_test_questions table with 160 questions:
-- - 5 Labor Regulations guides (G-LAB-005 to G-LAB-009)
-- - 8 questions per guide
-- - 4 languages per guide (en, es, nl, de)
--
-- Question difficulty mix per guide: 2 easy, 4 medium, 2 hard
-- Each question has 4 options with exactly 1 correct answer
-- Explanations reference specific regulations and legal basis

-- ============================================================================
-- LABOR REGULATIONS GUIDES (G-LAB-005 to G-LAB-009)
-- ============================================================================

-- G-LAB-005: Time Recording (Registro de Jornada)
INSERT INTO training_test_questions (guide_code, language, question, options, explanation, sort_order) VALUES
('G-LAB-005', 'en', 'Since what year has daily time recording been mandatory for all employers in Spain?', '[{"text":"2015","correct":false},{"text":"2017","correct":false},{"text":"2019","correct":true},{"text":"2021","correct":false}]', 'RD-ley 8/2019 made daily time recording mandatory starting in 2019, requiring employers to record start and end times for all workers.', 1),
('G-LAB-005', 'en', 'What is the minimum retention period for time recording records?', '[{"text":"1 year","correct":false},{"text":"2 years","correct":false},{"text":"4 years","correct":true},{"text":"5 years","correct":false}]', 'Time recording records must be kept for a minimum of 4 years and must be available for labor inspection at any time.', 2),
('G-LAB-005', 'en', 'What range of fines can an employer face for non-compliance with time recording?', '[{"text":"100-500 euros","correct":false},{"text":"626-6,250 euros","correct":true},{"text":"1,000-10,000 euros","correct":false},{"text":"5,000-25,000 euros","correct":false}]', 'Failure to comply with time recording requirements can result in fines ranging from 626 to 6,250 euros, classified as a serious infraction.', 3),
('G-LAB-005', 'en', 'What information must the time recording system capture for each worker?', '[{"text":"Only start time","correct":false},{"text":"Only total hours worked","correct":false},{"text":"Daily start and end times","correct":true},{"text":"Break times only","correct":false}]', 'The time recording system must reliably record the daily start and end time for each worker, creating a verifiable record of actual working hours.', 4),
('G-LAB-005', 'en', 'Who must have access to the time recording records?', '[{"text":"Only the employer","correct":false},{"text":"Workers and labor inspectors","correct":true},{"text":"Only the human resources department","correct":false},{"text":"Only external auditors","correct":false}]', 'The time recording system must be accessible to both workers (to review their own records) and labor inspectors during inspections.', 5),
('G-LAB-005', 'en', 'What characteristics must the time recording system have?', '[{"text":"It can be paper-based only","correct":false},{"text":"It must be reliable and verifiable","correct":true},{"text":"It only needs to track overtime","correct":false},{"text":"It is optional for small businesses","correct":false}]', 'The system must be reliable, verifiable, and capable of producing accurate records. It can be digital or paper-based but must meet these standards.', 6),
('G-LAB-005', 'en', 'Which legal document established the mandatory time recording requirement?', '[{"text":"Estatuto de los Trabajadores","correct":false},{"text":"RD-ley 8/2019","correct":true},{"text":"Ley 31/1995","correct":false},{"text":"RD 39/1997","correct":false}]', 'Real Decreto-ley 8/2019 de medidas urgentes introduced the mandatory daily time recording requirement to combat unreported overtime and labor fraud.', 7),
('G-LAB-005', 'en', 'What happens if a worker disputes their recorded hours?', '[{"text":"The worker has no recourse","correct":false},{"text":"Only the employer version is valid","correct":false},{"text":"The worker can access and challenge their records","correct":true},{"text":"Disputes are not permitted","correct":false}]', 'Workers have the right to access their time records and can challenge discrepancies. The verifiable nature of the system supports resolution of disputes.', 8);

INSERT INTO training_test_questions (guide_code, language, question, options, explanation, sort_order) VALUES
('G-LAB-005', 'es', '¿Desde qué año es obligatorio el registro diario de jornada para todos los empleadores en España?', '[{"text":"2015","correct":false},{"text":"2017","correct":false},{"text":"2019","correct":true},{"text":"2021","correct":false}]', 'El RD-ley 8/2019 estableció la obligatoriedad del registro diario de jornada a partir de 2019, exigiendo registrar la hora de inicio y fin de cada trabajador.', 1),
('G-LAB-005', 'es', '¿Cuál es el período mínimo de conservación de los registros de jornada?', '[{"text":"1 año","correct":false},{"text":"2 años","correct":false},{"text":"4 años","correct":true},{"text":"5 años","correct":false}]', 'Los registros de jornada deben conservarse durante un mínimo de 4 años y estar disponibles para la inspección de trabajo en cualquier momento.', 2),
('G-LAB-005', 'es', '¿Qué rango de sanciones puede enfrentar un empleador por incumplimiento del registro de jornada?', '[{"text":"100-500 euros","correct":false},{"text":"626-6.250 euros","correct":true},{"text":"1.000-10.000 euros","correct":false},{"text":"5.000-25.000 euros","correct":false}]', 'El incumplimiento del registro de jornada puede resultar en sanciones que van desde 626 hasta 6.250 euros, clasificado como infracción grave.', 3),
('G-LAB-005', 'es', '¿Qué información debe capturar el sistema de registro de jornada para cada trabajador?', '[{"text":"Solo la hora de inicio","correct":false},{"text":"Solo el total de horas trabajadas","correct":false},{"text":"Hora de inicio y fin diaria","correct":true},{"text":"Solo los descansos","correct":false}]', 'El sistema de registro de jornada debe registrar de forma fiable la hora de inicio y fin diaria de cada trabajador, creando un registro verificable de las horas reales trabajadas.', 4),
('G-LAB-005', 'es', '¿Quién debe tener acceso a los registros de jornada?', '[{"text":"Solo el empleador","correct":false},{"text":"Los trabajadores y la inspección de trabajo","correct":true},{"text":"Solo el departamento de recursos humanos","correct":false},{"text":"Solo auditores externos","correct":false}]', 'El sistema de registro de jornada debe ser accesible tanto para los trabajadores (para revisar sus propios registros) como para la inspección de trabajo durante las inspecciones.', 5),
('G-LAB-005', 'es', '¿Qué características debe tener el sistema de registro de jornada?', '[{"text":"Solo puede ser en papel","correct":false},{"text":"Debe ser fiable y verificable","correct":true},{"text":"Solo necesita registrar horas extras","correct":false},{"text":"Es opcional para pequeñas empresas","correct":false}]', 'El sistema debe ser fiable, verificable y capaz de producir registros precisos. Puede ser digital o en papel pero debe cumplir estos estándares.', 6),
('G-LAB-005', 'es', '¿Qué documento legal estableció el requisito obligatorio del registro de jornada?', '[{"text":"Estatuto de los Trabajadores","correct":false},{"text":"RD-ley 8/2019","correct":true},{"text":"Ley 31/1995","correct":false},{"text":"RD 39/1997","correct":false}]', 'El Real Decreto-ley 8/2019 de medidas urgentes introdujo el requisito obligatorio del registro diario de jornada para combatir las horas extras no declaradas y el fraude laboral.', 7),
('G-LAB-005', 'es', '¿Qué sucede si un trabajador disputa sus horas registradas?', '[{"text":"El trabajador no tiene recurso","correct":false},{"text":"Solo la versión del empleador es válida","correct":false},{"text":"El trabajador puede acceder y cuestionar sus registros","correct":true},{"text":"No se permiten disputas","correct":false}]', 'Los trabajadores tienen derecho a acceder a sus registros de jornada y pueden cuestionar discrepancias. La naturaleza verificable del sistema respalda la resolución de disputas.', 8);

INSERT INTO training_test_questions (guide_code, language, question, options, explanation, sort_order) VALUES
('G-LAB-005', 'nl', 'Sinds welk jaar is dagelijkse tijdsregistratie verplicht voor alle werkgevers in Spanje?', '[{"text":"2015","correct":false},{"text":"2017","correct":false},{"text":"2019","correct":true},{"text":"2021","correct":false}]', 'RD-ley 8/2019 maakte dagelijkse tijdsregistratie verplicht vanaf 2019, waarbij werkgevers de begin- en eindtijden voor alle werknemers moeten registreren.', 1),
('G-LAB-005', 'nl', 'Wat is de minimale bewaartermijn voor tijdsregistraties?', '[{"text":"1 jaar","correct":false},{"text":"2 jaar","correct":false},{"text":"4 jaar","correct":true},{"text":"5 jaar","correct":false}]', 'Tijdsregistraties moeten minimaal 4 jaar worden bewaard en te allen tijde beschikbaar zijn voor arbeidsinspectie.', 2),
('G-LAB-005', 'nl', 'Welk boetebedrag kan een werkgever krijgen voor niet-naleving van tijdsregistratie?', '[{"text":"100-500 euro","correct":false},{"text":"626-6.250 euro","correct":true},{"text":"1.000-10.000 euro","correct":false},{"text":"5.000-25.000 euro","correct":false}]', 'Het niet naleven van tijdsregistratievereisten kan leiden tot boetes van 626 tot 6.250 euro, geclassificeerd als een ernstige overtreding.', 3),
('G-LAB-005', 'nl', 'Welke informatie moet het tijdsregistratiesysteem vastleggen voor elke werknemer?', '[{"text":"Alleen de starttijd","correct":false},{"text":"Alleen totaal gewerkte uren","correct":false},{"text":"Dagelijkse begin- en eindtijden","correct":true},{"text":"Alleen pauzetijden","correct":false}]', 'Het tijdsregistratiesysteem moet betrouwbaar de dagelijkse begin- en eindtijd voor elke werknemer registreren, waarbij een verifieerbare registratie van daadwerkelijk gewerkte uren wordt gecreëerd.', 4),
('G-LAB-005', 'nl', 'Wie moet toegang hebben tot de tijdsregistraties?', '[{"text":"Alleen de werkgever","correct":false},{"text":"Werknemers en arbeidsinspecteurs","correct":true},{"text":"Alleen de HR-afdeling","correct":false},{"text":"Alleen externe auditors","correct":false}]', 'Het tijdsregistratiesysteem moet toegankelijk zijn voor zowel werknemers (om hun eigen registraties te bekijken) als arbeidsinspecteurs tijdens inspecties.', 5),
('G-LAB-005', 'nl', 'Welke kenmerken moet het tijdsregistratiesysteem hebben?', '[{"text":"Het mag alleen papiergebaseerd zijn","correct":false},{"text":"Het moet betrouwbaar en verifieerbaar zijn","correct":true},{"text":"Het hoeft alleen overuren te registreren","correct":false},{"text":"Het is optioneel voor kleine bedrijven","correct":false}]', 'Het systeem moet betrouwbaar, verifieerbaar en in staat zijn nauwkeurige registraties te produceren. Het kan digitaal of papiergebaseerd zijn, maar moet aan deze normen voldoen.', 6),
('G-LAB-005', 'nl', 'Welk juridisch document heeft de verplichte tijdsregistratie-eis ingesteld?', '[{"text":"Estatuto de los Trabajadores","correct":false},{"text":"RD-ley 8/2019","correct":true},{"text":"Ley 31/1995","correct":false},{"text":"RD 39/1997","correct":false}]', 'Real Decreto-ley 8/2019 de medidas urgentes introduceerde de verplichte dagelijkse tijdsregistratie om niet-aangegeven overuren en arbeidsfraude tegen te gaan.', 7),
('G-LAB-005', 'nl', 'Wat gebeurt er als een werknemer hun geregistreerde uren betwist?', '[{"text":"De werknemer heeft geen verhaal","correct":false},{"text":"Alleen de werkgeversversie is geldig","correct":false},{"text":"De werknemer kan hun registraties inzien en aanvechten","correct":true},{"text":"Geschillen zijn niet toegestaan","correct":false}]', 'Werknemers hebben het recht om hun tijdsregistraties in te zien en kunnen discrepanties aanvechten. De verifieerbare aard van het systeem ondersteunt de oplossing van geschillen.', 8);

INSERT INTO training_test_questions (guide_code, language, question, options, explanation, sort_order) VALUES
('G-LAB-005', 'de', 'Seit welchem Jahr ist die tägliche Zeiterfassung für alle Arbeitgeber in Spanien verpflichtend?', '[{"text":"2015","correct":false},{"text":"2017","correct":false},{"text":"2019","correct":true},{"text":"2021","correct":false}]', 'RD-ley 8/2019 machte die tägliche Zeiterfassung ab 2019 verpflichtend und verlangt von Arbeitgebern, Beginn- und Endzeiten für alle Arbeitnehmer zu erfassen.', 1),
('G-LAB-005', 'de', 'Was ist die Mindestaufbewahrungsfrist für Zeiterfassungsunterlagen?', '[{"text":"1 Jahr","correct":false},{"text":"2 Jahre","correct":false},{"text":"4 Jahre","correct":true},{"text":"5 Jahre","correct":false}]', 'Zeiterfassungsunterlagen müssen mindestens 4 Jahre aufbewahrt werden und jederzeit für die Arbeitsinspektion verfügbar sein.', 2),
('G-LAB-005', 'de', 'Welche Geldstrafen kann ein Arbeitgeber bei Nichteinhaltung der Zeiterfassung erhalten?', '[{"text":"100-500 Euro","correct":false},{"text":"626-6.250 Euro","correct":true},{"text":"1.000-10.000 Euro","correct":false},{"text":"5.000-25.000 Euro","correct":false}]', 'Die Nichteinhaltung der Zeiterfassungsanforderungen kann zu Geldstrafen von 626 bis 6.250 Euro führen, die als schwere Ordnungswidrigkeit eingestuft werden.', 3),
('G-LAB-005', 'de', 'Welche Informationen muss das Zeiterfassungssystem für jeden Arbeitnehmer erfassen?', '[{"text":"Nur die Startzeit","correct":false},{"text":"Nur die Gesamtarbeitsstunden","correct":false},{"text":"Tägliche Beginn- und Endzeiten","correct":true},{"text":"Nur Pausenzeiten","correct":false}]', 'Das Zeiterfassungssystem muss zuverlässig die tägliche Beginn- und Endzeit für jeden Arbeitnehmer erfassen und eine überprüfbare Aufzeichnung der tatsächlich geleisteten Arbeitsstunden erstellen.', 4),
('G-LAB-005', 'de', 'Wer muss Zugang zu den Zeiterfassungsunterlagen haben?', '[{"text":"Nur der Arbeitgeber","correct":false},{"text":"Arbeitnehmer und Arbeitsinspektoren","correct":true},{"text":"Nur die Personalabteilung","correct":false},{"text":"Nur externe Prüfer","correct":false}]', 'Das Zeiterfassungssystem muss sowohl für Arbeitnehmer (um ihre eigenen Aufzeichnungen einzusehen) als auch für Arbeitsinspektoren während Inspektionen zugänglich sein.', 5),
('G-LAB-005', 'de', 'Welche Eigenschaften muss das Zeiterfassungssystem haben?', '[{"text":"Es darf nur papierbasiert sein","correct":false},{"text":"Es muss zuverlässig und überprüfbar sein","correct":true},{"text":"Es muss nur Überstunden erfassen","correct":false},{"text":"Es ist optional für kleine Unternehmen","correct":false}]', 'Das System muss zuverlässig, überprüfbar und in der Lage sein, genaue Aufzeichnungen zu erstellen. Es kann digital oder papierbasiert sein, muss aber diese Standards erfüllen.', 6),
('G-LAB-005', 'de', 'Welches Rechtsdokument hat die verpflichtende Zeiterfassung eingeführt?', '[{"text":"Estatuto de los Trabajadores","correct":false},{"text":"RD-ley 8/2019","correct":true},{"text":"Ley 31/1995","correct":false},{"text":"RD 39/1997","correct":false}]', 'Real Decreto-ley 8/2019 de medidas urgentes führte die verpflichtende tägliche Zeiterfassung ein, um nicht gemeldete Überstunden und Arbeitsbetrug zu bekämpfen.', 7),
('G-LAB-005', 'de', 'Was passiert, wenn ein Arbeitnehmer seine erfassten Stunden bestreitet?', '[{"text":"Der Arbeitnehmer hat keine Handhabe","correct":false},{"text":"Nur die Arbeitgeberversion ist gültig","correct":false},{"text":"Der Arbeitnehmer kann seine Aufzeichnungen einsehen und anfechten","correct":true},{"text":"Streitigkeiten sind nicht zulässig","correct":false}]', 'Arbeitnehmer haben das Recht, ihre Zeiterfassungen einzusehen und können Unstimmigkeiten anfechten. Die überprüfbare Natur des Systems unterstützt die Beilegung von Streitigkeiten.', 8);

-- G-LAB-006: Contract Types in Hospitality
INSERT INTO training_test_questions (guide_code, language, question, options, explanation, sort_order) VALUES
('G-LAB-006', 'en', 'What year did Spain implement a major labor reform affecting contract types?', '[{"text":"2019","correct":false},{"text":"2020","correct":false},{"text":"2021","correct":true},{"text":"2022","correct":false}]', 'The 2021 labor reform (RD-ley 32/2021) significantly changed Spanish labor law, making indefinite contracts the default and limiting fixed-term contracts.', 1),
('G-LAB-006', 'en', 'What is now the default type of employment contract in Spain after the 2021 reform?', '[{"text":"Fixed-term contract","correct":false},{"text":"Indefinite contract","correct":true},{"text":"Temporary contract","correct":false},{"text":"Seasonal contract","correct":false}]', 'Following the 2021 labor reform, indefinite contracts (contratos indefinidos) became the default, with fixed-term contracts limited to specific legal circumstances.', 2),
('G-LAB-006', 'en', 'What type of contract is commonly used for seasonal recurring work in hospitality?', '[{"text":"Temporary contract","correct":false},{"text":"Fixed-term contract","correct":false},{"text":"Fijo discontinuo contract","correct":true},{"text":"Training contract","correct":false}]', 'The fijo discontinuo (discontinuous permanent) contract is ideal for seasonal hospitality work, providing job security while accommodating seasonal activity patterns.', 3),
('G-LAB-006', 'en', 'Under what circumstances are fixed-term contracts permitted after the 2021 reform?', '[{"text":"At any time at employer discretion","correct":false},{"text":"Only for production peaks or substitutions","correct":true},{"text":"For all entry-level positions","correct":false},{"text":"Never permitted anymore","correct":false}]', 'Fixed-term contracts are now limited to specific circumstances: production peaks (accumulation of tasks) or substitution of absent workers, with strict legal requirements.', 4),
('G-LAB-006', 'en', 'What is the standard probation period for most workers in hospitality?', '[{"text":"1 month","correct":false},{"text":"2 months","correct":true},{"text":"4 months","correct":false},{"text":"6 months","correct":false}]', 'The standard probation period is 2 months for most workers. For university graduates or qualified technicians, it can extend to 6 months per the collective agreement.', 5),
('G-LAB-006', 'en', 'What must part-time contracts specify according to Spanish law?', '[{"text":"Only the total weekly hours","correct":false},{"text":"Exact hours and distribution","correct":true},{"text":"Only the days of work","correct":false},{"text":"No specific requirements","correct":false}]', 'Part-time contracts must clearly specify the exact number of hours and their distribution throughout the day, week, month, or year to protect worker rights.', 6),
('G-LAB-006', 'en', 'Which legal document governs contract types in Spain?', '[{"text":"RD 39/1997","correct":false},{"text":"Ley 31/1995","correct":false},{"text":"Estatuto de los Trabajadores (ET)","correct":true},{"text":"RD 8/2019","correct":false}]', 'The Estatuto de los Trabajadores (Workers Statute), specifically articles 8-16, along with RD-ley 32/2021, governs employment contract types and requirements in Spain.', 7),
('G-LAB-006', 'en', 'What type of contract is designed for young workers receiving training?', '[{"text":"Indefinite contract","correct":false},{"text":"Fixed-term contract","correct":false},{"text":"Training contract","correct":true},{"text":"Fijo discontinuo contract","correct":false}]', 'Training contracts (contratos formativos) are designed for young workers, combining work with formal training and offering special social security contribution rates.', 8);

INSERT INTO training_test_questions (guide_code, language, question, options, explanation, sort_order) VALUES
('G-LAB-006', 'es', '¿En qué año implementó España una reforma laboral importante que afectó los tipos de contrato?', '[{"text":"2019","correct":false},{"text":"2020","correct":false},{"text":"2021","correct":true},{"text":"2022","correct":false}]', 'La reforma laboral de 2021 (RD-ley 32/2021) cambió significativamente la legislación laboral española, haciendo los contratos indefinidos el tipo predeterminado y limitando los contratos temporales.', 1),
('G-LAB-006', 'es', '¿Cuál es ahora el tipo predeterminado de contrato laboral en España después de la reforma de 2021?', '[{"text":"Contrato temporal","correct":false},{"text":"Contrato indefinido","correct":true},{"text":"Contrato eventual","correct":false},{"text":"Contrato de temporada","correct":false}]', 'Tras la reforma laboral de 2021, los contratos indefinidos se convirtieron en el tipo predeterminado, limitándose los contratos temporales a circunstancias legales específicas.', 2),
('G-LAB-006', 'es', '¿Qué tipo de contrato se utiliza comúnmente para trabajo recurrente estacional en hostelería?', '[{"text":"Contrato temporal","correct":false},{"text":"Contrato de duración determinada","correct":false},{"text":"Contrato fijo discontinuo","correct":true},{"text":"Contrato formativo","correct":false}]', 'El contrato fijo discontinuo es ideal para el trabajo estacional en hostelería, proporcionando seguridad laboral mientras se acomoda a los patrones de actividad estacional.', 3),
('G-LAB-006', 'es', '¿Bajo qué circunstancias se permiten los contratos temporales después de la reforma de 2021?', '[{"text":"En cualquier momento a discreción del empleador","correct":false},{"text":"Solo por picos de producción o sustituciones","correct":true},{"text":"Para todos los puestos de nivel inicial","correct":false},{"text":"Ya no están permitidos","correct":false}]', 'Los contratos temporales ahora están limitados a circunstancias específicas: picos de producción (acumulación de tareas) o sustitución de trabajadores ausentes, con requisitos legales estrictos.', 4),
('G-LAB-006', 'es', '¿Cuál es el período de prueba estándar para la mayoría de trabajadores en hostelería?', '[{"text":"1 mes","correct":false},{"text":"2 meses","correct":true},{"text":"4 meses","correct":false},{"text":"6 meses","correct":false}]', 'El período de prueba estándar es de 2 meses para la mayoría de trabajadores. Para titulados universitarios o técnicos cualificados, puede extenderse a 6 meses según el convenio colectivo.', 5),
('G-LAB-006', 'es', '¿Qué deben especificar los contratos a tiempo parcial según la ley española?', '[{"text":"Solo las horas semanales totales","correct":false},{"text":"Horas exactas y su distribución","correct":true},{"text":"Solo los días de trabajo","correct":false},{"text":"No hay requisitos específicos","correct":false}]', 'Los contratos a tiempo parcial deben especificar claramente el número exacto de horas y su distribución a lo largo del día, semana, mes o año para proteger los derechos del trabajador.', 6),
('G-LAB-006', 'es', '¿Qué documento legal regula los tipos de contrato en España?', '[{"text":"RD 39/1997","correct":false},{"text":"Ley 31/1995","correct":false},{"text":"Estatuto de los Trabajadores (ET)","correct":true},{"text":"RD 8/2019","correct":false}]', 'El Estatuto de los Trabajadores (ET), específicamente los artículos 8-16, junto con el RD-ley 32/2021, regula los tipos de contratos laborales y sus requisitos en España.', 7),
('G-LAB-006', 'es', '¿Qué tipo de contrato está diseñado para trabajadores jóvenes que reciben formación?', '[{"text":"Contrato indefinido","correct":false},{"text":"Contrato temporal","correct":false},{"text":"Contrato formativo","correct":true},{"text":"Contrato fijo discontinuo","correct":false}]', 'Los contratos formativos están diseñados para trabajadores jóvenes, combinando trabajo con formación oficial y ofreciendo tipos especiales de cotización a la Seguridad Social.', 8);

INSERT INTO training_test_questions (guide_code, language, question, options, explanation, sort_order) VALUES
('G-LAB-006', 'nl', 'In welk jaar voerde Spanje een belangrijke arbeidshervorming door die de contracttypen beïnvloedde?', '[{"text":"2019","correct":false},{"text":"2020","correct":false},{"text":"2021","correct":true},{"text":"2022","correct":false}]', 'De arbeidshervorming van 2021 (RD-ley 32/2021) veranderde de Spaanse arbeidswetgeving aanzienlijk, waarbij contracten voor onbepaalde tijd de standaard werden en tijdelijke contracten werden beperkt.', 1),
('G-LAB-006', 'nl', 'Wat is nu het standaard type arbeidscontract in Spanje na de hervorming van 2021?', '[{"text":"Tijdelijk contract","correct":false},{"text":"Contract voor onbepaalde tijd","correct":true},{"text":"Tijdelijk contract","correct":false},{"text":"Seizoenscontract","correct":false}]', 'Na de arbeidshervorming van 2021 werden contracten voor onbepaalde tijd (contratos indefinidos) de standaard, waarbij tijdelijke contracten beperkt zijn tot specifieke wettelijke omstandigheden.', 2),
('G-LAB-006', 'nl', 'Welk type contract wordt vaak gebruikt voor seizoensgebonden terugkerend werk in de horeca?', '[{"text":"Tijdelijk contract","correct":false},{"text":"Contract voor bepaalde tijd","correct":false},{"text":"Fijo discontinuo contract","correct":true},{"text":"Opleidingscontract","correct":false}]', 'Het fijo discontinuo (discontinu permanent) contract is ideaal voor seizoensgebonden horecawerk, dat werkzekerheid biedt terwijl het seizoensgebonden activiteitspatronen accommodeert.', 3),
('G-LAB-006', 'nl', 'Onder welke omstandigheden zijn tijdelijke contracten toegestaan na de hervorming van 2021?', '[{"text":"Op elk moment naar goeddunken van de werkgever","correct":false},{"text":"Alleen voor productiepieken of vervangingen","correct":true},{"text":"Voor alle instapposities","correct":false},{"text":"Niet meer toegestaan","correct":false}]', 'Tijdelijke contracten zijn nu beperkt tot specifieke omstandigheden: productiepieken (ophoping van taken) of vervanging van afwezige werknemers, met strikte wettelijke vereisten.', 4),
('G-LAB-006', 'nl', 'Wat is de standaard proeftijd voor de meeste werknemers in de horeca?', '[{"text":"1 maand","correct":false},{"text":"2 maanden","correct":true},{"text":"4 maanden","correct":false},{"text":"6 maanden","correct":false}]', 'De standaard proeftijd is 2 maanden voor de meeste werknemers. Voor universitair afgestudeerden of gekwalificeerde technici kan dit volgens de cao worden verlengd tot 6 maanden.', 5),
('G-LAB-006', 'nl', 'Wat moeten deeltijdcontracten specificeren volgens de Spaanse wet?', '[{"text":"Alleen de totale wekelijkse uren","correct":false},{"text":"Exacte uren en verdeling","correct":true},{"text":"Alleen de werkdagen","correct":false},{"text":"Geen specifieke vereisten","correct":false}]', 'Deeltijdcontracten moeten duidelijk het exacte aantal uren en hun verdeling over de dag, week, maand of jaar specificeren om de rechten van werknemers te beschermen.', 6),
('G-LAB-006', 'nl', 'Welk juridisch document regelt de contracttypen in Spanje?', '[{"text":"RD 39/1997","correct":false},{"text":"Ley 31/1995","correct":false},{"text":"Estatuto de los Trabajadores (ET)","correct":true},{"text":"RD 8/2019","correct":false}]', 'Het Estatuto de los Trabajadores (Werknemersstatuut), specifiek artikelen 8-16, samen met RD-ley 32/2021, regelt arbeidscontracttypes en vereisten in Spanje.', 7),
('G-LAB-006', 'nl', 'Welk type contract is ontworpen voor jonge werknemers die een opleiding volgen?', '[{"text":"Contract voor onbepaalde tijd","correct":false},{"text":"Tijdelijk contract","correct":false},{"text":"Opleidingscontract","correct":true},{"text":"Fijo discontinuo contract","correct":false}]', 'Opleidingscontracten (contratos formativos) zijn ontworpen voor jonge werknemers, waarbij werk wordt gecombineerd met formele opleiding en speciale sociale zekerheidsbijdragetarieven worden aangeboden.', 8);

INSERT INTO training_test_questions (guide_code, language, question, options, explanation, sort_order) VALUES
('G-LAB-006', 'de', 'In welchem Jahr führte Spanien eine wichtige Arbeitsreform durch, die die Vertragsarten beeinflusste?', '[{"text":"2019","correct":false},{"text":"2020","correct":false},{"text":"2021","correct":true},{"text":"2022","correct":false}]', 'Die Arbeitsreform von 2021 (RD-ley 32/2021) veränderte das spanische Arbeitsrecht erheblich, machte unbefristete Verträge zum Standard und begrenzte befristete Verträge.', 1),
('G-LAB-006', 'de', 'Was ist jetzt nach der Reform von 2021 der Standardarbeitsvertragstyp in Spanien?', '[{"text":"Befristeter Vertrag","correct":false},{"text":"Unbefristeter Vertrag","correct":true},{"text":"Zeitvertrag","correct":false},{"text":"Saisonvertrag","correct":false}]', 'Nach der Arbeitsreform von 2021 wurden unbefristete Verträge (contratos indefinidos) zum Standard, wobei befristete Verträge auf spezifische rechtliche Umstände begrenzt sind.', 2),
('G-LAB-006', 'de', 'Welcher Vertragstyp wird häufig für saisonale wiederkehrende Arbeit im Gastgewerbe verwendet?', '[{"text":"Zeitvertrag","correct":false},{"text":"Befristeter Vertrag","correct":false},{"text":"Fijo discontinuo Vertrag","correct":true},{"text":"Ausbildungsvertrag","correct":false}]', 'Der fijo discontinuo (diskontinuierlich unbefristete) Vertrag ist ideal für saisonale Gastgewerbearbeit und bietet Arbeitsplatzsicherheit bei gleichzeitiger Anpassung an saisonale Aktivitätsmuster.', 3),
('G-LAB-006', 'de', 'Unter welchen Umständen sind befristete Verträge nach der Reform von 2021 zulässig?', '[{"text":"Jederzeit nach Ermessen des Arbeitgebers","correct":false},{"text":"Nur für Produktionsspitzen oder Ersatz","correct":true},{"text":"Für alle Einstiegspositionen","correct":false},{"text":"Nicht mehr zulässig","correct":false}]', 'Befristete Verträge sind jetzt auf spezifische Umstände begrenzt: Produktionsspitzen (Aufgabenanhäufung) oder Ersatz abwesender Arbeitnehmer, mit strengen rechtlichen Anforderungen.', 4),
('G-LAB-006', 'de', 'Was ist die Standard-Probezeit für die meisten Arbeitnehmer im Gastgewerbe?', '[{"text":"1 Monat","correct":false},{"text":"2 Monate","correct":true},{"text":"4 Monate","correct":false},{"text":"6 Monate","correct":false}]', 'Die Standard-Probezeit beträgt 2 Monate für die meisten Arbeitnehmer. Für Hochschulabsolventen oder qualifizierte Techniker kann sie gemäß Tarifvertrag auf 6 Monate verlängert werden.', 5),
('G-LAB-006', 'de', 'Was müssen Teilzeitverträge gemäß spanischem Recht spezifizieren?', '[{"text":"Nur die wöchentlichen Gesamtstunden","correct":false},{"text":"Genaue Stunden und Verteilung","correct":true},{"text":"Nur die Arbeitstage","correct":false},{"text":"Keine spezifischen Anforderungen","correct":false}]', 'Teilzeitverträge müssen die genaue Stundenanzahl und deren Verteilung über Tag, Woche, Monat oder Jahr klar spezifizieren, um die Arbeitnehmerrechte zu schützen.', 6),
('G-LAB-006', 'de', 'Welches Rechtsdokument regelt die Vertragsarten in Spanien?', '[{"text":"RD 39/1997","correct":false},{"text":"Ley 31/1995","correct":false},{"text":"Estatuto de los Trabajadores (ET)","correct":true},{"text":"RD 8/2019","correct":false}]', 'Das Estatuto de los Trabajadores (Arbeitnehmerstatut), insbesondere die Artikel 8-16, zusammen mit RD-ley 32/2021, regelt die Arbeitsvertragsarten und -anforderungen in Spanien.', 7),
('G-LAB-006', 'de', 'Welcher Vertragstyp ist für junge Arbeitnehmer in Ausbildung konzipiert?', '[{"text":"Unbefristeter Vertrag","correct":false},{"text":"Befristeter Vertrag","correct":false},{"text":"Ausbildungsvertrag","correct":true},{"text":"Fijo discontinuo Vertrag","correct":false}]', 'Ausbildungsverträge (contratos formativos) sind für junge Arbeitnehmer konzipiert und kombinieren Arbeit mit formaler Ausbildung und bieten spezielle Sozialversicherungsbeitragssätze.', 8);

-- G-LAB-007: Worker Rights & Duties
INSERT INTO training_test_questions (guide_code, language, question, options, explanation, sort_order) VALUES
('G-LAB-007', 'en', 'Which article of the Spanish Constitution establishes the right to work?', '[{"text":"Article 25","correct":false},{"text":"Article 30","correct":false},{"text":"Article 35","correct":true},{"text":"Article 40","correct":false}]', 'Article 35 of the Spanish Constitution establishes the right and duty to work, the right to free choice of profession or trade, and the right to fair remuneration.', 1),
('G-LAB-007', 'en', 'Which of the following is a fundamental worker right under Spanish law?', '[{"text":"Right to use personal mobile phone at all times","correct":false},{"text":"Right to non-discrimination","correct":true},{"text":"Right to refuse any assigned task","correct":false},{"text":"Right to set own working hours","correct":false}]', 'Workers have fundamental rights including fair pay, non-discrimination, dignity at work, health and safety, trade union membership, and information/consultation per ET Art. 4.', 2),
('G-LAB-007', 'en', 'What is a key worker duty according to the Estatuto de los Trabajadores?', '[{"text":"To maximize company profits","correct":false},{"text":"To work unlimited overtime","correct":false},{"text":"To comply with safety rules","correct":true},{"text":"To recruit new employees","correct":false}]', 'Workers have duties including good faith performance, diligence, compliance with safety rules and instructions, and maintaining confidentiality of company information per ET Art. 5.', 3),
('G-LAB-007', 'en', 'Workers have the right to dignity at work, which includes protection from:', '[{"text":"Constructive criticism","correct":false},{"text":"Harassment and discrimination","correct":true},{"text":"Performance evaluations","correct":false},{"text":"Training requirements","correct":false}]', 'The right to dignity at work (dignidad) includes protection from harassment, discrimination, and degrading treatment, ensuring a respectful work environment.', 4),
('G-LAB-007', 'en', 'What right do workers have regarding information about the company?', '[{"text":"Access to all company financial data","correct":false},{"text":"Information and consultation on work-related matters","correct":true},{"text":"Right to attend all management meetings","correct":false},{"text":"No information rights exist","correct":false}]', 'Workers have the right to information and consultation on matters affecting employment and working conditions, including company decisions that may impact their jobs.', 5),
('G-LAB-007', 'en', 'Which worker duty relates to trust and honesty?', '[{"text":"Good faith (buena fe)","correct":true},{"text":"Maximum productivity","correct":false},{"text":"Absolute obedience","correct":false},{"text":"Unlimited availability","correct":false}]', 'The duty of good faith (buena fe) requires workers to act honestly and loyally, performing duties conscientiously and respecting the employer-employee relationship.', 6),
('G-LAB-007', 'en', 'What does the right to occupational health and safety include?', '[{"text":"Only emergency medical care","correct":false},{"text":"Effective protection from workplace risks","correct":true},{"text":"Annual health insurance bonus","correct":false},{"text":"Gym membership","correct":false}]', 'The right to occupational health and safety includes effective protection from workplace risks, appropriate PPE, training, health surveillance, and a safe work environment per Ley 31/1995.', 7),
('G-LAB-007', 'en', 'Workers have a duty of confidentiality regarding:', '[{"text":"Their own salary information","correct":false},{"text":"Trade secrets and company information","correct":true},{"text":"Workplace safety incidents","correct":false},{"text":"Legal violations by the company","correct":false}]', 'Workers must maintain confidentiality of trade secrets and company information learned during employment. This duty continues even after employment ends for certain sensitive information.', 8);

INSERT INTO training_test_questions (guide_code, language, question, options, explanation, sort_order) VALUES
('G-LAB-007', 'es', '¿Qué artículo de la Constitución Española establece el derecho al trabajo?', '[{"text":"Artículo 25","correct":false},{"text":"Artículo 30","correct":false},{"text":"Artículo 35","correct":true},{"text":"Artículo 40","correct":false}]', 'El artículo 35 de la Constitución Española establece el derecho y el deber de trabajar, el derecho a la libre elección de profesión u oficio y el derecho a una remuneración justa.', 1),
('G-LAB-007', 'es', '¿Cuál de los siguientes es un derecho fundamental del trabajador según la ley española?', '[{"text":"Derecho a usar el móvil personal en todo momento","correct":false},{"text":"Derecho a la no discriminación","correct":true},{"text":"Derecho a rechazar cualquier tarea asignada","correct":false},{"text":"Derecho a establecer el propio horario","correct":false}]', 'Los trabajadores tienen derechos fundamentales incluyendo salario justo, no discriminación, dignidad en el trabajo, salud y seguridad, afiliación sindical e información/consulta según el ET Art. 4.', 2),
('G-LAB-007', 'es', '¿Cuál es un deber clave del trabajador según el Estatuto de los Trabajadores?', '[{"text":"Maximizar los beneficios de la empresa","correct":false},{"text":"Trabajar horas extras ilimitadas","correct":false},{"text":"Cumplir con las normas de seguridad","correct":true},{"text":"Reclutar nuevos empleados","correct":false}]', 'Los trabajadores tienen deberes incluyendo cumplimiento de buena fe, diligencia, cumplimiento de normas de seguridad e instrucciones, y mantenimiento de confidencialidad de información de la empresa según ET Art. 5.', 3),
('G-LAB-007', 'es', 'Los trabajadores tienen derecho a la dignidad en el trabajo, que incluye protección contra:', '[{"text":"Críticas constructivas","correct":false},{"text":"Acoso y discriminación","correct":true},{"text":"Evaluaciones de desempeño","correct":false},{"text":"Requisitos de formación","correct":false}]', 'El derecho a la dignidad en el trabajo incluye protección contra el acoso, la discriminación y el trato degradante, asegurando un ambiente de trabajo respetuoso.', 4),
('G-LAB-007', 'es', '¿Qué derecho tienen los trabajadores respecto a la información sobre la empresa?', '[{"text":"Acceso a todos los datos financieros de la empresa","correct":false},{"text":"Información y consulta sobre asuntos laborales","correct":true},{"text":"Derecho a asistir a todas las reuniones de gestión","correct":false},{"text":"No existen derechos de información","correct":false}]', 'Los trabajadores tienen derecho a información y consulta sobre asuntos que afectan el empleo y las condiciones de trabajo, incluyendo decisiones de la empresa que puedan impactar sus trabajos.', 5),
('G-LAB-007', 'es', '¿Qué deber del trabajador se relaciona con la confianza y la honestidad?', '[{"text":"Buena fe","correct":true},{"text":"Máxima productividad","correct":false},{"text":"Obediencia absoluta","correct":false},{"text":"Disponibilidad ilimitada","correct":false}]', 'El deber de buena fe requiere que los trabajadores actúen honesta y lealmente, desempeñando funciones concienzudamente y respetando la relación empleador-empleado.', 6),
('G-LAB-007', 'es', '¿Qué incluye el derecho a la salud y seguridad en el trabajo?', '[{"text":"Solo atención médica de emergencia","correct":false},{"text":"Protección efectiva contra riesgos laborales","correct":true},{"text":"Bono anual de seguro de salud","correct":false},{"text":"Membresía de gimnasio","correct":false}]', 'El derecho a la salud y seguridad en el trabajo incluye protección efectiva contra riesgos laborales, EPIs apropiados, formación, vigilancia de la salud y un ambiente de trabajo seguro según Ley 31/1995.', 7),
('G-LAB-007', 'es', 'Los trabajadores tienen un deber de confidencialidad respecto a:', '[{"text":"Su propia información salarial","correct":false},{"text":"Secretos comerciales e información de la empresa","correct":true},{"text":"Incidentes de seguridad en el lugar de trabajo","correct":false},{"text":"Violaciones legales por parte de la empresa","correct":false}]', 'Los trabajadores deben mantener la confidencialidad de los secretos comerciales e información de la empresa aprendida durante el empleo. Este deber continúa incluso después de que termina el empleo para cierta información sensible.', 8);

INSERT INTO training_test_questions (guide_code, language, question, options, explanation, sort_order) VALUES
('G-LAB-007', 'nl', 'Welk artikel van de Spaanse Grondwet vestigt het recht op werk?', '[{"text":"Artikel 25","correct":false},{"text":"Artikel 30","correct":false},{"text":"Artikel 35","correct":true},{"text":"Artikel 40","correct":false}]', 'Artikel 35 van de Spaanse Grondwet vestigt het recht en de plicht om te werken, het recht op vrije keuze van beroep en het recht op eerlijke beloning.', 1),
('G-LAB-007', 'nl', 'Welke van de volgende is een fundamenteel werknemersrecht volgens Spaans recht?', '[{"text":"Recht om altijd persoonlijke mobiele telefoon te gebruiken","correct":false},{"text":"Recht op non-discriminatie","correct":true},{"text":"Recht om elke toegewezen taak te weigeren","correct":false},{"text":"Recht om eigen werktijden vast te stellen","correct":false}]', 'Werknemers hebben fundamentele rechten waaronder eerlijk loon, non-discriminatie, waardigheid op het werk, gezondheid en veiligheid, vakbondslidmaatschap en informatie/consultatie volgens ET Art. 4.', 2),
('G-LAB-007', 'nl', 'Wat is een belangrijke werknemersplicht volgens het Estatuto de los Trabajadores?', '[{"text":"Bedrijfswinsten maximaliseren","correct":false},{"text":"Onbeperkte overuren werken","correct":false},{"text":"Veiligheidsregels naleven","correct":true},{"text":"Nieuwe werknemers werven","correct":false}]', 'Werknemers hebben plichten waaronder goede trouw, zorgvuldigheid, naleving van veiligheidsregels en instructies, en het handhaven van vertrouwelijkheid van bedrijfsinformatie volgens ET Art. 5.', 3),
('G-LAB-007', 'nl', 'Werknemers hebben recht op waardigheid op het werk, wat bescherming omvat tegen:', '[{"text":"Constructieve kritiek","correct":false},{"text":"Intimidatie en discriminatie","correct":true},{"text":"Prestatie-evaluaties","correct":false},{"text":"Trainingsvereisten","correct":false}]', 'Het recht op waardigheid op het werk (dignidad) omvat bescherming tegen intimidatie, discriminatie en vernederende behandeling, waardoor een respectvolle werkomgeving wordt gewaarborgd.', 4),
('G-LAB-007', 'nl', 'Welk recht hebben werknemers met betrekking tot informatie over het bedrijf?', '[{"text":"Toegang tot alle financiële bedrijfsgegevens","correct":false},{"text":"Informatie en consultatie over werkgerelateerde zaken","correct":true},{"text":"Recht om alle managementvergaderingen bij te wonen","correct":false},{"text":"Er bestaan geen informatierechten","correct":false}]', 'Werknemers hebben recht op informatie en consultatie over zaken die de werkgelegenheid en arbeidsvoorwaarden beïnvloeden, inclusief bedrijfsbeslissingen die hun banen kunnen beïnvloeden.', 5),
('G-LAB-007', 'nl', 'Welke werknemersplicht heeft betrekking op vertrouwen en eerlijkheid?', '[{"text":"Goede trouw (buena fe)","correct":true},{"text":"Maximale productiviteit","correct":false},{"text":"Absolute gehoorzaamheid","correct":false},{"text":"Onbeperkte beschikbaarheid","correct":false}]', 'De plicht van goede trouw (buena fe) vereist dat werknemers eerlijk en loyaal handelen, hun taken gewetens­vol uitvoeren en de werkgever-werknemersrelatie respecteren.', 6),
('G-LAB-007', 'nl', 'Wat omvat het recht op arbeidsgezondheid en -veiligheid?', '[{"text":"Alleen spoedeisende medische zorg","correct":false},{"text":"Effectieve bescherming tegen werkplekrisico\'s","correct":true},{"text":"Jaarlijkse ziektekostenverzekeringsbonus","correct":false},{"text":"Sportschoollidmaatschap","correct":false}]', 'Het recht op arbeidsgezondheid en -veiligheid omvat effectieve bescherming tegen werkplekrisico\'s, geschikte PBM, training, gezondheidstoezicht en een veilige werkomgeving volgens Ley 31/1995.', 7),
('G-LAB-007', 'nl', 'Werknemers hebben een vertrouwelijkheidsplicht met betrekking tot:', '[{"text":"Hun eigen salarisinformatie","correct":false},{"text":"Handelsgeheimen en bedrijfsinformatie","correct":true},{"text":"Veiligheidsincidenten op de werkplek","correct":false},{"text":"Wettelijke overtredingen door het bedrijf","correct":false}]', 'Werknemers moeten de vertrouwelijkheid bewaren van handelsgeheimen en bedrijfsinformatie die tijdens het dienstverband is geleerd. Deze plicht blijft bestaan zelfs na beëindiging van het dienstverband voor bepaalde gevoelige informatie.', 8);

INSERT INTO training_test_questions (guide_code, language, question, options, explanation, sort_order) VALUES
('G-LAB-007', 'de', 'Welcher Artikel der spanischen Verfassung begründet das Recht auf Arbeit?', '[{"text":"Artikel 25","correct":false},{"text":"Artikel 30","correct":false},{"text":"Artikel 35","correct":true},{"text":"Artikel 40","correct":false}]', 'Artikel 35 der spanischen Verfassung begründet das Recht und die Pflicht zu arbeiten, das Recht auf freie Berufswahl und das Recht auf angemessene Vergütung.', 1),
('G-LAB-007', 'de', 'Welches der folgenden ist ein grundlegendes Arbeitnehmerrecht nach spanischem Recht?', '[{"text":"Recht auf ständige Nutzung des persönlichen Mobiltelefons","correct":false},{"text":"Recht auf Nicht-Diskriminierung","correct":true},{"text":"Recht, jede zugewiesene Aufgabe abzulehnen","correct":false},{"text":"Recht, eigene Arbeitszeiten festzulegen","correct":false}]', 'Arbeitnehmer haben grundlegende Rechte einschließlich fairer Bezahlung, Nicht-Diskriminierung, Würde am Arbeitsplatz, Gesundheit und Sicherheit, Gewerkschaftsmitgliedschaft und Information/Konsultation gemäß ET Art. 4.', 2),
('G-LAB-007', 'de', 'Was ist eine wichtige Arbeitnehmerpflicht gemäß Estatuto de los Trabajadores?', '[{"text":"Unternehmensgewinne maximieren","correct":false},{"text":"Unbegrenzte Überstunden arbeiten","correct":false},{"text":"Sicherheitsregeln einhalten","correct":true},{"text":"Neue Mitarbeiter rekrutieren","correct":false}]', 'Arbeitnehmer haben Pflichten einschließlich Gutgläubigkeit, Sorgfalt, Einhaltung von Sicherheitsregeln und Anweisungen sowie Wahrung der Vertraulichkeit von Unternehmensinformationen gemäß ET Art. 5.', 3),
('G-LAB-007', 'de', 'Arbeitnehmer haben das Recht auf Würde am Arbeitsplatz, was Schutz einschließt vor:', '[{"text":"Konstruktiver Kritik","correct":false},{"text":"Belästigung und Diskriminierung","correct":true},{"text":"Leistungsbeurteilungen","correct":false},{"text":"Ausbildungsanforderungen","correct":false}]', 'Das Recht auf Würde am Arbeitsplatz (dignidad) umfasst Schutz vor Belästigung, Diskriminierung und erniedrigender Behandlung, um ein respektvolles Arbeitsumfeld zu gewährleisten.', 4),
('G-LAB-007', 'de', 'Welches Recht haben Arbeitnehmer in Bezug auf Informationen über das Unternehmen?', '[{"text":"Zugang zu allen Unternehmensfinanzdaten","correct":false},{"text":"Information und Konsultation über arbeitsbezogene Angelegenheiten","correct":true},{"text":"Recht auf Teilnahme an allen Managementsitzungen","correct":false},{"text":"Es existieren keine Informationsrechte","correct":false}]', 'Arbeitnehmer haben das Recht auf Information und Konsultation über Angelegenheiten, die Beschäftigung und Arbeitsbedingungen betreffen, einschließlich Unternehmensentscheidungen, die sich auf ihre Arbeitsplätze auswirken können.', 5),
('G-LAB-007', 'de', 'Welche Arbeitnehmerpflicht bezieht sich auf Vertrauen und Ehrlichkeit?', '[{"text":"Guter Glaube (buena fe)","correct":true},{"text":"Maximale Produktivität","correct":false},{"text":"Absoluter Gehorsam","correct":false},{"text":"Unbegrenzte Verfügbarkeit","correct":false}]', 'Die Pflicht zum guten Glauben (buena fe) verlangt von Arbeitnehmern, ehrlich und loyal zu handeln, Pflichten gewissenhaft zu erfüllen und die Arbeitgeber-Arbeitnehmer-Beziehung zu respektieren.', 6),
('G-LAB-007', 'de', 'Was umfasst das Recht auf Arbeitsschutz und -sicherheit?', '[{"text":"Nur Notfallmedizinische Versorgung","correct":false},{"text":"Wirksamer Schutz vor Arbeitsplatzrisiken","correct":true},{"text":"Jährlicher Krankenversicherungsbonus","correct":false},{"text":"Fitnessstudio-Mitgliedschaft","correct":false}]', 'Das Recht auf Arbeitsschutz und -sicherheit umfasst wirksamen Schutz vor Arbeitsplatzrisiken, angemessene PSA, Schulungen, Gesundheitsüberwachung und ein sicheres Arbeitsumfeld gemäß Ley 31/1995.', 7),
('G-LAB-007', 'de', 'Arbeitnehmer haben eine Vertraulichkeitspflicht in Bezug auf:', '[{"text":"Ihre eigenen Gehaltsinformationen","correct":false},{"text":"Geschäftsgeheimnisse und Unternehmensinformationen","correct":true},{"text":"Sicherheitsvorfälle am Arbeitsplatz","correct":false},{"text":"Rechtsverletzungen durch das Unternehmen","correct":false}]', 'Arbeitnehmer müssen die Vertraulichkeit von Geschäftsgeheimnissen und Unternehmensinformationen wahren, die während der Beschäftigung erlernt wurden. Diese Pflicht besteht auch nach Beendigung des Arbeitsverhältnisses für bestimmte sensible Informationen fort.', 8);

-- G-LAB-008: Understanding Your Payroll
INSERT INTO training_test_questions (guide_code, language, question, options, explanation, sort_order) VALUES
('G-LAB-008', 'en', 'What is the Spanish term for a payroll statement?', '[{"text":"Contrato","correct":false},{"text":"Nómina","correct":true},{"text":"Recibo","correct":false},{"text":"Factura","correct":false}]', 'The payroll statement in Spain is called a nómina, which must be provided monthly and shows all salary components, deductions, and net pay.', 1),
('G-LAB-008', 'en', 'Approximately what percentage of gross salary is deducted for Social Security contributions?', '[{"text":"2.5%","correct":false},{"text":"4.5%","correct":false},{"text":"6.35%","correct":true},{"text":"10%","correct":false}]', 'Workers social security contributions (contingencias comunes) are approximately 6.35% of gross salary, covering healthcare, pensions, and unemployment benefits.', 2),
('G-LAB-008', 'en', 'What are "complementos" in a payroll?', '[{"text":"Deductions from salary","correct":false},{"text":"Salary supplements and bonuses","correct":true},{"text":"Tax withholdings","correct":false},{"text":"Social security payments","correct":false}]', 'Complementos are salary supplements added to the base salary, including seniority bonuses, night shift differentials, tips distribution, and other contractual supplements.', 3),
('G-LAB-008', 'en', 'How many extra salary payments (pagas extra) are workers entitled to per year?', '[{"text":"One","correct":false},{"text":"Two","correct":true},{"text":"Three","correct":false},{"text":"Four","correct":false}]', 'Workers are entitled to two extra salary payments (pagas extraordinarias) per year, typically paid in summer (June/July) and Christmas (December), though they can be prorated monthly.', 4),
('G-LAB-008', 'en', 'What does IRPF represent on a payroll?', '[{"text":"Social Security contribution","correct":false},{"text":"Personal income tax withholding","correct":true},{"text":"Pension contribution","correct":false},{"text":"Union dues","correct":false}]', 'IRPF (Impuesto sobre la Renta de las Personas Físicas) is personal income tax withheld at source. The percentage depends on individual circumstances like marital status and dependents.', 5),
('G-LAB-008', 'en', 'What determines the base salary shown on a payroll in hospitality?', '[{"text":"Individual negotiation only","correct":false},{"text":"Professional category per convenio colectivo","correct":true},{"text":"Years of experience only","correct":false},{"text":"Educational qualifications only","correct":false}]', 'The base salary is determined by the workers professional category (categoría profesional) as defined in the applicable Convenio Colectivo de Hostelería for the province.', 6),
('G-LAB-008', 'en', 'What is the difference between gross pay (salario bruto) and net pay (salario neto)?', '[{"text":"Benefits and bonuses","correct":false},{"text":"Deductions for tax and social security","correct":true},{"text":"Overtime hours","correct":false},{"text":"There is no difference","correct":false}]', 'Net pay is gross pay minus all deductions including IRPF tax withholding and social security contributions. This is the actual amount paid to the worker.', 7),
('G-LAB-008', 'en', 'How frequently must employers provide a payroll statement?', '[{"text":"Weekly","correct":false},{"text":"Bi-weekly","correct":false},{"text":"Monthly","correct":true},{"text":"Quarterly","correct":false}]', 'According to ET Art. 29, employers must provide a detailed payroll statement (nómina) monthly, showing all salary components, deductions, and contributions.', 8);

INSERT INTO training_test_questions (guide_code, language, question, options, explanation, sort_order) VALUES
('G-LAB-008', 'es', '¿Cuál es el término español para el recibo de salario?', '[{"text":"Contrato","correct":false},{"text":"Nómina","correct":true},{"text":"Recibo","correct":false},{"text":"Factura","correct":false}]', 'El recibo de salario en España se llama nómina, que debe proporcionarse mensualmente y muestra todos los componentes del salario, deducciones y salario neto.', 1),
('G-LAB-008', 'es', '¿Aproximadamente qué porcentaje del salario bruto se deduce por cotizaciones a la Seguridad Social?', '[{"text":"2,5%","correct":false},{"text":"4,5%","correct":false},{"text":"6,35%","correct":true},{"text":"10%","correct":false}]', 'Las cotizaciones a la seguridad social de los trabajadores (contingencias comunes) son aproximadamente el 6,35% del salario bruto, cubriendo asistencia sanitaria, pensiones y prestaciones por desempleo.', 2),
('G-LAB-008', 'es', '¿Qué son los "complementos" en una nómina?', '[{"text":"Deducciones del salario","correct":false},{"text":"Suplementos salariales y bonificaciones","correct":true},{"text":"Retenciones fiscales","correct":false},{"text":"Pagos de seguridad social","correct":false}]', 'Los complementos son suplementos salariales añadidos al salario base, incluyendo bonos de antigüedad, complementos de nocturnidad, distribución de propinas y otros complementos contractuales.', 3),
('G-LAB-008', 'es', '¿A cuántas pagas extraordinarias tienen derecho los trabajadores por año?', '[{"text":"Una","correct":false},{"text":"Dos","correct":true},{"text":"Tres","correct":false},{"text":"Cuatro","correct":false}]', 'Los trabajadores tienen derecho a dos pagas extraordinarias por año, típicamente pagadas en verano (junio/julio) y Navidad (diciembre), aunque pueden prorratearse mensualmente.', 4),
('G-LAB-008', 'es', '¿Qué representa el IRPF en una nómina?', '[{"text":"Cotización a la Seguridad Social","correct":false},{"text":"Retención del impuesto sobre la renta personal","correct":true},{"text":"Cotización a la pensión","correct":false},{"text":"Cuotas sindicales","correct":false}]', 'El IRPF (Impuesto sobre la Renta de las Personas Físicas) es el impuesto sobre la renta personal retenido en origen. El porcentaje depende de circunstancias individuales como estado civil y personas a cargo.', 5),
('G-LAB-008', 'es', '¿Qué determina el salario base mostrado en una nómina en hostelería?', '[{"text":"Solo negociación individual","correct":false},{"text":"Categoría profesional según el convenio colectivo","correct":true},{"text":"Solo años de experiencia","correct":false},{"text":"Solo cualificaciones educativas","correct":false}]', 'El salario base está determinado por la categoría profesional del trabajador según lo definido en el Convenio Colectivo de Hostelería aplicable de la provincia.', 6),
('G-LAB-008', 'es', '¿Cuál es la diferencia entre salario bruto y salario neto?', '[{"text":"Beneficios y bonificaciones","correct":false},{"text":"Deducciones por impuestos y seguridad social","correct":true},{"text":"Horas extras","correct":false},{"text":"No hay diferencia","correct":false}]', 'El salario neto es el salario bruto menos todas las deducciones, incluyendo la retención del IRPF y las cotizaciones a la seguridad social. Esta es la cantidad real pagada al trabajador.', 7),
('G-LAB-008', 'es', '¿Con qué frecuencia deben los empleadores proporcionar un recibo de nómina?', '[{"text":"Semanalmente","correct":false},{"text":"Quincenalmente","correct":false},{"text":"Mensualmente","correct":true},{"text":"Trimestralmente","correct":false}]', 'Según el ET Art. 29, los empleadores deben proporcionar un recibo de nómina detallado mensualmente, mostrando todos los componentes del salario, deducciones y cotizaciones.', 8);

INSERT INTO training_test_questions (guide_code, language, question, options, explanation, sort_order) VALUES
('G-LAB-008', 'nl', 'Wat is de Spaanse term voor een salarisstrook?', '[{"text":"Contrato","correct":false},{"text":"Nómina","correct":true},{"text":"Recibo","correct":false},{"text":"Factura","correct":false}]', 'De salarisstrook in Spanje heet een nómina, die maandelijks moet worden verstrekt en alle salariscomponenten, inhoudingen en nettoloon toont.', 1),
('G-LAB-008', 'nl', 'Ongeveer welk percentage van het brutosalaris wordt ingehouden voor sociale zekerheidsbijdragen?', '[{"text":"2,5%","correct":false},{"text":"4,5%","correct":false},{"text":"6,35%","correct":true},{"text":"10%","correct":false}]', 'De sociale zekerheidsbijdragen van werknemers (contingencias comunes) bedragen ongeveer 6,35% van het brutosalaris en dekken gezondheidszorg, pensioenen en werkloosheidsuitkeringen.', 2),
('G-LAB-008', 'nl', 'Wat zijn "complementos" op een salarisstrook?', '[{"text":"Inhoudingen op het salaris","correct":false},{"text":"Salaristoelagen en bonussen","correct":true},{"text":"Belastinginhoudingen","correct":false},{"text":"Sociale zekerheidsbetalingen","correct":false}]', 'Complementos zijn salaristoelagen die aan het basissalaris worden toegevoegd, waaronder anciënniteitsbonussen, nachtdiensttoelagen, fooienverdeling en andere contractuele toeslagen.', 3),
('G-LAB-008', 'nl', 'Hoeveel extra salarisbetalingen (pagas extra) hebben werknemers recht op per jaar?', '[{"text":"Eén","correct":false},{"text":"Twee","correct":true},{"text":"Drie","correct":false},{"text":"Vier","correct":false}]', 'Werknemers hebben recht op twee extra salarisbetalingen (pagas extraordinarias) per jaar, meestal betaald in de zomer (juni/juli) en kerst (december), hoewel ze maandelijks kunnen worden verdeeld.', 4),
('G-LAB-008', 'nl', 'Wat vertegenwoordigt IRPF op een salarisstrook?', '[{"text":"Sociale zekerheidsbijdrage","correct":false},{"text":"Inkomstenbelastinginhouding","correct":true},{"text":"Pensioenbijdrage","correct":false},{"text":"Vakbondscontributies","correct":false}]', 'IRPF (Impuesto sobre la Renta de las Personas Físicas) is de ingehouden inkomstenbelasting aan de bron. Het percentage hangt af van individuele omstandigheden zoals burgerlijke staat en afhankelijke personen.', 5),
('G-LAB-008', 'nl', 'Wat bepaalt het basissalaris dat op een salarisstrook in de horeca wordt getoond?', '[{"text":"Alleen individuele onderhandeling","correct":false},{"text":"Professionele categorie volgens convenio colectivo","correct":true},{"text":"Alleen jaren ervaring","correct":false},{"text":"Alleen onderwijskwalificaties","correct":false}]', 'Het basissalaris wordt bepaald door de professionele categorie (categoría profesional) van de werknemer zoals gedefinieerd in het toepasselijke Convenio Colectivo de Hostelería voor de provincie.', 6),
('G-LAB-008', 'nl', 'Wat is het verschil tussen brutosalaris (salario bruto) en nettosalaris (salario neto)?', '[{"text":"Voordelen en bonussen","correct":false},{"text":"Inhoudingen voor belasting en sociale zekerheid","correct":true},{"text":"Overuren","correct":false},{"text":"Er is geen verschil","correct":false}]', 'Nettosalaris is brutosalaris minus alle inhoudingen, inclusief IRPF-belastinginhouding en sociale zekerheidsbijdragen. Dit is het werkelijke bedrag dat aan de werknemer wordt betaald.', 7),
('G-LAB-008', 'nl', 'Hoe vaak moeten werkgevers een salarisstrook verstrekken?', '[{"text":"Wekelijks","correct":false},{"text":"Tweewekelijks","correct":false},{"text":"Maandelijks","correct":true},{"text":"Per kwartaal","correct":false}]', 'Volgens ET Art. 29 moeten werkgevers maandelijks een gedetailleerde salarisstrook (nómina) verstrekken, waarin alle salariscomponenten, inhoudingen en bijdragen worden getoond.', 8);

INSERT INTO training_test_questions (guide_code, language, question, options, explanation, sort_order) VALUES
('G-LAB-008', 'de', 'Was ist die spanische Bezeichnung für eine Gehaltsabrechnung?', '[{"text":"Contrato","correct":false},{"text":"Nómina","correct":true},{"text":"Recibo","correct":false},{"text":"Factura","correct":false}]', 'Die Gehaltsabrechnung in Spanien heißt nómina und muss monatlich bereitgestellt werden. Sie zeigt alle Gehaltsbestandteile, Abzüge und Nettolohn.', 1),
('G-LAB-008', 'de', 'Ungefähr welcher Prozentsatz des Bruttogehalts wird für Sozialversicherungsbeiträge abgezogen?', '[{"text":"2,5%","correct":false},{"text":"4,5%","correct":false},{"text":"6,35%","correct":true},{"text":"10%","correct":false}]', 'Die Sozialversicherungsbeiträge der Arbeitnehmer (contingencias comunes) betragen etwa 6,35% des Bruttogehalts und decken Gesundheitsversorgung, Renten und Arbeitslosenleistungen ab.', 2),
('G-LAB-008', 'de', 'Was sind "complementos" in einer Gehaltsabrechnung?', '[{"text":"Gehaltsabzüge","correct":false},{"text":"Gehaltszulagen und Boni","correct":true},{"text":"Steuerabzüge","correct":false},{"text":"Sozialversicherungszahlungen","correct":false}]', 'Complementos sind Gehaltszulagen, die zum Grundgehalt hinzugefügt werden, einschließlich Dienstaltersboni, Nachtschichtzulagen, Trinkgeldverteilung und andere vertragliche Zulagen.', 3),
('G-LAB-008', 'de', 'Auf wie viele Sonderzahlungen (pagas extra) haben Arbeitnehmer pro Jahr Anspruch?', '[{"text":"Eine","correct":false},{"text":"Zwei","correct":true},{"text":"Drei","correct":false},{"text":"Vier","correct":false}]', 'Arbeitnehmer haben Anspruch auf zwei Sonderzahlungen (pagas extraordinarias) pro Jahr, die typischerweise im Sommer (Juni/Juli) und zu Weihnachten (Dezember) gezahlt werden, obwohl sie monatlich aufgeteilt werden können.', 4),
('G-LAB-008', 'de', 'Was stellt IRPF auf einer Gehaltsabrechnung dar?', '[{"text":"Sozialversicherungsbeitrag","correct":false},{"text":"Einkommensteuerabzug","correct":true},{"text":"Rentenbeitrag","correct":false},{"text":"Gewerkschaftsbeiträge","correct":false}]', 'IRPF (Impuesto sobre la Renta de las Personas Físicas) ist die an der Quelle einbehaltene Einkommensteuer. Der Prozentsatz hängt von individuellen Umständen wie Familienstand und unterhaltsberechtigten Personen ab.', 5),
('G-LAB-008', 'de', 'Was bestimmt das Grundgehalt, das auf einer Gehaltsabrechnung im Gastgewerbe angezeigt wird?', '[{"text":"Nur individuelle Verhandlung","correct":false},{"text":"Berufskategorie gemäß convenio colectivo","correct":true},{"text":"Nur Jahre der Erfahrung","correct":false},{"text":"Nur Bildungsqualifikationen","correct":false}]', 'Das Grundgehalt wird durch die Berufskategorie (categoría profesional) des Arbeitnehmers bestimmt, wie im geltenden Convenio Colectivo de Hostelería für die Provinz definiert.', 6),
('G-LAB-008', 'de', 'Was ist der Unterschied zwischen Bruttogehalt (salario bruto) und Nettogehalt (salario neto)?', '[{"text":"Leistungen und Boni","correct":false},{"text":"Abzüge für Steuern und Sozialversicherung","correct":true},{"text":"Überstunden","correct":false},{"text":"Es gibt keinen Unterschied","correct":false}]', 'Nettogehalt ist Bruttogehalt minus aller Abzüge einschließlich IRPF-Steuerabzug und Sozialversicherungsbeiträge. Dies ist der tatsächliche Betrag, der an den Arbeitnehmer gezahlt wird.', 7),
('G-LAB-008', 'de', 'Wie häufig müssen Arbeitgeber eine Gehaltsabrechnung bereitstellen?', '[{"text":"Wöchentlich","correct":false},{"text":"Zweiwöchentlich","correct":false},{"text":"Monatlich","correct":true},{"text":"Vierteljährlich","correct":false}]', 'Gemäß ET Art. 29 müssen Arbeitgeber monatlich eine detaillierte Gehaltsabrechnung (nómina) bereitstellen, die alle Gehaltsbestandteile, Abzüge und Beiträge zeigt.', 8);

-- G-LAB-009: Social Security
INSERT INTO training_test_questions (guide_code, language, question, options, explanation, sort_order) VALUES
('G-LAB-009', 'en', 'What is the legal basis for Social Security in Spain?', '[{"text":"Estatuto de los Trabajadores","correct":false},{"text":"Ley General de la Seguridad Social","correct":true},{"text":"RD-ley 8/2019","correct":false},{"text":"Constitución Española","correct":false}]', 'The Ley General de la Seguridad Social (RD Legislativo 8/2015) is the comprehensive legal framework governing social security in Spain, covering registration, contributions, and benefits.', 1),
('G-LAB-009', 'en', 'Who is responsible for registering a worker with Social Security?', '[{"text":"The worker themselves","correct":false},{"text":"The employer","correct":true},{"text":"The trade union","correct":false},{"text":"The local municipality","correct":false}]', 'The employer is legally responsible for registering workers with Social Security before they begin work and for making all required contributions on behalf of the worker.', 2),
('G-LAB-009', 'en', 'What does Social Security coverage include in Spain?', '[{"text":"Only pension benefits","correct":false},{"text":"Healthcare, pensions, unemployment, and sick leave","correct":true},{"text":"Only healthcare","correct":false},{"text":"Only unemployment benefits","correct":false}]', 'Spanish social security provides comprehensive coverage including healthcare (asistencia sanitaria), retirement pensions, unemployment benefits, sick leave, maternity/paternity leave, and disability benefits.', 3),
('G-LAB-009', 'en', 'From what point must a worker be registered with Social Security?', '[{"text":"Within the first week of employment","correct":false},{"text":"Day one of employment","correct":true},{"text":"After the probation period","correct":false},{"text":"After one month of employment","correct":false}]', 'Social Security registration is mandatory from day one of employment, before the worker begins their duties. Working without registration is a serious labor infraction.', 4),
('G-LAB-009', 'en', 'What is the "Informe de Vida Laboral"?', '[{"text":"Employment contract","correct":false},{"text":"Working life report showing employment history","correct":true},{"text":"Payroll statement","correct":false},{"text":"Job reference letter","correct":false}]', 'The Informe de Vida Laboral is an official report showing a workers complete employment history, including all periods of work, contributions, and unemployment. Workers should verify it periodically.', 5),
('G-LAB-009', 'en', 'What should a worker do if they discover irregularities in their Social Security registration?', '[{"text":"Ignore it","correct":false},{"text":"Report it to Social Security authorities","correct":true},{"text":"Wait until end of employment","correct":false},{"text":"Only tell coworkers","correct":false}]', 'Any irregularities in Social Security registration (missing periods, incorrect contributions) should be reported immediately to Social Security (Seguridad Social) or labor authorities to protect the workers rights.', 6),
('G-LAB-009', 'en', 'What is the Social Security number in Spain called?', '[{"text":"DNI","correct":false},{"text":"NIE","correct":false},{"text":"Número de la Seguridad Social","correct":true},{"text":"NIF","correct":false}]', 'The Número de la Seguridad Social (Social Security number) is a unique identifier assigned to each registered worker. It should be kept safe and is required for all employment and benefit claims.', 7),
('G-LAB-009', 'en', 'How often should workers check their "Vida Laboral" report?', '[{"text":"Never necessary","correct":false},{"text":"Periodically to verify accuracy","correct":true},{"text":"Only when changing jobs","correct":false},{"text":"Only at retirement","correct":false}]', 'Workers should periodically verify their Informe de Vida Laboral to ensure all employment periods are correctly registered and contributions properly recorded, protecting future pension and benefit rights.', 8);

INSERT INTO training_test_questions (guide_code, language, question, options, explanation, sort_order) VALUES
('G-LAB-009', 'es', '¿Cuál es la base legal de la Seguridad Social en España?', '[{"text":"Estatuto de los Trabajadores","correct":false},{"text":"Ley General de la Seguridad Social","correct":true},{"text":"RD-ley 8/2019","correct":false},{"text":"Constitución Española","correct":false}]', 'La Ley General de la Seguridad Social (RD Legislativo 8/2015) es el marco legal integral que regula la seguridad social en España, cubriendo registro, cotizaciones y prestaciones.', 1),
('G-LAB-009', 'es', '¿Quién es responsable de dar de alta a un trabajador en la Seguridad Social?', '[{"text":"El propio trabajador","correct":false},{"text":"El empleador","correct":true},{"text":"El sindicato","correct":false},{"text":"El municipio local","correct":false}]', 'El empleador es legalmente responsable de dar de alta a los trabajadores en la Seguridad Social antes de que comiencen a trabajar y de realizar todas las cotizaciones requeridas en nombre del trabajador.', 2),
('G-LAB-009', 'es', '¿Qué incluye la cobertura de la Seguridad Social en España?', '[{"text":"Solo prestaciones de pensión","correct":false},{"text":"Asistencia sanitaria, pensiones, desempleo e incapacidad temporal","correct":true},{"text":"Solo asistencia sanitaria","correct":false},{"text":"Solo prestaciones por desempleo","correct":false}]', 'La seguridad social española proporciona cobertura integral incluyendo asistencia sanitaria, pensiones de jubilación, prestaciones por desempleo, incapacidad temporal, maternidad/paternidad y prestaciones por discapacidad.', 3),
('G-LAB-009', 'es', '¿Desde qué momento debe estar un trabajador dado de alta en la Seguridad Social?', '[{"text":"Durante la primera semana de empleo","correct":false},{"text":"Desde el primer día de empleo","correct":true},{"text":"Después del período de prueba","correct":false},{"text":"Después de un mes de empleo","correct":false}]', 'El alta en la Seguridad Social es obligatoria desde el primer día de empleo, antes de que el trabajador comience sus funciones. Trabajar sin estar dado de alta es una infracción laboral grave.', 4),
('G-LAB-009', 'es', '¿Qué es el "Informe de Vida Laboral"?', '[{"text":"Contrato de trabajo","correct":false},{"text":"Informe de vida laboral que muestra el historial de empleo","correct":true},{"text":"Recibo de nómina","correct":false},{"text":"Carta de referencia laboral","correct":false}]', 'El Informe de Vida Laboral es un informe oficial que muestra el historial de empleo completo de un trabajador, incluyendo todos los períodos de trabajo, cotizaciones y desempleo. Los trabajadores deben verificarlo periódicamente.', 5),
('G-LAB-009', 'es', '¿Qué debe hacer un trabajador si descubre irregularidades en su registro de Seguridad Social?', '[{"text":"Ignorarlo","correct":false},{"text":"Reportarlo a las autoridades de Seguridad Social","correct":true},{"text":"Esperar hasta el final del empleo","correct":false},{"text":"Solo decírselo a compañeros de trabajo","correct":false}]', 'Cualquier irregularidad en el registro de Seguridad Social (períodos faltantes, cotizaciones incorrectas) debe reportarse inmediatamente a la Seguridad Social o autoridades laborales para proteger los derechos del trabajador.', 6),
('G-LAB-009', 'es', '¿Cómo se llama el número de la Seguridad Social en España?', '[{"text":"DNI","correct":false},{"text":"NIE","correct":false},{"text":"Número de la Seguridad Social","correct":true},{"text":"NIF","correct":false}]', 'El Número de la Seguridad Social es un identificador único asignado a cada trabajador registrado. Debe guardarse de forma segura y es necesario para todo empleo y reclamaciones de prestaciones.', 7),
('G-LAB-009', 'es', '¿Con qué frecuencia deben los trabajadores revisar su informe de "Vida Laboral"?', '[{"text":"Nunca es necesario","correct":false},{"text":"Periódicamente para verificar la exactitud","correct":true},{"text":"Solo al cambiar de trabajo","correct":false},{"text":"Solo al jubilarse","correct":false}]', 'Los trabajadores deben verificar periódicamente su Informe de Vida Laboral para asegurar que todos los períodos de empleo estén correctamente registrados y las cotizaciones debidamente registradas, protegiendo futuros derechos de pensión y prestaciones.', 8);

INSERT INTO training_test_questions (guide_code, language, question, options, explanation, sort_order) VALUES
('G-LAB-009', 'nl', 'Wat is de wettelijke basis voor sociale zekerheid in Spanje?', '[{"text":"Estatuto de los Trabajadores","correct":false},{"text":"Ley General de la Seguridad Social","correct":true},{"text":"RD-ley 8/2019","correct":false},{"text":"Constitución Española","correct":false}]', 'De Ley General de la Seguridad Social (RD Legislativo 8/2015) is het uitgebreide juridische kader voor sociale zekerheid in Spanje, dat registratie, bijdragen en uitkeringen regelt.', 1),
('G-LAB-009', 'nl', 'Wie is verantwoordelijk voor het registreren van een werknemer bij de sociale zekerheid?', '[{"text":"De werknemer zelf","correct":false},{"text":"De werkgever","correct":true},{"text":"De vakbond","correct":false},{"text":"De lokale gemeente","correct":false}]', 'De werkgever is wettelijk verantwoordelijk voor het registreren van werknemers bij de sociale zekerheid voordat ze beginnen met werken en voor het betalen van alle vereiste bijdragen namens de werknemer.', 2),
('G-LAB-009', 'nl', 'Wat omvat de sociale zekerheidsdekking in Spanje?', '[{"text":"Alleen pensioenuitkeringen","correct":false},{"text":"Gezondheidszorg, pensioenen, werkloosheid en ziekteverlof","correct":true},{"text":"Alleen gezondheidszorg","correct":false},{"text":"Alleen werkloosheidsuitkeringen","correct":false}]', 'De Spaanse sociale zekerheid biedt uitgebreide dekking inclusief gezondheidszorg (asistencia sanitaria), pensioenen, werkloosheidsuitkeringen, ziekteverlof, zwangerschaps-/vaderschapsverlof en arbeidsongeschiktheidsuitkeringen.', 3),
('G-LAB-009', 'nl', 'Vanaf welk moment moet een werknemer geregistreerd zijn bij de sociale zekerheid?', '[{"text":"Binnen de eerste week van dienstverband","correct":false},{"text":"Dag één van dienstverband","correct":true},{"text":"Na de proeftijd","correct":false},{"text":"Na één maand dienstverband","correct":false}]', 'Registratie bij de sociale zekerheid is verplicht vanaf dag één van het dienstverband, voordat de werknemer zijn taken begint. Werken zonder registratie is een ernstige arbeidsovertreding.', 4),
('G-LAB-009', 'nl', 'Wat is het "Informe de Vida Laboral"?', '[{"text":"Arbeidscontract","correct":false},{"text":"Arbeidsgeschiedenisrapport dat de werkgeschiedenis toont","correct":true},{"text":"Salarisstrook","correct":false},{"text":"Arbeidsreferentiebrief","correct":false}]', 'Het Informe de Vida Laboral is een officieel rapport dat de volledige arbeidsgeschiedenis van een werknemer toont, inclusief alle arbeidsperiodes, bijdragen en werkloosheid. Werknemers moeten het periodiek verifiëren.', 5),
('G-LAB-009', 'nl', 'Wat moet een werknemer doen als ze onregelmatigheden ontdekken in hun sociale zekerheidsregistratie?', '[{"text":"Negeren","correct":false},{"text":"Rapporteren aan de sociale zekerheidsautoriteiten","correct":true},{"text":"Wachten tot einde van dienstverband","correct":false},{"text":"Alleen collega\'s vertellen","correct":false}]', 'Eventuele onregelmatigheden in de sociale zekerheidsregistratie (ontbrekende periodes, onjuiste bijdragen) moeten onmiddellijk worden gemeld bij de sociale zekerheid (Seguridad Social) of arbeidsautoriteiten om de rechten van de werknemer te beschermen.', 6),
('G-LAB-009', 'nl', 'Hoe heet het sociale zekerheidsnummer in Spanje?', '[{"text":"DNI","correct":false},{"text":"NIE","correct":false},{"text":"Número de la Seguridad Social","correct":true},{"text":"NIF","correct":false}]', 'Het Número de la Seguridad Social (sociale zekerheidsnummer) is een unieke identificatie die aan elke geregistreerde werknemer wordt toegewezen. Het moet veilig worden bewaard en is vereist voor alle arbeids- en uitkeringsclaims.', 7),
('G-LAB-009', 'nl', 'Hoe vaak moeten werknemers hun "Vida Laboral" rapport controleren?', '[{"text":"Nooit nodig","correct":false},{"text":"Periodiek om nauwkeurigheid te verifiëren","correct":true},{"text":"Alleen bij het wisselen van baan","correct":false},{"text":"Alleen bij pensionering","correct":false}]', 'Werknemers moeten periodiek hun Informe de Vida Laboral verifiëren om ervoor te zorgen dat alle arbeidsperiodes correct zijn geregistreerd en bijdragen goed zijn vastgelegd, ter bescherming van toekomstige pensioen- en uitkeringsrechten.', 8);

INSERT INTO training_test_questions (guide_code, language, question, options, explanation, sort_order) VALUES
('G-LAB-009', 'de', 'Was ist die Rechtsgrundlage für die Sozialversicherung in Spanien?', '[{"text":"Estatuto de los Trabajadores","correct":false},{"text":"Ley General de la Seguridad Social","correct":true},{"text":"RD-ley 8/2019","correct":false},{"text":"Constitución Española","correct":false}]', 'Die Ley General de la Seguridad Social (RD Legislativo 8/2015) ist der umfassende rechtliche Rahmen für die Sozialversicherung in Spanien, der Registrierung, Beiträge und Leistungen regelt.', 1),
('G-LAB-009', 'de', 'Wer ist für die Anmeldung eines Arbeitnehmers bei der Sozialversicherung verantwortlich?', '[{"text":"Der Arbeitnehmer selbst","correct":false},{"text":"Der Arbeitgeber","correct":true},{"text":"Die Gewerkschaft","correct":false},{"text":"Die örtliche Gemeinde","correct":false}]', 'Der Arbeitgeber ist gesetzlich verpflichtet, Arbeitnehmer vor Arbeitsbeginn bei der Sozialversicherung anzumelden und alle erforderlichen Beiträge im Namen des Arbeitnehmers zu zahlen.', 2),
('G-LAB-009', 'de', 'Was umfasst die Sozialversicherungsdeckung in Spanien?', '[{"text":"Nur Rentenleistungen","correct":false},{"text":"Gesundheitsversorgung, Renten, Arbeitslosigkeit und Krankengeld","correct":true},{"text":"Nur Gesundheitsversorgung","correct":false},{"text":"Nur Arbeitslosenleistungen","correct":false}]', 'Die spanische Sozialversicherung bietet umfassenden Schutz einschließlich Gesundheitsversorgung (asistencia sanitaria), Altersrenten, Arbeitslosengeld, Krankengeld, Mutterschafts-/Vaterschaftsurlaub und Invaliditätsleistungen.', 3),
('G-LAB-009', 'de', 'Ab welchem Zeitpunkt muss ein Arbeitnehmer bei der Sozialversicherung angemeldet sein?', '[{"text":"Innerhalb der ersten Arbeitswoche","correct":false},{"text":"Ab dem ersten Arbeitstag","correct":true},{"text":"Nach der Probezeit","correct":false},{"text":"Nach einem Monat Beschäftigung","correct":false}]', 'Die Anmeldung bei der Sozialversicherung ist ab dem ersten Arbeitstag verpflichtend, bevor der Arbeitnehmer seine Tätigkeiten aufnimmt. Arbeit ohne Anmeldung ist eine schwerwiegende Arbeitsrechtsübertretung.', 4),
('G-LAB-009', 'de', 'Was ist das "Informe de Vida Laboral"?', '[{"text":"Arbeitsvertrag","correct":false},{"text":"Arbeitslebensbericht, der die Beschäftigungsgeschichte zeigt","correct":true},{"text":"Gehaltsabrechnung","correct":false},{"text":"Arbeitsreferenzschreiben","correct":false}]', 'Das Informe de Vida Laboral ist ein offizieller Bericht, der die vollständige Beschäftigungsgeschichte eines Arbeitnehmers zeigt, einschließlich aller Beschäftigungsperioden, Beiträge und Arbeitslosigkeit. Arbeitnehmer sollten ihn regelmäßig überprüfen.', 5),
('G-LAB-009', 'de', 'Was sollte ein Arbeitnehmer tun, wenn er Unregelmäßigkeiten in seiner Sozialversicherungsanmeldung entdeckt?', '[{"text":"Ignorieren","correct":false},{"text":"Den Sozialversicherungsbehörden melden","correct":true},{"text":"Bis zum Ende der Beschäftigung warten","correct":false},{"text":"Nur Kollegen erzählen","correct":false}]', 'Jegliche Unregelmäßigkeiten in der Sozialversicherungsanmeldung (fehlende Perioden, falsche Beiträge) sollten sofort der Sozialversicherung (Seguridad Social) oder den Arbeitsbehörden gemeldet werden, um die Rechte des Arbeitnehmers zu schützen.', 6),
('G-LAB-009', 'de', 'Wie heißt die Sozialversicherungsnummer in Spanien?', '[{"text":"DNI","correct":false},{"text":"NIE","correct":false},{"text":"Número de la Seguridad Social","correct":true},{"text":"NIF","correct":false}]', 'Die Número de la Seguridad Social (Sozialversicherungsnummer) ist eine eindeutige Kennung, die jedem registrierten Arbeitnehmer zugewiesen wird. Sie sollte sicher aufbewahrt werden und ist für alle Beschäftigungs- und Leistungsansprüche erforderlich.', 7),
('G-LAB-009', 'de', 'Wie oft sollten Arbeitnehmer ihren "Vida Laboral" Bericht überprüfen?', '[{"text":"Nie notwendig","correct":false},{"text":"Regelmäßig zur Überprüfung der Richtigkeit","correct":true},{"text":"Nur beim Jobwechsel","correct":false},{"text":"Nur bei Renteneintritt","correct":false}]', 'Arbeitnehmer sollten ihren Informe de Vida Laboral regelmäßig überprüfen, um sicherzustellen, dass alle Beschäftigungsperioden korrekt registriert und Beiträge ordnungsgemäß erfasst sind, um zukünftige Renten- und Leistungsansprüche zu schützen.', 8);
