-- Training test questions for role-specific guides (ROL 8-14)
-- Generated: 2026-02-08
-- 7 guides × 8 questions × 4 languages = 224 rows

-- G-ROL-008: Dining Room Tray Handling
INSERT INTO training_test_questions (guide_code, language, question, options, explanation, sort_order) VALUES

-- English
('G-ROL-008', 'en', 'What is the correct way to carry a heavy tray?', '[{"text":"One hand above shoulder height","correct":false},{"text":"Support with both hands","correct":true},{"text":"Balance on fingertips","correct":false},{"text":"Carry at arm''s length","correct":false}]', 'Heavy trays should be supported with both hands to maintain proper control and prevent strain or injury.', 1),
('G-ROL-008', 'en', 'When loading a tray, how should you distribute the weight?', '[{"text":"All items on one side","correct":false},{"text":"Heaviest items on the edges","correct":false},{"text":"Evenly distributed across the tray","correct":true},{"text":"Random placement is fine","correct":false}]', 'Proper weight distribution prevents the tray from tipping and makes it easier to carry safely.', 2),
('G-ROL-008', 'en', 'Before picking up a tray, you should always:', '[{"text":"Check your route and be aware of obstacles","correct":true},{"text":"Load it as full as possible","correct":false},{"text":"Rush to save time","correct":false},{"text":"Lift with your back bent","correct":false}]', 'Route awareness prevents collisions and allows you to navigate safely with a loaded tray.', 3),
('G-ROL-008', 'en', 'What should you do if a tray is too heavy?', '[{"text":"Try to carry it anyway","correct":false},{"text":"Use tray stands or make multiple trips","correct":true},{"text":"Ask customers to help","correct":false},{"text":"Drag it across surfaces","correct":false}]', 'Tray stands should be used for heavy loads, or items should be split into multiple trips to prevent injury.', 4),
('G-ROL-008', 'en', 'Which of the following is a hazard when carrying trays?', '[{"text":"Wet floors and uneven surfaces","correct":true},{"text":"Proper lighting","correct":false},{"text":"Empty dining room","correct":false},{"text":"Clean tray surface","correct":false}]', 'Wet floors and uneven surfaces significantly increase the risk of slipping and dropping the tray.', 5),
('G-ROL-008', 'en', 'The legal basis for tray handling safety comes from:', '[{"text":"Local restaurant guidelines","correct":false},{"text":"Ley 31/1995 and RD 487/1997","correct":true},{"text":"Customer preference rules","correct":false},{"text":"International hotel standards","correct":false}]', 'These regulations cover occupational safety and manual handling of loads in the workplace.', 6),
('G-ROL-008', 'en', 'When should you report overloading situations?', '[{"text":"Only after an accident occurs","correct":false},{"text":"Never, it''s expected in busy periods","correct":false},{"text":"Immediately when you notice them","correct":true},{"text":"At the end of your shift","correct":false}]', 'Overloading situations should be reported immediately to prevent injuries and improve work practices.', 7),
('G-ROL-008', 'en', 'What is the proper body mechanics when lifting a tray?', '[{"text":"Bend at the waist with straight legs","correct":false},{"text":"Keep your back straight and lift with your legs","correct":true},{"text":"Twist while lifting","correct":false},{"text":"Lock your knees while carrying","correct":false}]', 'Proper lifting technique with straight back and leg power prevents back injuries.', 8),

-- Spanish
('G-ROL-008', 'es', '¿Cuál es la forma correcta de llevar una bandeja pesada?', '[{"text":"Una mano por encima del hombro","correct":false},{"text":"Sujetar con ambas manos","correct":true},{"text":"Equilibrar sobre las puntas de los dedos","correct":false},{"text":"Llevar a distancia del brazo","correct":false}]', 'Las bandejas pesadas deben sujetarse con ambas manos para mantener el control adecuado y prevenir tensión o lesiones.', 1),
('G-ROL-008', 'es', 'Al cargar una bandeja, ¿cómo debe distribuir el peso?', '[{"text":"Todos los artículos en un lado","correct":false},{"text":"Los artículos más pesados en los bordes","correct":false},{"text":"Distribuido uniformemente en la bandeja","correct":true},{"text":"La colocación aleatoria está bien","correct":false}]', 'La distribución adecuada del peso evita que la bandeja se vuelque y facilita su transporte seguro.', 2),
('G-ROL-008', 'es', 'Antes de recoger una bandeja, siempre debe:', '[{"text":"Verificar su ruta y estar consciente de obstáculos","correct":true},{"text":"Cargarla lo más llena posible","correct":false},{"text":"Apresurarse para ahorrar tiempo","correct":false},{"text":"Levantar con la espalda doblada","correct":false}]', 'La conciencia de la ruta previene colisiones y le permite navegar de forma segura con una bandeja cargada.', 3),
('G-ROL-008', 'es', '¿Qué debe hacer si una bandeja es demasiado pesada?', '[{"text":"Intentar llevarla de todos modos","correct":false},{"text":"Usar soportes de bandeja o hacer múltiples viajes","correct":true},{"text":"Pedir a los clientes que ayuden","correct":false},{"text":"Arrastrarla sobre las superficies","correct":false}]', 'Se deben usar soportes de bandeja para cargas pesadas, o dividir los artículos en múltiples viajes para prevenir lesiones.', 4),
('G-ROL-008', 'es', '¿Cuál de los siguientes es un peligro al llevar bandejas?', '[{"text":"Pisos mojados y superficies irregulares","correct":true},{"text":"Iluminación adecuada","correct":false},{"text":"Comedor vacío","correct":false},{"text":"Superficie limpia de bandeja","correct":false}]', 'Los pisos mojados y las superficies irregulares aumentan significativamente el riesgo de resbalar y dejar caer la bandeja.', 5),
('G-ROL-008', 'es', 'La base legal para la seguridad en el manejo de bandejas proviene de:', '[{"text":"Directrices locales de restaurantes","correct":false},{"text":"Ley 31/1995 y RD 487/1997","correct":true},{"text":"Reglas de preferencia del cliente","correct":false},{"text":"Estándares internacionales de hoteles","correct":false}]', 'Estas regulaciones cubren la seguridad laboral y el manejo manual de cargas en el lugar de trabajo.', 6),
('G-ROL-008', 'es', '¿Cuándo debe reportar situaciones de sobrecarga?', '[{"text":"Solo después de que ocurra un accidente","correct":false},{"text":"Nunca, se espera en períodos ocupados","correct":false},{"text":"Inmediatamente cuando las note","correct":true},{"text":"Al final de su turno","correct":false}]', 'Las situaciones de sobrecarga deben reportarse inmediatamente para prevenir lesiones y mejorar las prácticas laborales.', 7),
('G-ROL-008', 'es', '¿Cuál es la mecánica corporal adecuada al levantar una bandeja?', '[{"text":"Doblar la cintura con piernas rectas","correct":false},{"text":"Mantener la espalda recta y levantar con las piernas","correct":true},{"text":"Girar mientras levanta","correct":false},{"text":"Bloquear las rodillas mientras lleva","correct":false}]', 'La técnica adecuada de levantamiento con espalda recta y fuerza de las piernas previene lesiones de espalda.', 8),

-- Dutch
('G-ROL-008', 'nl', 'Wat is de juiste manier om een zwaar dienblad te dragen?', '[{"text":"Eén hand boven schouderhoogte","correct":false},{"text":"Ondersteunen met beide handen","correct":true},{"text":"Balanceren op vingertoppen","correct":false},{"text":"Dragen op armlengte","correct":false}]', 'Zware dienbladen moeten met beide handen worden ondersteund om goede controle te behouden en spanning of letsel te voorkomen.', 1),
('G-ROL-008', 'nl', 'Hoe moet u bij het laden van een dienblad het gewicht verdelen?', '[{"text":"Alle items aan één kant","correct":false},{"text":"Zwaarste items aan de randen","correct":false},{"text":"Gelijkmatig verdeeld over het dienblad","correct":true},{"text":"Willekeurige plaatsing is prima","correct":false}]', 'Juiste gewichtsverdeling voorkomt dat het dienblad kantelt en maakt het gemakkelijker om veilig te dragen.', 2),
('G-ROL-008', 'nl', 'Voordat u een dienblad oppakt, moet u altijd:', '[{"text":"Uw route controleren en obstakels opmerken","correct":true},{"text":"Het zo vol mogelijk laden","correct":false},{"text":"Haasten om tijd te besparen","correct":false},{"text":"Tillen met gebogen rug","correct":false}]', 'Routebewustzijn voorkomt botsingen en stelt u in staat veilig te navigeren met een geladen dienblad.', 3),
('G-ROL-008', 'nl', 'Wat moet u doen als een dienblad te zwaar is?', '[{"text":"Proberen het toch te dragen","correct":false},{"text":"Dienblad standaards gebruiken of meerdere ritten maken","correct":true},{"text":"Klanten vragen om te helpen","correct":false},{"text":"Het over oppervlakken slepen","correct":false}]', 'Dienblad standaards moeten worden gebruikt voor zware lasten, of items moeten worden verdeeld over meerdere ritten om letsel te voorkomen.', 4),
('G-ROL-008', 'nl', 'Welk van het volgende is een gevaar bij het dragen van dienbladen?', '[{"text":"Natte vloeren en oneffen oppervlakken","correct":true},{"text":"Goede verlichting","correct":false},{"text":"Lege eetkamer","correct":false},{"text":"Schoon dienblad oppervlak","correct":false}]', 'Natte vloeren en oneffen oppervlakken verhogen het risico op uitglijden en het laten vallen van het dienblad aanzienlijk.', 5),
('G-ROL-008', 'nl', 'De wettelijke basis voor veiligheid bij dienblad hanteren komt van:', '[{"text":"Lokale restaurantrichtlijnen","correct":false},{"text":"Ley 31/1995 en RD 487/1997","correct":true},{"text":"Klantvoorkeursregels","correct":false},{"text":"Internationale hotelstandaarden","correct":false}]', 'Deze regelgeving dekt arbeidsveiligheid en handmatig hanteren van lasten op de werkplek.', 6),
('G-ROL-008', 'nl', 'Wanneer moet u overbeladingssituaties melden?', '[{"text":"Alleen nadat een ongeval is gebeurd","correct":false},{"text":"Nooit, het wordt verwacht in drukke periodes","correct":false},{"text":"Onmiddellijk wanneer u ze opmerkt","correct":true},{"text":"Aan het einde van uw dienst","correct":false}]', 'Overbeladingssituaties moeten onmiddellijk worden gemeld om letsel te voorkomen en werkpraktijken te verbeteren.', 7),
('G-ROL-008', 'nl', 'Wat is de juiste lichaamsmechanica bij het tillen van een dienblad?', '[{"text":"Buigen bij de taille met rechte benen","correct":false},{"text":"Uw rug recht houden en tillen met uw benen","correct":true},{"text":"Draaien tijdens het tillen","correct":false},{"text":"Uw knieën vergrendelen tijdens het dragen","correct":false}]', 'Juiste tiltechniek met rechte rug en beenkracht voorkomt rugletsel.', 8),

-- German
('G-ROL-008', 'de', 'Was ist der richtige Weg, ein schweres Tablett zu tragen?', '[{"text":"Eine Hand über Schulterhöhe","correct":false},{"text":"Mit beiden Händen stützen","correct":true},{"text":"Auf Fingerspitzen balancieren","correct":false},{"text":"Auf Armlänge tragen","correct":false}]', 'Schwere Tabletts sollten mit beiden Händen gestützt werden, um die richtige Kontrolle zu behalten und Belastung oder Verletzungen zu vermeiden.', 1),
('G-ROL-008', 'de', 'Beim Beladen eines Tabletts, wie sollten Sie das Gewicht verteilen?', '[{"text":"Alle Gegenstände auf einer Seite","correct":false},{"text":"Schwerste Gegenstände an den Rändern","correct":false},{"text":"Gleichmäßig über das Tablett verteilt","correct":true},{"text":"Zufällige Platzierung ist in Ordnung","correct":false}]', 'Eine ordnungsgemäße Gewichtsverteilung verhindert das Kippen des Tabletts und erleichtert das sichere Tragen.', 2),
('G-ROL-008', 'de', 'Bevor Sie ein Tablett aufheben, sollten Sie immer:', '[{"text":"Ihre Route überprüfen und Hindernisse beachten","correct":true},{"text":"Es so voll wie möglich laden","correct":false},{"text":"Sich beeilen, um Zeit zu sparen","correct":false},{"text":"Mit gebogenem Rücken heben","correct":false}]', 'Routenbewusstsein verhindert Kollisionen und ermöglicht es Ihnen, sicher mit einem beladenen Tablett zu navigieren.', 3),
('G-ROL-008', 'de', 'Was sollten Sie tun, wenn ein Tablett zu schwer ist?', '[{"text":"Versuchen, es trotzdem zu tragen","correct":false},{"text":"Tablettständer verwenden oder mehrere Fahrten machen","correct":true},{"text":"Kunden um Hilfe bitten","correct":false},{"text":"Es über Oberflächen ziehen","correct":false}]', 'Tablettständer sollten für schwere Lasten verwendet werden, oder Gegenstände sollten auf mehrere Fahrten aufgeteilt werden, um Verletzungen zu vermeiden.', 4),
('G-ROL-008', 'de', 'Welches der folgenden ist eine Gefahr beim Tragen von Tabletts?', '[{"text":"Nasse Böden und unebene Oberflächen","correct":true},{"text":"Richtige Beleuchtung","correct":false},{"text":"Leerer Speisesaal","correct":false},{"text":"Saubere Tablettoberfläche","correct":false}]', 'Nasse Böden und unebene Oberflächen erhöhen das Risiko des Ausrutschens und Fallenlassens des Tabletts erheblich.', 5),
('G-ROL-008', 'de', 'Die gesetzliche Grundlage für die Sicherheit beim Tablett-Handling stammt von:', '[{"text":"Lokale Restaurantrichtlinien","correct":false},{"text":"Ley 31/1995 und RD 487/1997","correct":true},{"text":"Kundenpräferenzregeln","correct":false},{"text":"Internationale Hotelstandards","correct":false}]', 'Diese Vorschriften decken die Arbeitssicherheit und das manuelle Handhaben von Lasten am Arbeitsplatz ab.', 6),
('G-ROL-008', 'de', 'Wann sollten Sie Überladungssituationen melden?', '[{"text":"Erst nachdem ein Unfall passiert ist","correct":false},{"text":"Niemals, es wird in geschäftigen Zeiten erwartet","correct":false},{"text":"Sofort, wenn Sie sie bemerken","correct":true},{"text":"Am Ende Ihrer Schicht","correct":false}]', 'Überladungssituationen sollten sofort gemeldet werden, um Verletzungen zu vermeiden und Arbeitspraktiken zu verbessern.', 7),
('G-ROL-008', 'de', 'Was ist die richtige Körpermechanik beim Heben eines Tabletts?', '[{"text":"An der Taille beugen mit geraden Beinen","correct":false},{"text":"Rücken gerade halten und mit den Beinen heben","correct":true},{"text":"Beim Heben drehen","correct":false},{"text":"Knie beim Tragen blockieren","correct":false}]', 'Die richtige Hebetechnik mit geradem Rücken und Beinkraft verhindert Rückenverletzungen.', 8);

-- G-ROL-009: Dining Room Slip Prevention
INSERT INTO training_test_questions (guide_code, language, question, options, explanation, sort_order) VALUES

-- English
('G-ROL-009', 'en', 'What type of footwear must be worn at all times in the dining room?', '[{"text":"Dress shoes","correct":false},{"text":"Non-slip shoes","correct":true},{"text":"Sandals","correct":false},{"text":"Any comfortable shoes","correct":false}]', 'Non-slip shoes are mandatory to prevent slips and falls in the dining area.', 1),
('G-ROL-009', 'en', 'What should you do immediately when you see a spill?', '[{"text":"Walk around it","correct":false},{"text":"Tell customers to be careful","correct":false},{"text":"Clean it immediately","correct":true},{"text":"Wait for cleaning staff","correct":false}]', 'Spills should be cleaned immediately to prevent slip hazards for staff and customers.', 2),
('G-ROL-009', 'en', 'When cleaning a floor, you must:', '[{"text":"Clean quickly without signs","correct":false},{"text":"Place wet floor signs","correct":true},{"text":"Block all exits","correct":false},{"text":"Only clean at closing time","correct":false}]', 'Wet floor signs are required to warn staff and customers of slip hazards during cleaning.', 3),
('G-ROL-009', 'en', 'Which area requires extra caution for slip hazards?', '[{"text":"Dining room to kitchen transitions","correct":true},{"text":"Customer seating areas only","correct":false},{"text":"Outside the building","correct":false},{"text":"Storage rooms","correct":false}]', 'Transitions between dining room and kitchen often have different flooring and increased traffic, requiring extra caution.', 4),
('G-ROL-009', 'en', 'What should you do if you notice damaged or uneven flooring?', '[{"text":"Ignore it","correct":false},{"text":"Put a mat over it","correct":false},{"text":"Report it immediately","correct":true},{"text":"Mark it with tape yourself","correct":false}]', 'Damaged or uneven flooring should be reported immediately for repair to prevent trip hazards.', 5),
('G-ROL-009', 'en', 'Keeping walkways clear of obstacles helps prevent:', '[{"text":"Customer complaints","correct":false},{"text":"Trips and falls","correct":true},{"text":"Food spoilage","correct":false},{"text":"Noise problems","correct":false}]', 'Clear walkways reduce the risk of trips and falls, which are common workplace injuries.', 6),
('G-ROL-009', 'en', 'The legal basis for slip prevention comes from:', '[{"text":"Restaurant policy only","correct":false},{"text":"RD 486/1997 and Ley 31/1995","correct":true},{"text":"Customer feedback","correct":false},{"text":"Industry recommendations","correct":false}]', 'These regulations establish workplace safety requirements including floor surface and maintenance standards.', 7),
('G-ROL-009', 'en', 'What is a common cause of slips in the dining room?', '[{"text":"Proper lighting","correct":false},{"text":"Wet floors from spills","correct":true},{"text":"Non-slip footwear","correct":false},{"text":"Clear walkways","correct":false}]', 'Wet floors from spills are one of the most common causes of slip accidents in hospitality settings.', 8),

-- Spanish
('G-ROL-009', 'es', '¿Qué tipo de calzado debe usarse en todo momento en el comedor?', '[{"text":"Zapatos de vestir","correct":false},{"text":"Zapatos antideslizantes","correct":true},{"text":"Sandalias","correct":false},{"text":"Cualquier zapato cómodo","correct":false}]', 'Los zapatos antideslizantes son obligatorios para prevenir resbalones y caídas en el área del comedor.', 1),
('G-ROL-009', 'es', '¿Qué debe hacer inmediatamente cuando vea un derrame?', '[{"text":"Caminar alrededor de él","correct":false},{"text":"Decir a los clientes que tengan cuidado","correct":false},{"text":"Limpiarlo inmediatamente","correct":true},{"text":"Esperar al personal de limpieza","correct":false}]', 'Los derrames deben limpiarse inmediatamente para prevenir peligros de resbalones para el personal y los clientes.', 2),
('G-ROL-009', 'es', 'Al limpiar un piso, debe:', '[{"text":"Limpiar rápidamente sin señales","correct":false},{"text":"Colocar señales de piso mojado","correct":true},{"text":"Bloquear todas las salidas","correct":false},{"text":"Solo limpiar al cerrar","correct":false}]', 'Las señales de piso mojado son necesarias para advertir al personal y clientes sobre los peligros de resbalones durante la limpieza.', 3),
('G-ROL-009', 'es', '¿Qué área requiere precaución adicional por peligros de resbalones?', '[{"text":"Transiciones del comedor a la cocina","correct":true},{"text":"Solo áreas de asientos de clientes","correct":false},{"text":"Fuera del edificio","correct":false},{"text":"Salas de almacenamiento","correct":false}]', 'Las transiciones entre el comedor y la cocina a menudo tienen pisos diferentes y mayor tráfico, requiriendo precaución adicional.', 4),
('G-ROL-009', 'es', '¿Qué debe hacer si nota un piso dañado o irregular?', '[{"text":"Ignorarlo","correct":false},{"text":"Poner una alfombra sobre él","correct":false},{"text":"Reportarlo inmediatamente","correct":true},{"text":"Marcarlo con cinta usted mismo","correct":false}]', 'El piso dañado o irregular debe reportarse inmediatamente para su reparación para prevenir peligros de tropiezos.', 5),
('G-ROL-009', 'es', 'Mantener los pasillos libres de obstáculos ayuda a prevenir:', '[{"text":"Quejas de clientes","correct":false},{"text":"Tropiezos y caídas","correct":true},{"text":"Deterioro de alimentos","correct":false},{"text":"Problemas de ruido","correct":false}]', 'Los pasillos despejados reducen el riesgo de tropiezos y caídas, que son lesiones laborales comunes.', 6),
('G-ROL-009', 'es', 'La base legal para la prevención de resbalones proviene de:', '[{"text":"Solo política del restaurante","correct":false},{"text":"RD 486/1997 y Ley 31/1995","correct":true},{"text":"Comentarios de clientes","correct":false},{"text":"Recomendaciones de la industria","correct":false}]', 'Estas regulaciones establecen requisitos de seguridad laboral incluyendo estándares de superficie y mantenimiento de pisos.', 7),
('G-ROL-009', 'es', '¿Cuál es una causa común de resbalones en el comedor?', '[{"text":"Iluminación adecuada","correct":false},{"text":"Pisos mojados por derrames","correct":true},{"text":"Calzado antideslizante","correct":false},{"text":"Pasillos despejados","correct":false}]', 'Los pisos mojados por derrames son una de las causas más comunes de accidentes por resbalones en entornos de hospitalidad.', 8),

-- Dutch
('G-ROL-009', 'nl', 'Welk type schoeisel moet te allen tijde in de eetkamer worden gedragen?', '[{"text":"Nette schoenen","correct":false},{"text":"Antislipschoenen","correct":true},{"text":"Sandalen","correct":false},{"text":"Elke comfortabele schoen","correct":false}]', 'Antislipschoenen zijn verplicht om uitglijden en vallen in de eetruimte te voorkomen.', 1),
('G-ROL-009', 'nl', 'Wat moet u onmiddellijk doen wanneer u een gemorste vloeistof ziet?', '[{"text":"Eromheen lopen","correct":false},{"text":"Klanten vertellen voorzichtig te zijn","correct":false},{"text":"Het onmiddellijk schoonmaken","correct":true},{"text":"Wachten op schoonmaakpersoneel","correct":false}]', 'Gemorste vloeistoffen moeten onmiddellijk worden schoongemaakt om uitglijgevaar voor personeel en klanten te voorkomen.', 2),
('G-ROL-009', 'nl', 'Bij het schoonmaken van een vloer moet u:', '[{"text":"Snel schoonmaken zonder borden","correct":false},{"text":"Natte vloer borden plaatsen","correct":true},{"text":"Alle uitgangen blokkeren","correct":false},{"text":"Alleen bij sluiting schoonmaken","correct":false}]', 'Natte vloer borden zijn vereist om personeel en klanten te waarschuwen voor uitglijgevaar tijdens het schoonmaken.', 3),
('G-ROL-009', 'nl', 'Welk gebied vereist extra voorzichtigheid voor uitglijgevaar?', '[{"text":"Overgangen van eetkamer naar keuken","correct":true},{"text":"Alleen klantzitgebieden","correct":false},{"text":"Buiten het gebouw","correct":false},{"text":"Opslagruimten","correct":false}]', 'Overgangen tussen eetkamer en keuken hebben vaak verschillende vloeren en toegenomen verkeer, wat extra voorzichtigheid vereist.', 4),
('G-ROL-009', 'nl', 'Wat moet u doen als u beschadigde of oneffen vloer opmerkt?', '[{"text":"Het negeren","correct":false},{"text":"Er een mat overheen leggen","correct":false},{"text":"Het onmiddellijk melden","correct":true},{"text":"Het zelf met tape markeren","correct":false}]', 'Beschadigde of oneffen vloer moet onmiddellijk worden gemeld voor reparatie om struikelgevaar te voorkomen.', 5),
('G-ROL-009', 'nl', 'Het vrijhouden van looppaden van obstakels helpt te voorkomen:', '[{"text":"Klachten van klanten","correct":false},{"text":"Struikelen en vallen","correct":true},{"text":"Voedselbederf","correct":false},{"text":"Geluidsproblemen","correct":false}]', 'Vrije looppaden verminderen het risico op struikelen en vallen, wat veelvoorkomende arbeidsongevallen zijn.', 6),
('G-ROL-009', 'nl', 'De wettelijke basis voor uitglijpreventie komt van:', '[{"text":"Alleen restaurantbeleid","correct":false},{"text":"RD 486/1997 en Ley 31/1995","correct":true},{"text":"Klantfeedback","correct":false},{"text":"Branche-aanbevelingen","correct":false}]', 'Deze regelgeving stelt arbeidsveiligheidseisen vast, inclusief vloeroppervlak- en onderhoudsstandaarden.', 7),
('G-ROL-009', 'nl', 'Wat is een veelvoorkomende oorzaak van uitglijden in de eetkamer?', '[{"text":"Goede verlichting","correct":false},{"text":"Natte vloeren door gemorste vloeistoffen","correct":true},{"text":"Antislipschoeisel","correct":false},{"text":"Vrije looppaden","correct":false}]', 'Natte vloeren door gemorste vloeistoffen zijn een van de meest voorkomende oorzaken van uitglijdongevallen in de horeca.', 8),

-- German
('G-ROL-009', 'de', 'Welche Art von Schuhwerk muss jederzeit im Speisesaal getragen werden?', '[{"text":"Elegante Schuhe","correct":false},{"text":"Rutschfeste Schuhe","correct":true},{"text":"Sandalen","correct":false},{"text":"Jede bequeme Schuhe","correct":false}]', 'Rutschfeste Schuhe sind obligatorisch, um Ausrutschen und Stürze im Essbereich zu verhindern.', 1),
('G-ROL-009', 'de', 'Was sollten Sie sofort tun, wenn Sie eine verschüttete Flüssigkeit sehen?', '[{"text":"Darum herumgehen","correct":false},{"text":"Kunden sagen, vorsichtig zu sein","correct":false},{"text":"Es sofort aufwischen","correct":true},{"text":"Auf Reinigungspersonal warten","correct":false}]', 'Verschüttete Flüssigkeiten sollten sofort aufgewischt werden, um Rutschgefahren für Personal und Kunden zu vermeiden.', 2),
('G-ROL-009', 'de', 'Beim Reinigen eines Bodens müssen Sie:', '[{"text":"Schnell ohne Schilder reinigen","correct":false},{"text":"Warnschilder für nasse Böden aufstellen","correct":true},{"text":"Alle Ausgänge blockieren","correct":false},{"text":"Nur beim Schließen reinigen","correct":false}]', 'Warnschilder für nasse Böden sind erforderlich, um Personal und Kunden vor Rutschgefahren während der Reinigung zu warnen.', 3),
('G-ROL-009', 'de', 'Welcher Bereich erfordert zusätzliche Vorsicht bei Rutschgefahren?', '[{"text":"Übergänge vom Speisesaal zur Küche","correct":true},{"text":"Nur Kundensitzbereiche","correct":false},{"text":"Außerhalb des Gebäudes","correct":false},{"text":"Lagerräume","correct":false}]', 'Übergänge zwischen Speisesaal und Küche haben oft unterschiedliche Bodenbeläge und erhöhten Verkehr, was zusätzliche Vorsicht erfordert.', 4),
('G-ROL-009', 'de', 'Was sollten Sie tun, wenn Sie beschädigte oder unebene Bodenbeläge bemerken?', '[{"text":"Es ignorieren","correct":false},{"text":"Eine Matte darüber legen","correct":false},{"text":"Es sofort melden","correct":true},{"text":"Es selbst mit Klebeband markieren","correct":false}]', 'Beschädigte oder unebene Bodenbeläge sollten sofort zur Reparatur gemeldet werden, um Stolperfallen zu vermeiden.', 5),
('G-ROL-009', 'de', 'Das Freihalten von Gehwegen von Hindernissen hilft zu verhindern:', '[{"text":"Kundenbeschwerden","correct":false},{"text":"Stolpern und Stürze","correct":true},{"text":"Lebensmittelverderb","correct":false},{"text":"Lärmprobleme","correct":false}]', 'Freie Gehwege verringern das Risiko von Stolpern und Stürzen, die häufige Arbeitsunfälle sind.', 6),
('G-ROL-009', 'de', 'Die gesetzliche Grundlage für Rutschprävention stammt von:', '[{"text":"Nur Restaurantrichtlinien","correct":false},{"text":"RD 486/1997 und Ley 31/1995","correct":true},{"text":"Kundenfeedback","correct":false},{"text":"Branchenempfehlungen","correct":false}]', 'Diese Vorschriften legen Anforderungen an die Arbeitssicherheit fest, einschließlich Standards für Bodenoberflächen und Wartung.', 7),
('G-ROL-009', 'de', 'Was ist eine häufige Ursache für Ausrutschen im Speisesaal?', '[{"text":"Richtige Beleuchtung","correct":false},{"text":"Nasse Böden durch verschüttete Flüssigkeiten","correct":true},{"text":"Rutschfestes Schuhwerk","correct":false},{"text":"Freie Gehwege","correct":false}]', 'Nasse Böden durch verschüttete Flüssigkeiten sind eine der häufigsten Ursachen für Rutschunfälle im Gastgewerbe.', 8);

-- G-ROL-010: Anti-Harassment Protocol
INSERT INTO training_test_questions (guide_code, language, question, options, explanation, sort_order) VALUES

-- English
('G-ROL-010', 'en', 'What is the company policy on harassment?', '[{"text":"Tolerate minor incidents","correct":false},{"text":"Zero tolerance for all forms","correct":true},{"text":"Handle informally only","correct":false},{"text":"Ignore unless repeated","correct":false}]', 'The company maintains a strict zero tolerance policy for all forms of harassment.', 1),
('G-ROL-010', 'en', 'The anti-harassment protocol covers which types of harassment?', '[{"text":"Only sexual harassment","correct":false},{"text":"Sexual, gender-based, and workplace bullying","correct":true},{"text":"Only harassment by managers","correct":false},{"text":"Only physical harassment","correct":false}]', 'The protocol covers all forms of harassment including sexual, gender-based, and workplace bullying.', 2),
('G-ROL-010', 'en', 'If you experience or witness harassment, you should:', '[{"text":"Keep it to yourself","correct":false},{"text":"Use the complaint procedure","correct":true},{"text":"Handle it yourself","correct":false},{"text":"Wait to see if it happens again","correct":false}]', 'All harassment should be reported through the official complaint procedure for proper investigation.', 3),
('G-ROL-010', 'en', 'How are harassment complaints handled?', '[{"text":"Made public immediately","correct":false},{"text":"Investigated confidentially","correct":true},{"text":"Ignored if minor","correct":false},{"text":"Dismissed without investigation","correct":false}]', 'All complaints are investigated confidentially to protect the privacy of all parties involved.', 4),
('G-ROL-010', 'en', 'What happens if someone retaliates against a person who made a harassment complaint?', '[{"text":"Nothing, it''s allowed","correct":false},{"text":"It is prohibited and will be sanctioned","correct":true},{"text":"Only warned once","correct":false},{"text":"Depends on their position","correct":false}]', 'Retaliation against complainants is strictly prohibited and subject to disciplinary action.', 5),
('G-ROL-010', 'en', 'The legal basis for the anti-harassment protocol comes from:', '[{"text":"Company preference only","correct":false},{"text":"LO 3/2007 and ET Art. 4.2.e","correct":true},{"text":"Industry customs","correct":false},{"text":"Customer requests","correct":false}]', 'These laws mandate equality at work and protection against harassment.', 6),
('G-ROL-010', 'en', 'Training on harassment prevention is:', '[{"text":"Optional for staff","correct":false},{"text":"Mandatory for all employees","correct":true},{"text":"Only for managers","correct":false},{"text":"Not required","correct":false}]', 'All employees must receive training on harassment prevention as part of the protocol.', 7),
('G-ROL-010', 'en', 'What are possible sanctions for harassment?', '[{"text":"Only verbal warning","correct":false},{"text":"Range from warning to dismissal","correct":true},{"text":"No sanctions apply","correct":false},{"text":"Only suspension","correct":false}]', 'Sanctions for harassment can range from written warnings to termination depending on severity.', 8),

-- Spanish
('G-ROL-010', 'es', '¿Cuál es la política de la empresa sobre el acoso?', '[{"text":"Tolerar incidentes menores","correct":false},{"text":"Tolerancia cero para todas las formas","correct":true},{"text":"Manejar solo informalmente","correct":false},{"text":"Ignorar a menos que se repita","correct":false}]', 'La empresa mantiene una política estricta de tolerancia cero para todas las formas de acoso.', 1),
('G-ROL-010', 'es', 'El protocolo anti-acoso cubre qué tipos de acoso?', '[{"text":"Solo acoso sexual","correct":false},{"text":"Sexual, por razón de sexo, y mobbing laboral","correct":true},{"text":"Solo acoso por gerentes","correct":false},{"text":"Solo acoso físico","correct":false}]', 'El protocolo cubre todas las formas de acoso incluyendo sexual, por razón de sexo, y mobbing laboral.', 2),
('G-ROL-010', 'es', 'Si experimenta o presencia acoso, debe:', '[{"text":"Guardárselo para usted","correct":false},{"text":"Usar el procedimiento de denuncia","correct":true},{"text":"Manejarlo usted mismo","correct":false},{"text":"Esperar a ver si sucede de nuevo","correct":false}]', 'Todo acoso debe denunciarse a través del procedimiento oficial de denuncia para una investigación adecuada.', 3),
('G-ROL-010', 'es', '¿Cómo se manejan las denuncias de acoso?', '[{"text":"Se hacen públicas inmediatamente","correct":false},{"text":"Se investigan confidencialmente","correct":true},{"text":"Se ignoran si son menores","correct":false},{"text":"Se desestiman sin investigación","correct":false}]', 'Todas las denuncias se investigan confidencialmente para proteger la privacidad de todas las partes involucradas.', 4),
('G-ROL-010', 'es', '¿Qué sucede si alguien toma represalias contra una persona que hizo una denuncia de acoso?', '[{"text":"Nada, está permitido","correct":false},{"text":"Está prohibido y será sancionado","correct":true},{"text":"Solo se advierte una vez","correct":false},{"text":"Depende de su posición","correct":false}]', 'Las represalias contra los denunciantes están estrictamente prohibidas y sujetas a medidas disciplinarias.', 5),
('G-ROL-010', 'es', 'La base legal para el protocolo anti-acoso proviene de:', '[{"text":"Solo preferencia de la empresa","correct":false},{"text":"LO 3/2007 y ET Art. 4.2.e","correct":true},{"text":"Costumbres de la industria","correct":false},{"text":"Solicitudes de clientes","correct":false}]', 'Estas leyes exigen la igualdad en el trabajo y la protección contra el acoso.', 6),
('G-ROL-010', 'es', 'La formación sobre prevención del acoso es:', '[{"text":"Opcional para el personal","correct":false},{"text":"Obligatoria para todos los empleados","correct":true},{"text":"Solo para gerentes","correct":false},{"text":"No requerida","correct":false}]', 'Todos los empleados deben recibir formación sobre prevención del acoso como parte del protocolo.', 7),
('G-ROL-010', 'es', '¿Cuáles son las posibles sanciones por acoso?', '[{"text":"Solo advertencia verbal","correct":false},{"text":"Van desde advertencia hasta despido","correct":true},{"text":"No se aplican sanciones","correct":false},{"text":"Solo suspensión","correct":false}]', 'Las sanciones por acoso pueden ir desde advertencias escritas hasta el despido según la gravedad.', 8),

-- Dutch
('G-ROL-010', 'nl', 'Wat is het bedrijfsbeleid over intimidatie?', '[{"text":"Kleine incidenten tolereren","correct":false},{"text":"Nultolerantie voor alle vormen","correct":true},{"text":"Alleen informeel afhandelen","correct":false},{"text":"Negeren tenzij herhaald","correct":false}]', 'Het bedrijf hanteert een strikt nultolerantiebeleid voor alle vormen van intimidatie.', 1),
('G-ROL-010', 'nl', 'Het anti-intimidatieprotocol dekt welke soorten intimidatie?', '[{"text":"Alleen seksuele intimidatie","correct":false},{"text":"Seksuele, gendergebaseerde en pesten op de werkplek","correct":true},{"text":"Alleen intimidatie door managers","correct":false},{"text":"Alleen fysieke intimidatie","correct":false}]', 'Het protocol dekt alle vormen van intimidatie inclusief seksuele, gendergebaseerde en pesten op de werkplek.', 2),
('G-ROL-010', 'nl', 'Als u intimidatie ervaart of getuige bent, moet u:', '[{"text":"Het voor uzelf houden","correct":false},{"text":"De klachtenprocedure gebruiken","correct":true},{"text":"Het zelf afhandelen","correct":false},{"text":"Wachten om te zien of het opnieuw gebeurt","correct":false}]', 'Alle intimidatie moet worden gemeld via de officiële klachtenprocedure voor een correct onderzoek.', 3),
('G-ROL-010', 'nl', 'Hoe worden klachten over intimidatie behandeld?', '[{"text":"Onmiddellijk openbaar gemaakt","correct":false},{"text":"Vertrouwelijk onderzocht","correct":true},{"text":"Genegeerd als ze klein zijn","correct":false},{"text":"Afgewezen zonder onderzoek","correct":false}]', 'Alle klachten worden vertrouwelijk onderzocht om de privacy van alle betrokken partijen te beschermen.', 4),
('G-ROL-010', 'nl', 'Wat gebeurt er als iemand represailles neemt tegen een persoon die een intimidatieklacht heeft ingediend?', '[{"text":"Niets, het is toegestaan","correct":false},{"text":"Het is verboden en zal worden gesanctioneerd","correct":true},{"text":"Slechts één keer gewaarschuwd","correct":false},{"text":"Hangt af van hun positie","correct":false}]', 'Represailles tegen klagers zijn strikt verboden en onderhevig aan disciplinaire maatregelen.', 5),
('G-ROL-010', 'nl', 'De wettelijke basis voor het anti-intimidatieprotocol komt van:', '[{"text":"Alleen bedrijfsvoorkeur","correct":false},{"text":"LO 3/2007 en ET Art. 4.2.e","correct":true},{"text":"Branchegewoonten","correct":false},{"text":"Klantverzoeken","correct":false}]', 'Deze wetten mandateren gelijkheid op het werk en bescherming tegen intimidatie.', 6),
('G-ROL-010', 'nl', 'Training over intimidatiepreventie is:', '[{"text":"Optioneel voor personeel","correct":false},{"text":"Verplicht voor alle werknemers","correct":true},{"text":"Alleen voor managers","correct":false},{"text":"Niet vereist","correct":false}]', 'Alle werknemers moeten training ontvangen over intimidatiepreventie als onderdeel van het protocol.', 7),
('G-ROL-010', 'nl', 'Wat zijn mogelijke sancties voor intimidatie?', '[{"text":"Alleen mondelinge waarschuwing","correct":false},{"text":"Variëren van waarschuwing tot ontslag","correct":true},{"text":"Geen sancties van toepassing","correct":false},{"text":"Alleen schorsing","correct":false}]', 'Sancties voor intimidatie kunnen variëren van schriftelijke waarschuwingen tot ontslag afhankelijk van de ernst.', 8),

-- German
('G-ROL-010', 'de', 'Was ist die Unternehmenspolitik zu Belästigung?', '[{"text":"Kleinere Vorfälle tolerieren","correct":false},{"text":"Null Toleranz für alle Formen","correct":true},{"text":"Nur informell behandeln","correct":false},{"text":"Ignorieren, es sei denn wiederholt","correct":false}]', 'Das Unternehmen verfolgt eine strenge Null-Toleranz-Politik für alle Formen von Belästigung.', 1),
('G-ROL-010', 'de', 'Das Anti-Belästigungsprotokoll deckt welche Arten von Belästigung ab?', '[{"text":"Nur sexuelle Belästigung","correct":false},{"text":"Sexuelle, geschlechtsbasierte und Mobbing am Arbeitsplatz","correct":true},{"text":"Nur Belästigung durch Manager","correct":false},{"text":"Nur körperliche Belästigung","correct":false}]', 'Das Protokoll deckt alle Formen von Belästigung ab, einschließlich sexueller, geschlechtsbasierter und Mobbing am Arbeitsplatz.', 2),
('G-ROL-010', 'de', 'Wenn Sie Belästigung erleben oder Zeuge werden, sollten Sie:', '[{"text":"Es für sich behalten","correct":false},{"text":"Das Beschwerdeverfahren nutzen","correct":true},{"text":"Es selbst regeln","correct":false},{"text":"Warten, ob es erneut passiert","correct":false}]', 'Alle Belästigung sollte über das offizielle Beschwerdeverfahren für eine ordnungsgemäße Untersuchung gemeldet werden.', 3),
('G-ROL-010', 'de', 'Wie werden Belästigungsbeschwerden behandelt?', '[{"text":"Sofort öffentlich gemacht","correct":false},{"text":"Vertraulich untersucht","correct":true},{"text":"Ignoriert, wenn geringfügig","correct":false},{"text":"Ohne Untersuchung abgewiesen","correct":false}]', 'Alle Beschwerden werden vertraulich untersucht, um die Privatsphäre aller Beteiligten zu schützen.', 4),
('G-ROL-010', 'de', 'Was passiert, wenn jemand Vergeltung gegen eine Person übt, die eine Belästigungsbeschwerde eingereicht hat?', '[{"text":"Nichts, es ist erlaubt","correct":false},{"text":"Es ist verboten und wird sanktioniert","correct":true},{"text":"Nur einmal gewarnt","correct":false},{"text":"Hängt von ihrer Position ab","correct":false}]', 'Vergeltung gegen Beschwerdeführer ist streng verboten und unterliegt Disziplinarmaßnahmen.', 5),
('G-ROL-010', 'de', 'Die gesetzliche Grundlage für das Anti-Belästigungsprotokoll stammt von:', '[{"text":"Nur Unternehmenspräferenz","correct":false},{"text":"LO 3/2007 und ET Art. 4.2.e","correct":true},{"text":"Branchenbräuche","correct":false},{"text":"Kundenanfragen","correct":false}]', 'Diese Gesetze schreiben Gleichheit am Arbeitsplatz und Schutz vor Belästigung vor.', 6),
('G-ROL-010', 'de', 'Die Schulung zur Belästigungsprävention ist:', '[{"text":"Optional für Mitarbeiter","correct":false},{"text":"Obligatorisch für alle Mitarbeiter","correct":true},{"text":"Nur für Manager","correct":false},{"text":"Nicht erforderlich","correct":false}]', 'Alle Mitarbeiter müssen als Teil des Protokolls eine Schulung zur Belästigungsprävention erhalten.', 7),
('G-ROL-010', 'de', 'Was sind mögliche Sanktionen für Belästigung?', '[{"text":"Nur mündliche Verwarnung","correct":false},{"text":"Reichen von Verwarnung bis Entlassung","correct":true},{"text":"Keine Sanktionen gelten","correct":false},{"text":"Nur Suspendierung","correct":false}]', 'Sanktionen für Belästigung können je nach Schweregrad von schriftlichen Verwarnungen bis zur Kündigung reichen.', 8);

-- G-ROL-011: Equality Plan
INSERT INTO training_test_questions (guide_code, language, question, options, explanation, sort_order) VALUES

-- English
('G-ROL-011', 'en', 'Which companies are required to have an Equality Plan?', '[{"text":"Only companies with 500+ employees","correct":false},{"text":"Companies with 50+ employees","correct":true},{"text":"Only multinational companies","correct":false},{"text":"No companies need one","correct":false}]', 'Companies with 50 or more employees must implement a formal Equality Plan.', 1),
('G-ROL-011', 'en', 'The principle of equal pay means:', '[{"text":"Everyone gets the same salary","correct":false},{"text":"Equal pay for equal work","correct":true},{"text":"Only managers get equal pay","correct":false},{"text":"Pay can vary by gender","correct":false}]', 'Equal pay for equal work means workers performing the same work must receive equal compensation regardless of gender.', 2),
('G-ROL-011', 'en', 'What does the Equality Plan address?', '[{"text":"Only hiring practices","correct":false},{"text":"Pay, recruitment, promotion, work-life balance, harassment","correct":true},{"text":"Only sexual harassment","correct":false},{"text":"Only training","correct":false}]', 'The Equality Plan must comprehensively address all aspects of workplace equality.', 3),
('G-ROL-011', 'en', 'Recruitment processes must be:', '[{"text":"Favor men for physical roles","correct":false},{"text":"Non-discriminatory","correct":true},{"text":"Only advertise to certain groups","correct":false},{"text":"Based on gender preferences","correct":false}]', 'All recruitment must be free from discrimination based on gender or other protected characteristics.', 4),
('G-ROL-011', 'en', 'Work-life balance measures in the Equality Plan include:', '[{"text":"Rigid schedules only","correct":false},{"text":"Flexible arrangements and family support","correct":true},{"text":"No accommodations","correct":false},{"text":"Only for women","correct":false}]', 'Work-life balance measures support all employees in managing work and personal responsibilities.', 5),
('G-ROL-011', 'en', 'The legal basis for the Equality Plan comes from:', '[{"text":"Company preference","correct":false},{"text":"LO 3/2007 and RD 901/2020","correct":true},{"text":"Industry guidelines only","correct":false},{"text":"Customer requests","correct":false}]', 'These laws mandate equality in the workplace and establish requirements for equality plans.', 6),
('G-ROL-011', 'en', 'Equal access to training and promotion means:', '[{"text":"Only certain staff get training","correct":false},{"text":"All employees have equal opportunities","correct":true},{"text":"Promotions only for specific groups","correct":false},{"text":"Training is optional","correct":false}]', 'All employees must have equal access to training and career advancement opportunities.', 7),
('G-ROL-011', 'en', 'How often should the Equality Plan be reviewed?', '[{"text":"Never","correct":false},{"text":"Regularly monitored and reviewed","correct":true},{"text":"Only once at creation","correct":false},{"text":"Only if problems arise","correct":false}]', 'The Equality Plan requires regular monitoring and review to ensure effectiveness.', 8),

-- Spanish
('G-ROL-011', 'es', '¿Qué empresas están obligadas a tener un Plan de Igualdad?', '[{"text":"Solo empresas con 500+ empleados","correct":false},{"text":"Empresas con 50+ empleados","correct":true},{"text":"Solo empresas multinacionales","correct":false},{"text":"Ninguna empresa lo necesita","correct":false}]', 'Las empresas con 50 o más empleados deben implementar un Plan de Igualdad formal.', 1),
('G-ROL-011', 'es', 'El principio de igualdad salarial significa:', '[{"text":"Todos reciben el mismo salario","correct":false},{"text":"Igual salario por igual trabajo","correct":true},{"text":"Solo los gerentes reciben igual salario","correct":false},{"text":"El salario puede variar por género","correct":false}]', 'Igualdad salarial por igual trabajo significa que los trabajadores que realizan el mismo trabajo deben recibir igual compensación independientemente del género.', 2),
('G-ROL-011', 'es', '¿Qué aborda el Plan de Igualdad?', '[{"text":"Solo prácticas de contratación","correct":false},{"text":"Salario, reclutamiento, promoción, conciliación, acoso","correct":true},{"text":"Solo acoso sexual","correct":false},{"text":"Solo formación","correct":false}]', 'El Plan de Igualdad debe abordar de manera integral todos los aspectos de la igualdad en el lugar de trabajo.', 3),
('G-ROL-011', 'es', 'Los procesos de reclutamiento deben ser:', '[{"text":"Favorecer a hombres para roles físicos","correct":false},{"text":"No discriminatorios","correct":true},{"text":"Solo anunciar a ciertos grupos","correct":false},{"text":"Basados en preferencias de género","correct":false}]', 'Todo reclutamiento debe estar libre de discriminación basada en género u otras características protegidas.', 4),
('G-ROL-011', 'es', 'Las medidas de conciliación laboral-personal en el Plan de Igualdad incluyen:', '[{"text":"Solo horarios rígidos","correct":false},{"text":"Arreglos flexibles y apoyo familiar","correct":true},{"text":"Sin acomodaciones","correct":false},{"text":"Solo para mujeres","correct":false}]', 'Las medidas de conciliación apoyan a todos los empleados en la gestión del trabajo y responsabilidades personales.', 5),
('G-ROL-011', 'es', 'La base legal para el Plan de Igualdad proviene de:', '[{"text":"Preferencia de la empresa","correct":false},{"text":"LO 3/2007 y RD 901/2020","correct":true},{"text":"Solo directrices de la industria","correct":false},{"text":"Solicitudes de clientes","correct":false}]', 'Estas leyes exigen la igualdad en el lugar de trabajo y establecen requisitos para los planes de igualdad.', 6),
('G-ROL-011', 'es', 'El acceso igualitario a formación y promoción significa:', '[{"text":"Solo cierto personal recibe formación","correct":false},{"text":"Todos los empleados tienen iguales oportunidades","correct":true},{"text":"Promociones solo para grupos específicos","correct":false},{"text":"La formación es opcional","correct":false}]', 'Todos los empleados deben tener igual acceso a la formación y oportunidades de avance profesional.', 7),
('G-ROL-011', 'es', '¿Con qué frecuencia debe revisarse el Plan de Igualdad?', '[{"text":"Nunca","correct":false},{"text":"Monitoreado y revisado regularmente","correct":true},{"text":"Solo una vez en la creación","correct":false},{"text":"Solo si surgen problemas","correct":false}]', 'El Plan de Igualdad requiere monitoreo y revisión regulares para asegurar efectividad.', 8),

-- Dutch
('G-ROL-011', 'nl', 'Welke bedrijven zijn verplicht een Gelijkheidsplan te hebben?', '[{"text":"Alleen bedrijven met 500+ werknemers","correct":false},{"text":"Bedrijven met 50+ werknemers","correct":true},{"text":"Alleen multinationale bedrijven","correct":false},{"text":"Geen bedrijven hebben er een nodig","correct":false}]', 'Bedrijven met 50 of meer werknemers moeten een formeel Gelijkheidsplan implementeren.', 1),
('G-ROL-011', 'nl', 'Het principe van gelijke beloning betekent:', '[{"text":"Iedereen krijgt hetzelfde salaris","correct":false},{"text":"Gelijke beloning voor gelijk werk","correct":true},{"text":"Alleen managers krijgen gelijke beloning","correct":false},{"text":"Beloning kan variëren per geslacht","correct":false}]', 'Gelijke beloning voor gelijk werk betekent dat werknemers die hetzelfde werk doen gelijke compensatie moeten ontvangen ongeacht geslacht.', 2),
('G-ROL-011', 'nl', 'Wat behandelt het Gelijkheidsplan?', '[{"text":"Alleen wervingspraktijken","correct":false},{"text":"Beloning, werving, promotie, werk-privébalans, intimidatie","correct":true},{"text":"Alleen seksuele intimidatie","correct":false},{"text":"Alleen training","correct":false}]', 'Het Gelijkheidsplan moet alle aspecten van werkplekgelijkheid uitgebreid behandelen.', 3),
('G-ROL-011', 'nl', 'Wervingsprocessen moeten zijn:', '[{"text":"Mannen bevoordeligen voor fysieke rollen","correct":false},{"text":"Niet-discriminerend","correct":true},{"text":"Alleen adverteren naar bepaalde groepen","correct":false},{"text":"Gebaseerd op gendervoorkeuren","correct":false}]', 'Alle werving moet vrij zijn van discriminatie op basis van geslacht of andere beschermde kenmerken.', 4),
('G-ROL-011', 'nl', 'Werk-privébalansmaatregelen in het Gelijkheidsplan omvatten:', '[{"text":"Alleen rigide roosters","correct":false},{"text":"Flexibele regelingen en gezinsondersteuning","correct":true},{"text":"Geen aanpassingen","correct":false},{"text":"Alleen voor vrouwen","correct":false}]', 'Werk-privébalansmaatregelen ondersteunen alle werknemers bij het beheren van werk en persoonlijke verantwoordelijkheden.', 5),
('G-ROL-011', 'nl', 'De wettelijke basis voor het Gelijkheidsplan komt van:', '[{"text":"Bedrijfsvoorkeur","correct":false},{"text":"LO 3/2007 en RD 901/2020","correct":true},{"text":"Alleen brancherichtlijnen","correct":false},{"text":"Klantverzoeken","correct":false}]', 'Deze wetten verplichten gelijkheid op de werkplek en stellen eisen vast voor gelijkheidsplannen.', 6),
('G-ROL-011', 'nl', 'Gelijke toegang tot training en promotie betekent:', '[{"text":"Alleen bepaald personeel krijgt training","correct":false},{"text":"Alle werknemers hebben gelijke kansen","correct":true},{"text":"Promoties alleen voor specifieke groepen","correct":false},{"text":"Training is optioneel","correct":false}]', 'Alle werknemers moeten gelijke toegang hebben tot training en carrièreontwikkelingsmogelijkheden.', 7),
('G-ROL-011', 'nl', 'Hoe vaak moet het Gelijkheidsplan worden herzien?', '[{"text":"Nooit","correct":false},{"text":"Regelmatig gemonitord en herzien","correct":true},{"text":"Slechts één keer bij creatie","correct":false},{"text":"Alleen als er problemen ontstaan","correct":false}]', 'Het Gelijkheidsplan vereist regelmatige monitoring en herziening om effectiviteit te waarborgen.', 8),

-- German
('G-ROL-011', 'de', 'Welche Unternehmen sind verpflichtet, einen Gleichstellungsplan zu haben?', '[{"text":"Nur Unternehmen mit 500+ Mitarbeitern","correct":false},{"text":"Unternehmen mit 50+ Mitarbeitern","correct":true},{"text":"Nur multinationale Unternehmen","correct":false},{"text":"Keine Unternehmen brauchen einen","correct":false}]', 'Unternehmen mit 50 oder mehr Mitarbeitern müssen einen formellen Gleichstellungsplan implementieren.', 1),
('G-ROL-011', 'de', 'Das Prinzip der gleichen Bezahlung bedeutet:', '[{"text":"Alle bekommen das gleiche Gehalt","correct":false},{"text":"Gleiche Bezahlung für gleiche Arbeit","correct":true},{"text":"Nur Manager bekommen gleiche Bezahlung","correct":false},{"text":"Bezahlung kann nach Geschlecht variieren","correct":false}]', 'Gleiche Bezahlung für gleiche Arbeit bedeutet, dass Arbeitnehmer, die die gleiche Arbeit verrichten, unabhängig vom Geschlecht gleiche Vergütung erhalten müssen.', 2),
('G-ROL-011', 'de', 'Was behandelt der Gleichstellungsplan?', '[{"text":"Nur Einstellungspraktiken","correct":false},{"text":"Bezahlung, Rekrutierung, Beförderung, Work-Life-Balance, Belästigung","correct":true},{"text":"Nur sexuelle Belästigung","correct":false},{"text":"Nur Schulung","correct":false}]', 'Der Gleichstellungsplan muss alle Aspekte der Arbeitsplatzgleichstellung umfassend behandeln.', 3),
('G-ROL-011', 'de', 'Rekrutierungsprozesse müssen sein:', '[{"text":"Männer für körperliche Rollen bevorzugen","correct":false},{"text":"Nicht diskriminierend","correct":true},{"text":"Nur an bestimmte Gruppen werben","correct":false},{"text":"Basierend auf Geschlechtspräferenzen","correct":false}]', 'Alle Rekrutierung muss frei von Diskriminierung aufgrund von Geschlecht oder anderen geschützten Merkmalen sein.', 4),
('G-ROL-011', 'de', 'Work-Life-Balance-Maßnahmen im Gleichstellungsplan umfassen:', '[{"text":"Nur starre Zeitpläne","correct":false},{"text":"Flexible Regelungen und Familienunterstützung","correct":true},{"text":"Keine Anpassungen","correct":false},{"text":"Nur für Frauen","correct":false}]', 'Work-Life-Balance-Maßnahmen unterstützen alle Mitarbeiter beim Management von Arbeit und persönlichen Verantwortlichkeiten.', 5),
('G-ROL-011', 'de', 'Die gesetzliche Grundlage für den Gleichstellungsplan stammt von:', '[{"text":"Unternehmenspräferenz","correct":false},{"text":"LO 3/2007 und RD 901/2020","correct":true},{"text":"Nur Branchenrichtlinien","correct":false},{"text":"Kundenanfragen","correct":false}]', 'Diese Gesetze schreiben Gleichstellung am Arbeitsplatz vor und legen Anforderungen für Gleichstellungspläne fest.', 6),
('G-ROL-011', 'de', 'Gleicher Zugang zu Schulung und Beförderung bedeutet:', '[{"text":"Nur bestimmte Mitarbeiter erhalten Schulung","correct":false},{"text":"Alle Mitarbeiter haben gleiche Chancen","correct":true},{"text":"Beförderungen nur für bestimmte Gruppen","correct":false},{"text":"Schulung ist optional","correct":false}]', 'Alle Mitarbeiter müssen gleichen Zugang zu Schulung und Karriereentwicklungsmöglichkeiten haben.', 7),
('G-ROL-011', 'de', 'Wie oft sollte der Gleichstellungsplan überprüft werden?', '[{"text":"Niemals","correct":false},{"text":"Regelmäßig überwacht und überprüft","correct":true},{"text":"Nur einmal bei Erstellung","correct":false},{"text":"Nur wenn Probleme auftreten","correct":false}]', 'Der Gleichstellungsplan erfordert regelmäßige Überwachung und Überprüfung, um Wirksamkeit sicherzustellen.', 8);

-- G-ROL-012: Digital Disconnection Right
INSERT INTO training_test_questions (guide_code, language, question, options, explanation, sort_order) VALUES

-- English
('G-ROL-012', 'en', 'What does the right to digital disconnection mean?', '[{"text":"No internet at work","correct":false},{"text":"No obligation to respond to work messages outside hours","correct":true},{"text":"Cannot use phone at work","correct":false},{"text":"Only for managers","correct":false}]', 'Workers have the right to disconnect from work communications during rest periods and outside working hours.', 1),
('G-ROL-012', 'en', 'When does the right to digital disconnection apply?', '[{"text":"During working hours","correct":false},{"text":"Outside working hours and during rest periods","correct":true},{"text":"Only on weekends","correct":false},{"text":"Only during annual vacation","correct":false}]', 'The right applies to all rest periods including daily rest, weekends, and vacation.', 2),
('G-ROL-012', 'en', 'Can an employer require you to answer work emails during vacation?', '[{"text":"Yes, always","correct":false},{"text":"No, except genuine emergencies","correct":true},{"text":"Yes, if important","correct":false},{"text":"Depends on your salary","correct":false}]', 'Digital disconnection during vacation must be respected except in true emergency situations.', 3),
('G-ROL-012', 'en', 'What must the company establish regarding digital disconnection?', '[{"text":"Nothing required","correct":false},{"text":"An internal policy defining the terms","correct":true},{"text":"Only verbal guidance","correct":false},{"text":"Individual agreements only","correct":false}]', 'Companies must establish a clear written policy defining digital disconnection rights and procedures.', 4),
('G-ROL-012', 'en', 'Can a worker be penalized for not responding to work messages outside hours?', '[{"text":"Yes, if urgent","correct":false},{"text":"No, they have the right to disconnect","correct":true},{"text":"Only if in their contract","correct":false},{"text":"Depends on their role","correct":false}]', 'Workers cannot be penalized for exercising their right to digital disconnection.', 5),
('G-ROL-012', 'en', 'The legal basis for digital disconnection comes from:', '[{"text":"Company policy only","correct":false},{"text":"LO 3/2018 LOPDGDD Art. 88 and ET Art. 20 bis","correct":true},{"text":"Industry customs","correct":false},{"text":"Informal agreement","correct":false}]', 'These laws establish the right to digital disconnection as a fundamental worker right.', 6),
('G-ROL-012', 'en', 'Who should lead by example in respecting digital disconnection?', '[{"text":"Only new employees","correct":false},{"text":"Managers and supervisors","correct":true},{"text":"Only HR department","correct":false},{"text":"No one specifically","correct":false}]', 'Managers must model appropriate digital disconnection behavior to establish organizational culture.', 7),
('G-ROL-012', 'en', 'What constitutes a genuine emergency for digital connection outside hours?', '[{"text":"Any work question","correct":false},{"text":"True urgent matters affecting operations or safety","correct":true},{"text":"Manager preference","correct":false},{"text":"Routine tasks","correct":false}]', 'Only genuine emergencies affecting safety or critical operations justify contact outside working hours.', 8),

-- Spanish
('G-ROL-012', 'es', '¿Qué significa el derecho a la desconexión digital?', '[{"text":"Sin internet en el trabajo","correct":false},{"text":"Sin obligación de responder mensajes laborales fuera de horas","correct":true},{"text":"No se puede usar el teléfono en el trabajo","correct":false},{"text":"Solo para gerentes","correct":false}]', 'Los trabajadores tienen derecho a desconectarse de las comunicaciones laborales durante los periodos de descanso y fuera del horario laboral.', 1),
('G-ROL-012', 'es', '¿Cuándo se aplica el derecho a la desconexión digital?', '[{"text":"Durante las horas de trabajo","correct":false},{"text":"Fuera del horario laboral y durante periodos de descanso","correct":true},{"text":"Solo los fines de semana","correct":false},{"text":"Solo durante vacaciones anuales","correct":false}]', 'El derecho se aplica a todos los periodos de descanso incluyendo descanso diario, fines de semana y vacaciones.', 2),
('G-ROL-012', 'es', '¿Puede un empleador exigir que responda correos de trabajo durante las vacaciones?', '[{"text":"Sí, siempre","correct":false},{"text":"No, excepto emergencias genuinas","correct":true},{"text":"Sí, si es importante","correct":false},{"text":"Depende de su salario","correct":false}]', 'La desconexión digital durante las vacaciones debe respetarse excepto en situaciones de verdadera emergencia.', 3),
('G-ROL-012', 'es', '¿Qué debe establecer la empresa respecto a la desconexión digital?', '[{"text":"Nada requerido","correct":false},{"text":"Una política interna que defina los términos","correct":true},{"text":"Solo orientación verbal","correct":false},{"text":"Solo acuerdos individuales","correct":false}]', 'Las empresas deben establecer una política escrita clara que defina los derechos y procedimientos de desconexión digital.', 4),
('G-ROL-012', 'es', '¿Se puede penalizar a un trabajador por no responder mensajes de trabajo fuera de horas?', '[{"text":"Sí, si es urgente","correct":false},{"text":"No, tienen el derecho a desconectar","correct":true},{"text":"Solo si está en su contrato","correct":false},{"text":"Depende de su rol","correct":false}]', 'Los trabajadores no pueden ser penalizados por ejercer su derecho a la desconexión digital.', 5),
('G-ROL-012', 'es', 'La base legal para la desconexión digital proviene de:', '[{"text":"Solo política de la empresa","correct":false},{"text":"LO 3/2018 LOPDGDD Art. 88 y ET Art. 20 bis","correct":true},{"text":"Costumbres de la industria","correct":false},{"text":"Acuerdo informal","correct":false}]', 'Estas leyes establecen el derecho a la desconexión digital como un derecho fundamental del trabajador.', 6),
('G-ROL-012', 'es', '¿Quién debe dar ejemplo respetando la desconexión digital?', '[{"text":"Solo empleados nuevos","correct":false},{"text":"Gerentes y supervisores","correct":true},{"text":"Solo el departamento de RRHH","correct":false},{"text":"Nadie específicamente","correct":false}]', 'Los gerentes deben modelar un comportamiento apropiado de desconexión digital para establecer la cultura organizacional.', 7),
('G-ROL-012', 'es', '¿Qué constituye una emergencia genuina para conexión digital fuera de horas?', '[{"text":"Cualquier pregunta de trabajo","correct":false},{"text":"Asuntos verdaderamente urgentes que afecten operaciones o seguridad","correct":true},{"text":"Preferencia del gerente","correct":false},{"text":"Tareas rutinarias","correct":false}]', 'Solo emergencias genuinas que afecten la seguridad o las operaciones críticas justifican el contacto fuera del horario laboral.', 8),

-- Dutch
('G-ROL-012', 'nl', 'Wat betekent het recht op digitale ontkoppeling?', '[{"text":"Geen internet op het werk","correct":false},{"text":"Geen verplichting om werkberichten buiten werktijd te beantwoorden","correct":true},{"text":"Kan telefoon niet gebruiken op het werk","correct":false},{"text":"Alleen voor managers","correct":false}]', 'Werknemers hebben het recht om los te koppelen van werkcommunicatie tijdens rustperiodes en buiten werktijden.', 1),
('G-ROL-012', 'nl', 'Wanneer is het recht op digitale ontkoppeling van toepassing?', '[{"text":"Tijdens werkuren","correct":false},{"text":"Buiten werktijd en tijdens rustperiodes","correct":true},{"text":"Alleen in weekenden","correct":false},{"text":"Alleen tijdens jaarlijkse vakantie","correct":false}]', 'Het recht is van toepassing op alle rustperiodes inclusief dagelijkse rust, weekenden en vakantie.', 2),
('G-ROL-012', 'nl', 'Kan een werkgever eisen dat u werk-e-mails beantwoordt tijdens vakantie?', '[{"text":"Ja, altijd","correct":false},{"text":"Nee, behalve echte noodgevallen","correct":true},{"text":"Ja, als het belangrijk is","correct":false},{"text":"Hangt af van uw salaris","correct":false}]', 'Digitale ontkoppeling tijdens vakantie moet worden gerespecteerd behalve in echte noodsituaties.', 3),
('G-ROL-012', 'nl', 'Wat moet het bedrijf vaststellen met betrekking tot digitale ontkoppeling?', '[{"text":"Niets vereist","correct":false},{"text":"Een intern beleid dat de voorwaarden definieert","correct":true},{"text":"Alleen mondelinge begeleiding","correct":false},{"text":"Alleen individuele overeenkomsten","correct":false}]', 'Bedrijven moeten een duidelijk schriftelijk beleid vaststellen dat rechten en procedures voor digitale ontkoppeling definieert.', 4),
('G-ROL-012', 'nl', 'Kan een werknemer worden gestraft voor het niet reageren op werkberichten buiten werktijd?', '[{"text":"Ja, als het dringend is","correct":false},{"text":"Nee, ze hebben het recht om los te koppelen","correct":true},{"text":"Alleen als het in hun contract staat","correct":false},{"text":"Hangt af van hun rol","correct":false}]', 'Werknemers kunnen niet worden gestraft voor het uitoefenen van hun recht op digitale ontkoppeling.', 5),
('G-ROL-012', 'nl', 'De wettelijke basis voor digitale ontkoppeling komt van:', '[{"text":"Alleen bedrijfsbeleid","correct":false},{"text":"LO 3/2018 LOPDGDD Art. 88 en ET Art. 20 bis","correct":true},{"text":"Branchegewoonten","correct":false},{"text":"Informele overeenkomst","correct":false}]', 'Deze wetten stellen het recht op digitale ontkoppeling vast als een fundamenteel werknemersrecht.', 6),
('G-ROL-012', 'nl', 'Wie moet het goede voorbeeld geven in het respecteren van digitale ontkoppeling?', '[{"text":"Alleen nieuwe werknemers","correct":false},{"text":"Managers en supervisors","correct":true},{"text":"Alleen HR-afdeling","correct":false},{"text":"Niemand specifiek","correct":false}]', 'Managers moeten gepast gedrag op het gebied van digitale ontkoppeling modelleren om de organisatiecultuur te vestigen.', 7),
('G-ROL-012', 'nl', 'Wat vormt een echt noodgeval voor digitale connectie buiten werktijd?', '[{"text":"Elke werkvraag","correct":false},{"text":"Echt urgente zaken die operaties of veiligheid beïnvloeden","correct":true},{"text":"Voorkeur van de manager","correct":false},{"text":"Routinetaken","correct":false}]', 'Alleen echte noodgevallen die de veiligheid of kritieke operaties beïnvloeden rechtvaardigen contact buiten werktijden.', 8),

-- German
('G-ROL-012', 'de', 'Was bedeutet das Recht auf digitale Abkopplung?', '[{"text":"Kein Internet bei der Arbeit","correct":false},{"text":"Keine Verpflichtung, Arbeitsnachrichten außerhalb der Arbeitszeit zu beantworten","correct":true},{"text":"Kann Telefon nicht bei der Arbeit benutzen","correct":false},{"text":"Nur für Manager","correct":false}]', 'Arbeitnehmer haben das Recht, sich während der Ruhezeiten und außerhalb der Arbeitszeiten von der Arbeitskommunikation abzukoppeln.', 1),
('G-ROL-012', 'de', 'Wann gilt das Recht auf digitale Abkopplung?', '[{"text":"Während der Arbeitszeiten","correct":false},{"text":"Außerhalb der Arbeitszeit und während Ruhezeiten","correct":true},{"text":"Nur an Wochenenden","correct":false},{"text":"Nur während des Jahresurlaubs","correct":false}]', 'Das Recht gilt für alle Ruhezeiten einschließlich täglicher Ruhe, Wochenenden und Urlaub.', 2),
('G-ROL-012', 'de', 'Kann ein Arbeitgeber verlangen, dass Sie Arbeits-E-Mails während des Urlaubs beantworten?', '[{"text":"Ja, immer","correct":false},{"text":"Nein, außer echte Notfälle","correct":true},{"text":"Ja, wenn es wichtig ist","correct":false},{"text":"Hängt von Ihrem Gehalt ab","correct":false}]', 'Digitale Abkopplung während des Urlaubs muss respektiert werden außer in echten Notfallsituationen.', 3),
('G-ROL-012', 'de', 'Was muss das Unternehmen bezüglich digitaler Abkopplung festlegen?', '[{"text":"Nichts erforderlich","correct":false},{"text":"Eine interne Richtlinie, die die Bedingungen definiert","correct":true},{"text":"Nur mündliche Anleitung","correct":false},{"text":"Nur individuelle Vereinbarungen","correct":false}]', 'Unternehmen müssen eine klare schriftliche Richtlinie festlegen, die Rechte und Verfahren zur digitalen Abkopplung definiert.', 4),
('G-ROL-012', 'de', 'Kann ein Arbeitnehmer bestraft werden, wenn er außerhalb der Arbeitszeit nicht auf Arbeitsnachrichten reagiert?', '[{"text":"Ja, wenn es dringend ist","correct":false},{"text":"Nein, sie haben das Recht auf Abkopplung","correct":true},{"text":"Nur wenn es in ihrem Vertrag steht","correct":false},{"text":"Hängt von ihrer Rolle ab","correct":false}]', 'Arbeitnehmer können nicht für die Ausübung ihres Rechts auf digitale Abkopplung bestraft werden.', 5),
('G-ROL-012', 'de', 'Die gesetzliche Grundlage für digitale Abkopplung stammt von:', '[{"text":"Nur Unternehmensrichtlinie","correct":false},{"text":"LO 3/2018 LOPDGDD Art. 88 und ET Art. 20 bis","correct":true},{"text":"Branchenbräuche","correct":false},{"text":"Informelle Vereinbarung","correct":false}]', 'Diese Gesetze etablieren das Recht auf digitale Abkopplung als grundlegendes Arbeitnehmerrecht.', 6),
('G-ROL-012', 'de', 'Wer sollte mit gutem Beispiel vorangehen bei der Respektierung digitaler Abkopplung?', '[{"text":"Nur neue Mitarbeiter","correct":false},{"text":"Manager und Vorgesetzte","correct":true},{"text":"Nur Personalabteilung","correct":false},{"text":"Niemand speziell","correct":false}]', 'Manager müssen angemessenes Verhalten bezüglich digitaler Abkopplung vorleben, um die Unternehmenskultur zu etablieren.', 7),
('G-ROL-012', 'de', 'Was stellt einen echten Notfall für digitale Verbindung außerhalb der Arbeitszeit dar?', '[{"text":"Jede Arbeitsfrage","correct":false},{"text":"Echte dringende Angelegenheiten, die Betrieb oder Sicherheit betreffen","correct":true},{"text":"Vorliebe des Managers","correct":false},{"text":"Routineaufgaben","correct":false}]', 'Nur echte Notfälle, die Sicherheit oder kritische Operationen betreffen, rechtfertigen Kontakt außerhalb der Arbeitszeiten.', 8);

-- G-ROL-013: Workplace Bullying Prevention
INSERT INTO training_test_questions (guide_code, language, question, options, explanation, sort_order) VALUES

-- English
('G-ROL-013', 'en', 'What is workplace bullying (acoso laboral)?', '[{"text":"One-time disagreement","correct":false},{"text":"Repeated hostile behavior creating intimidating environment","correct":true},{"text":"Normal work criticism","correct":false},{"text":"Friendly workplace banter","correct":false}]', 'Workplace bullying involves repeated hostile actions that create an intimidating, degrading, or offensive work environment.', 1),
('G-ROL-013', 'en', 'Which of the following is a sign of workplace bullying?', '[{"text":"Constructive feedback","correct":false},{"text":"Systematic exclusion or humiliation","correct":true},{"text":"Performance reviews","correct":false},{"text":"Normal work assignments","correct":false}]', 'Systematic exclusion, humiliation, or isolation are indicators of workplace bullying.', 2),
('G-ROL-013', 'en', 'What should you do if you experience workplace bullying?', '[{"text":"Keep it to yourself","correct":false},{"text":"Report through official channels","correct":true},{"text":"Confront the person alone","correct":false},{"text":"Quit immediately","correct":false}]', 'Workplace bullying should be reported through official complaint channels for investigation.', 3),
('G-ROL-013', 'en', 'How are workplace bullying complaints investigated?', '[{"text":"Made public immediately","correct":false},{"text":"Confidentially investigated","correct":true},{"text":"Not investigated","correct":false},{"text":"Only if repeated","correct":false}]', 'All bullying complaints are investigated confidentially to protect all parties.', 4),
('G-ROL-013', 'en', 'What support is provided to affected workers?', '[{"text":"No support","correct":false},{"text":"Support and protection during investigation","correct":true},{"text":"Only financial compensation","correct":false},{"text":"Transfer to another city","correct":false}]', 'Workers who report bullying receive support and protection throughout the investigation process.', 5),
('G-ROL-013', 'en', 'The legal basis for workplace bullying prevention comes from:', '[{"text":"Company preference only","correct":false},{"text":"Ley 31/1995, ET Art. 4.2.e, CC Art. 173.1","correct":true},{"text":"Informal guidelines","correct":false},{"text":"Customer feedback","correct":false}]', 'These laws establish protections against workplace bullying and dignity at work.', 6),
('G-ROL-013', 'en', 'What is the goal of workplace bullying prevention?', '[{"text":"Punish all conflicts","correct":false},{"text":"Foster a respectful work culture","correct":true},{"text":"Eliminate all criticism","correct":false},{"text":"Avoid all difficult conversations","correct":false}]', 'Prevention aims to create and maintain a culture of mutual respect and dignity in the workplace.', 7),
('G-ROL-013', 'en', 'What actions can be taken against perpetrators?', '[{"text":"No actions possible","correct":false},{"text":"Sanctions based on severity","correct":true},{"text":"Only informal warnings","correct":false},{"text":"Automatic dismissal only","correct":false}]', 'Sanctions for workplace bullying range from warnings to termination based on the severity and circumstances.', 8),

-- Spanish
('G-ROL-013', 'es', '¿Qué es el acoso laboral?', '[{"text":"Un desacuerdo único","correct":false},{"text":"Comportamiento hostil repetido que crea un entorno intimidante","correct":true},{"text":"Crítica laboral normal","correct":false},{"text":"Bromas amistosas en el lugar de trabajo","correct":false}]', 'El acoso laboral implica acciones hostiles repetidas que crean un entorno de trabajo intimidante, degradante u ofensivo.', 1),
('G-ROL-013', 'es', '¿Cuál de los siguientes es una señal de acoso laboral?', '[{"text":"Retroalimentación constructiva","correct":false},{"text":"Exclusión o humillación sistemática","correct":true},{"text":"Evaluaciones de desempeño","correct":false},{"text":"Asignaciones de trabajo normales","correct":false}]', 'La exclusión, humillación o aislamiento sistemáticos son indicadores de acoso laboral.', 2),
('G-ROL-013', 'es', '¿Qué debe hacer si experimenta acoso laboral?', '[{"text":"Guardárselo para usted","correct":false},{"text":"Denunciar a través de canales oficiales","correct":true},{"text":"Confrontar a la persona solo","correct":false},{"text":"Renunciar inmediatamente","correct":false}]', 'El acoso laboral debe denunciarse a través de canales oficiales de denuncia para su investigación.', 3),
('G-ROL-013', 'es', '¿Cómo se investigan las denuncias de acoso laboral?', '[{"text":"Se hacen públicas inmediatamente","correct":false},{"text":"Se investigan confidencialmente","correct":true},{"text":"No se investigan","correct":false},{"text":"Solo si se repite","correct":false}]', 'Todas las denuncias de acoso se investigan confidencialmente para proteger a todas las partes.', 4),
('G-ROL-013', 'es', '¿Qué apoyo se proporciona a los trabajadores afectados?', '[{"text":"Ningún apoyo","correct":false},{"text":"Apoyo y protección durante la investigación","correct":true},{"text":"Solo compensación financiera","correct":false},{"text":"Traslado a otra ciudad","correct":false}]', 'Los trabajadores que denuncian acoso reciben apoyo y protección durante todo el proceso de investigación.', 5),
('G-ROL-013', 'es', 'La base legal para la prevención del acoso laboral proviene de:', '[{"text":"Solo preferencia de la empresa","correct":false},{"text":"Ley 31/1995, ET Art. 4.2.e, CC Art. 173.1","correct":true},{"text":"Directrices informales","correct":false},{"text":"Comentarios de clientes","correct":false}]', 'Estas leyes establecen protecciones contra el acoso laboral y la dignidad en el trabajo.', 6),
('G-ROL-013', 'es', '¿Cuál es el objetivo de la prevención del acoso laboral?', '[{"text":"Castigar todos los conflictos","correct":false},{"text":"Fomentar una cultura laboral respetuosa","correct":true},{"text":"Eliminar toda crítica","correct":false},{"text":"Evitar todas las conversaciones difíciles","correct":false}]', 'La prevención tiene como objetivo crear y mantener una cultura de respeto mutuo y dignidad en el lugar de trabajo.', 7),
('G-ROL-013', 'es', '¿Qué acciones se pueden tomar contra los perpetradores?', '[{"text":"No son posibles acciones","correct":false},{"text":"Sanciones basadas en la gravedad","correct":true},{"text":"Solo advertencias informales","correct":false},{"text":"Solo despido automático","correct":false}]', 'Las sanciones por acoso laboral van desde advertencias hasta el despido según la gravedad y las circunstancias.', 8),

-- Dutch
('G-ROL-013', 'nl', 'Wat is pesten op de werkplek (acoso laboral)?', '[{"text":"Eenmalig meningsverschil","correct":false},{"text":"Herhaald vijandig gedrag dat intimiderende omgeving creëert","correct":true},{"text":"Normale werkkritiek","correct":false},{"text":"Vriendelijk geplag op de werkplek","correct":false}]', 'Pesten op de werkplek omvat herhaalde vijandige acties die een intimiderende, vernederende of beledigende werkomgeving creëren.', 1),
('G-ROL-013', 'nl', 'Welk van de volgende is een teken van pesten op de werkplek?', '[{"text":"Constructieve feedback","correct":false},{"text":"Systematische uitsluiting of vernedering","correct":true},{"text":"Prestatiebeoordelingen","correct":false},{"text":"Normale werkopdrachten","correct":false}]', 'Systematische uitsluiting, vernedering of isolatie zijn indicatoren van pesten op de werkplek.', 2),
('G-ROL-013', 'nl', 'Wat moet u doen als u pesten op de werkplek ervaart?', '[{"text":"Het voor uzelf houden","correct":false},{"text":"Melden via officiële kanalen","correct":true},{"text":"De persoon alleen confronteren","correct":false},{"text":"Onmiddellijk ontslag nemen","correct":false}]', 'Pesten op de werkplek moet worden gemeld via officiële klachtenkanalen voor onderzoek.', 3),
('G-ROL-013', 'nl', 'Hoe worden klachten over pesten op de werkplek onderzocht?', '[{"text":"Onmiddellijk openbaar gemaakt","correct":false},{"text":"Vertrouwelijk onderzocht","correct":true},{"text":"Niet onderzocht","correct":false},{"text":"Alleen als het zich herhaalt","correct":false}]', 'Alle klachten over pesten worden vertrouwelijk onderzocht om alle partijen te beschermen.', 4),
('G-ROL-013', 'nl', 'Welke ondersteuning wordt geboden aan getroffen werknemers?', '[{"text":"Geen ondersteuning","correct":false},{"text":"Ondersteuning en bescherming tijdens onderzoek","correct":true},{"text":"Alleen financiële compensatie","correct":false},{"text":"Overplaatsing naar een andere stad","correct":false}]', 'Werknemers die pesten melden ontvangen ondersteuning en bescherming gedurende het hele onderzoeksproces.', 5),
('G-ROL-013', 'nl', 'De wettelijke basis voor preventie van pesten op de werkplek komt van:', '[{"text":"Alleen bedrijfsvoorkeur","correct":false},{"text":"Ley 31/1995, ET Art. 4.2.e, CC Art. 173.1","correct":true},{"text":"Informele richtlijnen","correct":false},{"text":"Klantfeedback","correct":false}]', 'Deze wetten stellen bescherming vast tegen pesten op de werkplek en waardigheid op het werk.', 6),
('G-ROL-013', 'nl', 'Wat is het doel van preventie van pesten op de werkplek?', '[{"text":"Alle conflicten straffen","correct":false},{"text":"Een respectvolle werkcultuur bevorderen","correct":true},{"text":"Alle kritiek elimineren","correct":false},{"text":"Alle moeilijke gesprekken vermijden","correct":false}]', 'Preventie heeft tot doel een cultuur van wederzijds respect en waardigheid op de werkplek te creëren en te handhaven.', 7),
('G-ROL-013', 'nl', 'Welke acties kunnen worden ondernomen tegen daders?', '[{"text":"Geen acties mogelijk","correct":false},{"text":"Sancties op basis van ernst","correct":true},{"text":"Alleen informele waarschuwingen","correct":false},{"text":"Alleen automatisch ontslag","correct":false}]', 'Sancties voor pesten op de werkplek variëren van waarschuwingen tot ontslag op basis van de ernst en omstandigheden.', 8),

-- German
('G-ROL-013', 'de', 'Was ist Mobbing am Arbeitsplatz (acoso laboral)?', '[{"text":"Einmalige Meinungsverschiedenheit","correct":false},{"text":"Wiederholtes feindseliges Verhalten, das einschüchternde Umgebung schafft","correct":true},{"text":"Normale Arbeitskritik","correct":false},{"text":"Freundliches Geplänkel am Arbeitsplatz","correct":false}]', 'Mobbing am Arbeitsplatz umfasst wiederholte feindselige Handlungen, die eine einschüchternde, erniedrigende oder beleidigende Arbeitsumgebung schaffen.', 1),
('G-ROL-013', 'de', 'Welches der folgenden ist ein Zeichen von Mobbing am Arbeitsplatz?', '[{"text":"Konstruktives Feedback","correct":false},{"text":"Systematischer Ausschluss oder Demütigung","correct":true},{"text":"Leistungsbeurteilungen","correct":false},{"text":"Normale Arbeitsaufgaben","correct":false}]', 'Systematischer Ausschluss, Demütigung oder Isolation sind Indikatoren für Mobbing am Arbeitsplatz.', 2),
('G-ROL-013', 'de', 'Was sollten Sie tun, wenn Sie Mobbing am Arbeitsplatz erleben?', '[{"text":"Es für sich behalten","correct":false},{"text":"Über offizielle Kanäle melden","correct":true},{"text":"Die Person allein konfrontieren","correct":false},{"text":"Sofort kündigen","correct":false}]', 'Mobbing am Arbeitsplatz sollte über offizielle Beschwerdekanäle zur Untersuchung gemeldet werden.', 3),
('G-ROL-013', 'de', 'Wie werden Beschwerden über Mobbing am Arbeitsplatz untersucht?', '[{"text":"Sofort öffentlich gemacht","correct":false},{"text":"Vertraulich untersucht","correct":true},{"text":"Nicht untersucht","correct":false},{"text":"Nur wenn wiederholt","correct":false}]', 'Alle Mobbingbeschwerden werden vertraulich untersucht, um alle Parteien zu schützen.', 4),
('G-ROL-013', 'de', 'Welche Unterstützung wird betroffenen Arbeitnehmern geboten?', '[{"text":"Keine Unterstützung","correct":false},{"text":"Unterstützung und Schutz während der Untersuchung","correct":true},{"text":"Nur finanzielle Entschädigung","correct":false},{"text":"Transfer in eine andere Stadt","correct":false}]', 'Arbeitnehmer, die Mobbing melden, erhalten während des gesamten Untersuchungsprozesses Unterstützung und Schutz.', 5),
('G-ROL-013', 'de', 'Die gesetzliche Grundlage für Mobbingprävention am Arbeitsplatz stammt von:', '[{"text":"Nur Unternehmenspräferenz","correct":false},{"text":"Ley 31/1995, ET Art. 4.2.e, CC Art. 173.1","correct":true},{"text":"Informelle Richtlinien","correct":false},{"text":"Kundenfeedback","correct":false}]', 'Diese Gesetze etablieren Schutz vor Mobbing am Arbeitsplatz und Würde bei der Arbeit.', 6),
('G-ROL-013', 'de', 'Was ist das Ziel der Mobbingprävention am Arbeitsplatz?', '[{"text":"Alle Konflikte bestrafen","correct":false},{"text":"Eine respektvolle Arbeitskultur fördern","correct":true},{"text":"Alle Kritik eliminieren","correct":false},{"text":"Alle schwierigen Gespräche vermeiden","correct":false}]', 'Prävention zielt darauf ab, eine Kultur gegenseitigen Respekts und Würde am Arbeitsplatz zu schaffen und aufrechtzuerhalten.', 7),
('G-ROL-013', 'de', 'Welche Maßnahmen können gegen Täter ergriffen werden?', '[{"text":"Keine Maßnahmen möglich","correct":false},{"text":"Sanktionen basierend auf Schweregrad","correct":true},{"text":"Nur informelle Warnungen","correct":false},{"text":"Nur automatische Entlassung","correct":false}]', 'Sanktionen für Mobbing am Arbeitsplatz reichen von Verwarnungen bis zur Kündigung je nach Schweregrad und Umständen.', 8);

-- G-ROL-014: Data Protection (GDPR/LOPDGDD)
INSERT INTO training_test_questions (guide_code, language, question, options, explanation, sort_order) VALUES

-- English
('G-ROL-014', 'en', 'What is personal data?', '[{"text":"Only credit card numbers","correct":false},{"text":"Any information identifying an individual","correct":true},{"text":"Only passport numbers","correct":false},{"text":"Only medical records","correct":false}]', 'Personal data includes any information that can identify a person, such as names, emails, phone numbers, and identification numbers.', 1),
('G-ROL-014', 'en', 'What is the principle of data minimization?', '[{"text":"Collect as much data as possible","correct":false},{"text":"Collect only necessary personal data","correct":true},{"text":"Never collect any data","correct":false},{"text":"Collect data without limit","correct":false}]', 'Data minimization means collecting only the personal data that is necessary for the specific purpose.', 2),
('G-ROL-014', 'en', 'When is consent required for data collection?', '[{"text":"Never needed","correct":false},{"text":"Where required by law or no other legal basis","correct":true},{"text":"Always, without exception","correct":false},{"text":"Only for children","correct":false}]', 'Consent is required when there is no other legal basis for processing, such as contract or legitimate interest.', 3),
('G-ROL-014', 'en', 'How should personal data be stored?', '[{"text":"Leave documents on desks","correct":false},{"text":"Securely, both physical and digital","correct":true},{"text":"Share with anyone","correct":false},{"text":"No security needed","correct":false}]', 'Personal data must be protected with appropriate security measures in both physical and digital formats.', 4),
('G-ROL-014', 'en', 'What are individuals\' rights under GDPR?', '[{"text":"No rights","correct":false},{"text":"Access, correction, erasure, portability","correct":true},{"text":"Only access","correct":false},{"text":"Only deletion","correct":false}]', 'Individuals have multiple rights including accessing their data, correcting it, requesting deletion, and data portability.', 5),
('G-ROL-014', 'en', 'What must be done in case of a data breach?', '[{"text":"Keep it secret","correct":false},{"text":"Report within 72 hours to authorities","correct":true},{"text":"Tell only management","correct":false},{"text":"Wait a week before reporting","correct":false}]', 'Data breaches must be reported to the supervisory authority within 72 hours of becoming aware.', 6),
('G-ROL-014', 'en', 'The legal basis for data protection comes from:', '[{"text":"Company policy only","correct":false},{"text":"EU GDPR 2016/679 and LO 3/2018 LOPDGDD","correct":true},{"text":"Industry recommendations","correct":false},{"text":"Informal guidelines","correct":false}]', 'These laws establish comprehensive data protection requirements in the EU and Spain.', 7),
('G-ROL-014', 'en', 'Can you share personal data with others without authorization?', '[{"text":"Yes, with anyone","correct":false},{"text":"No, never without authorization","correct":true},{"text":"Only with friends","correct":false},{"text":"Only by email","correct":false}]', 'Personal data must never be shared without proper authorization and legal basis.', 8),

-- Spanish
('G-ROL-014', 'es', '¿Qué son los datos personales?', '[{"text":"Solo números de tarjetas de crédito","correct":false},{"text":"Cualquier información que identifique a un individuo","correct":true},{"text":"Solo números de pasaporte","correct":false},{"text":"Solo registros médicos","correct":false}]', 'Los datos personales incluyen cualquier información que pueda identificar a una persona, como nombres, correos electrónicos, números de teléfono y números de identificación.', 1),
('G-ROL-014', 'es', '¿Qué es el principio de minimización de datos?', '[{"text":"Recoger tantos datos como sea posible","correct":false},{"text":"Recoger solo los datos personales necesarios","correct":true},{"text":"Nunca recoger ningún dato","correct":false},{"text":"Recoger datos sin límite","correct":false}]', 'La minimización de datos significa recoger solo los datos personales que sean necesarios para el propósito específico.', 2),
('G-ROL-014', 'es', '¿Cuándo se requiere consentimiento para la recopilación de datos?', '[{"text":"Nunca se necesita","correct":false},{"text":"Cuando lo requiere la ley o no hay otra base legal","correct":true},{"text":"Siempre, sin excepción","correct":false},{"text":"Solo para niños","correct":false}]', 'El consentimiento se requiere cuando no hay otra base legal para el procesamiento, como un contrato o interés legítimo.', 3),
('G-ROL-014', 'es', '¿Cómo deben almacenarse los datos personales?', '[{"text":"Dejar documentos en escritorios","correct":false},{"text":"De forma segura, tanto física como digital","correct":true},{"text":"Compartir con cualquiera","correct":false},{"text":"No se necesita seguridad","correct":false}]', 'Los datos personales deben protegerse con medidas de seguridad apropiadas tanto en formatos físicos como digitales.', 4),
('G-ROL-014', 'es', '¿Cuáles son los derechos de los individuos bajo el RGPD?', '[{"text":"Sin derechos","correct":false},{"text":"Acceso, corrección, eliminación, portabilidad","correct":true},{"text":"Solo acceso","correct":false},{"text":"Solo eliminación","correct":false}]', 'Los individuos tienen múltiples derechos incluyendo acceder a sus datos, corregirlos, solicitar eliminación y portabilidad de datos.', 5),
('G-ROL-014', 'es', '¿Qué se debe hacer en caso de una violación de datos?', '[{"text":"Mantenerlo en secreto","correct":false},{"text":"Reportar dentro de 72 horas a las autoridades","correct":true},{"text":"Decir solo a la gerencia","correct":false},{"text":"Esperar una semana antes de reportar","correct":false}]', 'Las violaciones de datos deben reportarse a la autoridad supervisora dentro de las 72 horas de conocerse.', 6),
('G-ROL-014', 'es', 'La base legal para la protección de datos proviene de:', '[{"text":"Solo política de la empresa","correct":false},{"text":"RGPD UE 2016/679 y LO 3/2018 LOPDGDD","correct":true},{"text":"Recomendaciones de la industria","correct":false},{"text":"Directrices informales","correct":false}]', 'Estas leyes establecen requisitos integrales de protección de datos en la UE y España.', 7),
('G-ROL-014', 'es', '¿Puede compartir datos personales con otros sin autorización?', '[{"text":"Sí, con cualquiera","correct":false},{"text":"No, nunca sin autorización","correct":true},{"text":"Solo con amigos","correct":false},{"text":"Solo por correo electrónico","correct":false}]', 'Los datos personales nunca deben compartirse sin la autorización y base legal adecuadas.', 8),

-- Dutch
('G-ROL-014', 'nl', 'Wat zijn persoonsgegevens?', '[{"text":"Alleen creditcardnummers","correct":false},{"text":"Alle informatie die een individu identificeert","correct":true},{"text":"Alleen paspoortnummers","correct":false},{"text":"Alleen medische dossiers","correct":false}]', 'Persoonsgegevens omvatten alle informatie die een persoon kan identificeren, zoals namen, e-mails, telefoonnummers en identificatienummers.', 1),
('G-ROL-014', 'nl', 'Wat is het principe van dataminimalisatie?', '[{"text":"Zoveel mogelijk gegevens verzamelen","correct":false},{"text":"Alleen noodzakelijke persoonsgegevens verzamelen","correct":true},{"text":"Nooit gegevens verzamelen","correct":false},{"text":"Gegevens zonder limiet verzamelen","correct":false}]', 'Dataminimalisatie betekent alleen de persoonsgegevens verzamelen die nodig zijn voor het specifieke doel.', 2),
('G-ROL-014', 'nl', 'Wanneer is toestemming vereist voor gegevensverzameling?', '[{"text":"Nooit nodig","correct":false},{"text":"Waar vereist door wet of geen andere rechtsgrond","correct":true},{"text":"Altijd, zonder uitzondering","correct":false},{"text":"Alleen voor kinderen","correct":false}]', 'Toestemming is vereist wanneer er geen andere rechtsgrond is voor verwerking, zoals een contract of gerechtvaardigd belang.', 3),
('G-ROL-014', 'nl', 'Hoe moeten persoonsgegevens worden opgeslagen?', '[{"text":"Documenten op bureaus laten liggen","correct":false},{"text":"Veilig, zowel fysiek als digitaal","correct":true},{"text":"Met iedereen delen","correct":false},{"text":"Geen beveiliging nodig","correct":false}]', 'Persoonsgegevens moeten worden beschermd met passende beveiligingsmaatregelen in zowel fysieke als digitale formaten.', 4),
('G-ROL-014', 'nl', 'Wat zijn de rechten van individuen onder AVG?', '[{"text":"Geen rechten","correct":false},{"text":"Toegang, correctie, verwijdering, overdraagbaarheid","correct":true},{"text":"Alleen toegang","correct":false},{"text":"Alleen verwijdering","correct":false}]', 'Individuen hebben meerdere rechten waaronder toegang tot hun gegevens, correctie, verwijdering aanvragen en data-overdraagbaarheid.', 5),
('G-ROL-014', 'nl', 'Wat moet worden gedaan in geval van een datalek?', '[{"text":"Geheimhouden","correct":false},{"text":"Binnen 72 uur rapporteren aan autoriteiten","correct":true},{"text":"Alleen management vertellen","correct":false},{"text":"Een week wachten voor rapportage","correct":false}]', 'Datalekken moeten binnen 72 uur na bekendwording worden gemeld aan de toezichthoudende autoriteit.', 6),
('G-ROL-014', 'nl', 'De wettelijke basis voor gegevensbescherming komt van:', '[{"text":"Alleen bedrijfsbeleid","correct":false},{"text":"EU AVG 2016/679 en LO 3/2018 LOPDGDD","correct":true},{"text":"Branche-aanbevelingen","correct":false},{"text":"Informele richtlijnen","correct":false}]', 'Deze wetten stellen uitgebreide vereisten voor gegevensbescherming vast in de EU en Spanje.', 7),
('G-ROL-014', 'nl', 'Kunt u persoonsgegevens met anderen delen zonder toestemming?', '[{"text":"Ja, met iedereen","correct":false},{"text":"Nee, nooit zonder toestemming","correct":true},{"text":"Alleen met vrienden","correct":false},{"text":"Alleen per e-mail","correct":false}]', 'Persoonsgegevens mogen nooit worden gedeeld zonder de juiste toestemming en rechtsgrond.', 8),

-- German
('G-ROL-014', 'de', 'Was sind personenbezogene Daten?', '[{"text":"Nur Kreditkartennummern","correct":false},{"text":"Alle Informationen, die eine Person identifizieren","correct":true},{"text":"Nur Passnummern","correct":false},{"text":"Nur Krankenakten","correct":false}]', 'Personenbezogene Daten umfassen alle Informationen, die eine Person identifizieren können, wie Namen, E-Mails, Telefonnummern und Identifikationsnummern.', 1),
('G-ROL-014', 'de', 'Was ist das Prinzip der Datenminimierung?', '[{"text":"So viele Daten wie möglich sammeln","correct":false},{"text":"Nur notwendige personenbezogene Daten sammeln","correct":true},{"text":"Niemals Daten sammeln","correct":false},{"text":"Daten ohne Limit sammeln","correct":false}]', 'Datenminimierung bedeutet, nur die personenbezogenen Daten zu sammeln, die für den spezifischen Zweck notwendig sind.', 2),
('G-ROL-014', 'de', 'Wann ist eine Einwilligung für die Datenerhebung erforderlich?', '[{"text":"Niemals erforderlich","correct":false},{"text":"Wo gesetzlich vorgeschrieben oder keine andere Rechtsgrundlage","correct":true},{"text":"Immer, ohne Ausnahme","correct":false},{"text":"Nur für Kinder","correct":false}]', 'Einwilligung ist erforderlich, wenn keine andere Rechtsgrundlage für die Verarbeitung vorliegt, wie ein Vertrag oder berechtigtes Interesse.', 3),
('G-ROL-014', 'de', 'Wie sollten personenbezogene Daten gespeichert werden?', '[{"text":"Dokumente auf Schreibtischen lassen","correct":false},{"text":"Sicher, sowohl physisch als auch digital","correct":true},{"text":"Mit jedem teilen","correct":false},{"text":"Keine Sicherheit erforderlich","correct":false}]', 'Personenbezogene Daten müssen mit angemessenen Sicherheitsmaßnahmen sowohl in physischen als auch digitalen Formaten geschützt werden.', 4),
('G-ROL-014', 'de', 'Welche Rechte haben Personen unter DSGVO?', '[{"text":"Keine Rechte","correct":false},{"text":"Zugang, Korrektur, Löschung, Übertragbarkeit","correct":true},{"text":"Nur Zugang","correct":false},{"text":"Nur Löschung","correct":false}]', 'Personen haben mehrere Rechte, einschließlich Zugang zu ihren Daten, Korrektur, Löschung beantragen und Datenübertragbarkeit.', 5),
('G-ROL-014', 'de', 'Was muss im Fall einer Datenschutzverletzung getan werden?', '[{"text":"Geheimhalten","correct":false},{"text":"Innerhalb von 72 Stunden den Behörden melden","correct":true},{"text":"Nur der Geschäftsführung sagen","correct":false},{"text":"Eine Woche vor der Meldung warten","correct":false}]', 'Datenschutzverletzungen müssen innerhalb von 72 Stunden nach Bekanntwerden der Aufsichtsbehörde gemeldet werden.', 6),
('G-ROL-014', 'de', 'Die gesetzliche Grundlage für Datenschutz stammt von:', '[{"text":"Nur Unternehmensrichtlinie","correct":false},{"text":"EU DSGVO 2016/679 und LO 3/2018 LOPDGDD","correct":true},{"text":"Branchenempfehlungen","correct":false},{"text":"Informelle Richtlinien","correct":false}]', 'Diese Gesetze legen umfassende Datenschutzanforderungen in der EU und Spanien fest.', 7),
('G-ROL-014', 'de', 'Können Sie personenbezogene Daten ohne Genehmigung mit anderen teilen?', '[{"text":"Ja, mit jedem","correct":false},{"text":"Nein, niemals ohne Genehmigung","correct":true},{"text":"Nur mit Freunden","correct":false},{"text":"Nur per E-Mail","correct":false}]', 'Personenbezogene Daten dürfen niemals ohne ordnungsgemäße Genehmigung und Rechtsgrundlage geteilt werden.', 8);
